### ISSUE TITLE
Test suite failures with Traits 6.2

### ISSUE THREAD

**Issue by mdickinson** [enthought/mayavi#1004]
The Travis CI cron job is turning up the following errors with Traits master (to become Traits 6.2).

This is likely to be the result of a fix in Traits: previously, range-checking for `Range` traits inside a `List` or `Tuple` in trait was buggy, and that's fixed for Traits 6.2.  enthought/traits#1392

```
======================================================================
ERROR: Test if the MayaVi2 visualization can be deep-copied.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/enthought/mayavi/mayavi/tests/test_optional_collection.py", line 128, in test_deepcopied
    self.check(coll)
  File "/home/travis/build/enthought/mayavi/mayavi/tests/test_optional_collection.py", line 69, in check
    c.contours.append(200)
  File "/home/travis/.edm/envs/edm/lib/python3.6/site-packages/traits/trait_list_object.py", line 726, in append
    super().append(object)
  File "/home/travis/.edm/envs/edm/lib/python3.6/site-packages/traits/trait_list_object.py", line 364, in append
    super().append(self.item_validator(object))
  File "/home/travis/.edm/envs/edm/lib/python3.6/site-packages/traits/trait_list_object.py", line 865, in _item_validator
    return trait_validator(object, self.name, value)
  File "/home/travis/.edm/envs/edm/lib/python3.6/site-packages/traits/trait_types.py", line 1821, in _validate
    self.error(object, name, value)
  File "/home/travis/.edm/envs/edm/lib/python3.6/site-packages/traits/base_trait_handler.py", line 75, in error
    object, name, self.full_info(object, name, value), value
traits.trait_errors.TraitError: Each element of the 'contours' trait of a Contour instance must be 0.9999999999999999 <= a number <= 11.180339887498949, but a value of 200 <class 'int'> was specified.
-------------------- >> begin captured logging << --------------------
mayavi.core.registry: DEBUG: Engine [<mayavi.core.null_engine.NullEngine object at 0x7f7df4735fc0>] named NullEngine2 registered
mayavi.core.registry: DEBUG: Engine named NullEngine2 unregistered
mayavi.core.registry: DEBUG: Engine named None unregistered
--------------------- >> end captured logging << ---------------------
======================================================================
ERROR: Test if the test fixture works
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/enthought/mayavi/mayavi/tests/test_optional_collection.py", line 88, in test_optional_collection
    self.check(coll)
  File "/home/travis/build/enthought/mayavi/mayavi/tests/test_optional_collection.py", line 69, in check
    c.contours.append(200)
  File "/home/travis/.edm/envs/edm/lib/python3.6/site-packages/traits/trait_list_object.py", line 726, in append
    super().append(object)
  File "/home/travis/.edm/envs/edm/lib/python3.6/site-packages/traits/trait_list_object.py", line 364, in append
    super().append(self.item_validator(object))
  File "/home/travis/.edm/envs/edm/lib/python3.6/site-packages/traits/trait_list_object.py", line 865, in _item_validator
    return trait_validator(object, self.name, value)
  File "/home/travis/.edm/envs/edm/lib/python3.6/site-packages/traits/trait_types.py", line 1821, in _validate
    self.error(object, name, value)
  File "/home/travis/.edm/envs/edm/lib/python3.6/site-packages/traits/base_trait_handler.py", line 75, in error
    object, name, self.full_info(object, name, value), value
traits.trait_errors.TraitError: Each element of the 'contours' trait of a Contour instance must be 0.9999999999999999 <= a number <= 11.180339887498949, but a value of 200 <class 'int'> was specified.
-------------------- >> begin captured logging << --------------------
mayavi.core.registry: DEBUG: Engine [<mayavi.core.null_engine.NullEngine object at 0x7f7df4c8d258>] named NullEngine2 registered
mayavi.core.registry: DEBUG: Engine named NullEngine2 unregistered
mayavi.core.registry: DEBUG: Engine named None unregistered
--------------------- >> end captured logging << ---------------------
======================================================================
ERROR: Test if saving a visualization and restoring it works.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/enthought/mayavi/mayavi/tests/test_optional_collection.py", line 113, in test_save_and_restore
    self.check(coll)
  File "/home/travis/build/enthought/mayavi/mayavi/tests/test_optional_collection.py", line 69, in check
    c.contours.append(200)
  File "/home/travis/.edm/envs/edm/lib/python3.6/site-packages/traits/trait_list_object.py", line 726, in append
    super().append(object)
  File "/home/travis/.edm/envs/edm/lib/python3.6/site-packages/traits/trait_list_object.py", line 364, in append
    super().append(self.item_validator(object))
  File "/home/travis/.edm/envs/edm/lib/python3.6/site-packages/traits/trait_list_object.py", line 865, in _item_validator
    return trait_validator(object, self.name, value)
  File "/home/travis/.edm/envs/edm/lib/python3.6/site-packages/traits/trait_types.py", line 1821, in _validate
    self.error(object, name, value)
  File "/home/travis/.edm/envs/edm/lib/python3.6/site-packages/traits/base_trait_handler.py", line 75, in error
    object, name, self.full_info(object, name, value), value
traits.trait_errors.TraitError: Each element of the 'contours' trait of a Contour instance must be 1.0 <= a number <= 11.1803, but a value of 200 <class 'int'> was specified.
-------------------- >> begin captured logging << --------------------
mayavi.core.registry: DEBUG: Engine [<mayavi.core.null_engine.NullEngine object at 0x7f7df4c8d888>] named NullEngine2 registered
mayavi.core.registry: DEBUG: Engine named NullEngine2 unregistered
mayavi.core.registry: DEBUG: Engine named None unregistered
--------------------- >> end captured logging << ---------------------
```

**Comment by mdickinson** [comment]
At a glance, this looks like a shallow bug in the test itself, which hard-codes the value `200` without checking whether it's in range.

**Comment by thephet** [comment]
Hi all, I am having this exact same error. What is the solution?

**Comment by mdickinson** [comment]
@thephet What version of Mayavi are you using, and how are you running the test suite? The fix for this issue should already be included with the most recent release of Mayavi (4.7.3), so you may just need to upgrade.

If you're seeing this error outside the context of running the test suite, you'd probably do better to open a separate issue.
