### ISSUE TITLE
Mayavi doesn't work out of the box on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [enthought/mayavi#1005]
Update : For a temporary workaround, see - https://github.com/enthought/mayavi/issues/1005#issuecomment-765280015

I have ```vtk9-9.0.1``` installed, and its python interface works.

Yet, ```from mayavi import mlab``` fails:
```
$ python3.7 i.py 
Traceback (most recent call last):
  File "i.py", line 1, in <module>
    from mayavi import mlab
  File "/usr/local/lib/python3.7/site-packages/mayavi/mlab.py", line 16, in <module>
    from mayavi.tools.camera import view, roll, yaw, pitch, move
  File "/usr/local/lib/python3.7/site-packages/mayavi/tools/camera.py", line 24, in <module>
    from .engine_manager import get_engine
  File "/usr/local/lib/python3.7/site-packages/mayavi/tools/engine_manager.py", line 14, in <module>
    from mayavi.core.engine import Engine
  File "/usr/local/lib/python3.7/site-packages/mayavi/core/engine.py", line 34, in <module>
    from mayavi.core.ui.mayavi_scene import viewer_factory
  File "/usr/local/lib/python3.7/site-packages/mayavi/core/ui/mayavi_scene.py", line 12, in <module>
    from tvtk.tools.ivtk import IVTK
  File "/usr/local/lib/python3.7/site-packages/tvtk/tools/ivtk.py", line 35, in <module>
    from tvtk.pyface.api import Scene, DecoratedScene
  File "/usr/local/lib/python3.7/site-packages/tvtk/pyface/api.py", line 1, in <module>
    from .decorated_scene import DecoratedScene
  File "/usr/local/lib/python3.7/site-packages/tvtk/pyface/decorated_scene.py", line 12, in <module>
    from tvtk.pyface.toolkit import toolkit_object
  File "/usr/local/lib/python3.7/site-packages/tvtk/pyface/toolkit.py", line 3, in <module>
    toolkit = toolkit_object = find_toolkit('tvtk.toolkits')
  File "/usr/local/lib/python3.7/site-packages/pyface/base_toolkit.py", line 263, in find_toolkit
    return import_toolkit(ETSConfig.toolkit, entry_point)
  File "/usr/local/lib/python3.7/site-packages/pyface/base_toolkit.py", line 217, in import_toolkit
    toolkit_object = plugin.load()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2442, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2465, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'vtk' distribution was not found and is required by the application
```

Same in ```ipython```:
```
$ ipython --gui=wx i.py 
---------------------------------------------------------------------------
DistributionNotFound                      Traceback (most recent call last)
/usr/ports/graphics/py-mayavi/i.py in <module>
----> 1 from mayavi import mlab

/usr/local/lib/python3.7/site-packages/mayavi/mlab.py in <module>
     14 # Mayavi imports
     15 from mayavi.core.common import process_ui_events
---> 16 from mayavi.tools.camera import view, roll, yaw, pitch, move
     17 from mayavi.tools.figure import figure, clf, gcf, savefig, \
     18     draw, sync_camera, close, screenshot

/usr/local/lib/python3.7/site-packages/mayavi/tools/camera.py in <module>
     22 # We can't use gcf, as it creates a circular import in camera management
     23 # routines.
---> 24 from .engine_manager import get_engine
     25 
     26 

/usr/local/lib/python3.7/site-packages/mayavi/tools/engine_manager.py in <module>
     12 from mayavi.preferences.api import preference_manager
     13 from mayavi.core.registry import registry
---> 14 from mayavi.core.engine import Engine
     15 from mayavi.core.off_screen_engine import OffScreenEngine
     16 from mayavi.core.null_engine import NullEngine

/usr/local/lib/python3.7/site-packages/mayavi/core/engine.py in <module>
     32 from mayavi.core.adder_node import AdderNode, SceneAdderNode
     33 from mayavi.preferences.api import preference_manager
---> 34 from mayavi.core.ui.mayavi_scene import viewer_factory
     35 
     36 

/usr/local/lib/python3.7/site-packages/mayavi/core/ui/mayavi_scene.py in <module>
     10 
     11 # Enthought library imports
---> 12 from tvtk.tools.ivtk import IVTK
     13 from tvtk.pyface.api import DecoratedScene
     14 from traits.api import Callable

/usr/local/lib/python3.7/site-packages/tvtk/tools/ivtk.py in <module>
     33 from pyface.api import SplitApplicationWindow, ApplicationWindow
     34 from pyface.api import SplitPanel
---> 35 from tvtk.pyface.api import Scene, DecoratedScene
     36 from pyface.action.api import Action, MenuBarManager,\
     37      MenuManager, Separator

/usr/local/lib/pythpyfaceon3.7/site-packages/tvtk/pyface/api.py in <module>
----> 1 from .decorated_scene import DecoratedScene
      2 from .scene import Scene

/usr/local/lib/python3.7/site-packages/tvtk/pyface/decorated_scene.py in <module>
     10 
     11 # Import the toolkit specific version.
---> 12 from tvtk.pyface.toolkit import toolkit_object
     13 DecoratedScene = toolkit_object('decorated_scene:DecoratedScene')

/usr/local/lib/python3.7/site-packages/tvtk/pyface/toolkit.py in <module>
      1 from pyface.base_toolkit import find_toolkit
      2 
----> 3 toolkit = toolkit_object = find_toolkit('tvtk.toolkits')

/usr/local/lib/python3.7/site-packages/pyface/base_toolkit.py in find_toolkit(entry_point, toolkits, priorities)
    261     """
    262     if ETSConfig.toolkit:
--> 263         return import_toolkit(ETSConfig.toolkit, entry_point)
    264 
    265     entry_points = [

/usr/local/lib/python3.7/site-packages/pyface/base_toolkit.py in import_toolkit(toolkit_name, entry_point)
    215     for plugin in plugins:
    216         try:
--> 217             toolkit_object = plugin.load()
    218             return toolkit_object
    219         except (ImportError, AttributeError) as exc:

/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py in load(self, require, *args, **kwargs)
   2440             )
   2441         if require:
-> 2442             self.require(*args, **kwargs)
   2443         return self.resolve()
   2444 

/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py in require(self, env, installer)
   2463         # requirements for that extra are purely optional and skip over them.
   2464         reqs = self.dist.requires(self.extras)
-> 2465         items = working_set.resolve(reqs, env, installer, extras=self.extras)
   2466         list(map(working_set.add, items))
   2467 

/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py in resolve(self, requirements, env, installer, replace_conflicting, extras)
    784                     if dist is None:
    785                         requirers = required_by.get(req, None)
--> 786                         raise DistributionNotFound(req, requirers)
    787                 to_activate.append(dist)
    788             if dist not in req:

DistributionNotFound: The 'vtk' distribution was not found and is required by the application
```

Mayavi 4.7.2
Python 3.7
FreeBSD 12.2

**Comment by rahulporuri** [comment]
@yurivict thanks for reporting the issue. How did you install mayavi? Are you using system python?

**Comment by yurivict** [comment]
I installed Mayavi through the FreeBSD port framework, it uses ```python setup.py confirure && python setup.py build && python setup.py install```.

**Comment by rahulporuri** [comment]
Can you report `pip freeze` or `python3.7 -m pip freeze`?

I suspect that `vtk` was not automatically picked up when you installed `mayavi`. Can you try installing `vtk` manually if it does not exist in the python environment?

**Comment by yurivict** [comment]
```pip freeze``` doesn't find ```vtk``` because vtk9 only installs runnable python module, but not its corresponding ```.egg-info``` directory that ```pip freeze``` is looking for.

```vtk9``` is installed with ```cmake```, basically the same way as Arch linux does it: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=vtk9

**Comment by rahulporuri** [comment]
> pip freeze doesn't find vtk because vtk9 only installs the runnable python module, but not its corresponding .egg-info directory that pip freeze is looking for.

I can't be sure of this but I think that is also the reason why `mayavi` is not able to find `vtk`. I am not sure how to fix this.

Can you try installing and using `edm` (https://assets.enthought.com/downloads/edm/) or anaconda to install mayavi and vtk?

**Comment by yurivict** [comment]
It seems from its website that ```edm``` is a binary install that doesn't support FreeBSD.
I never used anaconda.

**Comment by rahulporuri** [comment]
> It seems from its website that edm is a binary install that doesn't support FreeBSD.

I apologize but im not too familiar with FreeBSD but can you not use the generic glibc linux installer (.sh file) - for the command-line only installer?

**Comment by yurivict** [comment]
I asked vtk: https://gitlab.kitware.com/vtk/vtk/-/issues/18087

I am after creating the FreeBSD port for Mayavi, and am interested to get vtk and mayavi to play together in a standard way.

**Comment by yurivict** [comment]
> I apologize but im not too familiar with FreeBSD but can you not use the generic glibc linux installer (.sh file) - for the command-line only installer?

No, glibc doesn't exist on FreeBSD, because FreeBSD is not Linux.

**Comment by rahulporuri** [comment]
Going back to the original issue, I am reasonably sure that the lack of the `.egg-info` directory is what is causing the `mayavi` import error. I am not sure how to fix this issue.

Can you try manually creating the `.egg-info` directory and adding a `PKG-INFO` file. For example, the `PKG-INFO` file in my local `vtk` installation in an edm environment has the following -
 
```
Metadata-Version: 1.1
Name: VTK
Version: 8.1.2
Summary: 3-D computer graphics, image processing, and visualization
Home-page: 
Author: 
Author-email: 
License: BSD
Download-URL: http://www.vtk.org/
Description: The Visualization Toolkit (VTK) is an open source, freely
        available software system for 3D computer graphics, modeling,
        image processing, volume rendering, scientific visualization and
        information visualization.
Platform: UNKNOWN
```

**Comment by yurivict** [comment]
Yes, adding this directory and file helps, thanks!

**Comment by rahulporuri** [comment]
@yurivict I updated the issue title and added a link to the temporary workaround in the issue description. And this seems to be a vtk issue - which mayavi cannot fix. Because of that, I am going to close this issue. Is that okay with you?

Please keep us posted on your efforts to create the FreeBSD port of mayavi.

**Comment by yurivict** [comment]
Ok, thanks!
