### ISSUE TITLE
Can't enable python view in Mayavi2

### ISSUE THREAD

**Issue by Sivapriyasr** [enthought/mayavi#1008]
I installed mayavi 4.7.2 , vtk 9, python 3.6, pyqt5. The mayavi aplication is opening but when i enable python view in the others option of the View menu, the mayavi application crashes. And the logger says:
WARNING|2021-01-25 16:12:24,255|Can't find the Python shell to bind variables
WARNING|2021-01-25 16:12:24,255|'PythonShellView' object has no attribute 'shell'

**Comment by yjx12345** [comment]
I got the same problem,have you solved the problem?Could you please share the way to conquer it?

**Comment by yjx12345** [comment]
help!!!

**Comment by yjx12345** [comment]
![image](https://user-images.githubusercontent.com/63141475/145715591-20c2c267-b8bb-4ab1-8b49-ad1070e824ad.png)

**Comment by yjx12345** [comment]
![image](https://user-images.githubusercontent.com/63141475/145715627-87b36bec-3569-40c0-8459-ded73b3889e3.png)

**Comment by rahulporuri** [comment]
@yjx12345 can you give us information about your python environment so we can debug what is happening? For example, what version of python are you using, what version of mayavi and vtk are you using, which GUI toolkit are you using (Qt or Wx) and what toolkit wrapper are you using (pyqt5, pyside5, wxpython etc) and what is the version.

You should be able to run `python -m pip list` or `python -m pip freeze` and get this information. You can simply copy-paste the output of that command in this discussion.

**Comment by CCMCAGP** [comment]
Hi, I've run into the same issue! Here are the versions:

Package                            Version
---------------------------------- --------------------
aiohttp                            3.8.1
aiosignal                          1.2.0
alabaster                          0.7.12
anaconda-clean                     1.0
anaconda-client                    1.9.0
anaconda-navigator                 2.1.4
anaconda-project                   0.10.2
anyio                              3.5.0
appdirs                            1.4.4
apptools                           5.1.0
argh                               0.26.2
argon2-cffi                        21.3.0
argon2-cffi-bindings               21.2.0
arrow                              1.2.2
asn1crypto                         1.4.0
astroid                            2.5
astropy                            5.0.3
asttokens                          2.0.5
async-generator                    1.10
async-timeout                      4.0.2
atomicwrites                       1.4.0
attrs                              21.4.0
autopep8                           1.5.6
Babel                              2.9.1
backcall                           0.2.0
backports.functools-lru-cache      1.6.4
backports.shutil-get-terminal-size 1.0.0
backports.tempfile                 1.0
backports.weakref                  1.0.post1
bcrypt                             3.2.0
beautifulsoup4                     4.10.0
binaryornot                        0.4.4
bitarray                           2.4.1
bkcharts                           0.2
black                              19.10b0
bleach                             4.1.0
bokeh                              2.4.2
boto                               2.49.0
Bottleneck                         1.3.4
brotlipy                           0.7.0
certifi                            2021.10.8
cffi                               1.15.0
chardet                            4.0.0
charset-normalizer                 2.0.12
click                              8.0.4
cloudpickle                        2.0.0
clyent                             1.2.2
colorama                           0.4.4
comtypes                           1.1.10
conda                              4.12.0
conda-build                        3.21.4
conda-content-trust                0+unknown
conda-pack                         0.6.0
conda-package-handling             1.8.1
conda-repo-cli                     1.0.4
conda-token                        0.3.0
conda-verify                       3.4.2
configobj                          5.0.6
contextlib2                        0.6.0.post1
cookiecutter                       1.7.3
cryptography                       3.4.8
cycler                             0.11.0
Cython                             0.29.28
cytoolz                            0.11.0
daal4py                            2021.5.0
dask                               2022.2.1
debugpy                            1.5.1
decorator                          5.1.1
defusedxml                         0.7.1
diff-match-patch                   20200713
distributed                        2022.2.1
docutils                           0.17.1
entrypoints                        0.3
envisage                           6.0.1
et-xmlfile                         1.1.0
executing                          0.8.3
fastcache                          1.1.0
fastjsonschema                     2.15.1
filelock                           3.6.0
flake8                             3.9.2
Flask                              1.1.2
fonttools                          4.25.0
frozenlist                         1.3.0
fsspec                             2022.2.0
future                             0.18.2
gevent                             21.8.0
glob2                              0.7
gmpy2                              2.1.2
greenlet                           1.1.1
h5py                               2.10.0
HeapDict                           1.0.1
html5lib                           1.1
idna                               3.3
imagecodecs                        2021.8.26
imageio                            2.9.0
imagesize                          1.3.0
importlib-metadata                 4.11.3
importlib-resources                5.7.1
inflection                         0.5.1
iniconfig                          1.1.1
intervaltree                       3.1.0
ipykernel                          6.9.1
ipython                            8.2.0
ipython-genutils                   0.2.0
ipywidgets                         7.6.5
isort                              5.9.3
itsdangerous                       2.0.1
jdcal                              1.4.1
jedi                               0.17.2
Jinja2                             2.11.3
jinja2-time                        0.2.0
joblib                             1.1.0
json5                              0.9.6
jsonschema                         3.2.0
jupyter                            1.0.0
jupyter-client                     6.1.12
jupyter-console                    6.4.0
jupyter-core                       4.9.2
jupyter-packaging                  0.7.12
jupyter-server                     1.13.5
jupyterlab                         3.3.2
jupyterlab-pygments                0.1.2
jupyterlab-server                  2.10.3
jupyterlab-widgets                 1.0.0
keyring                            23.4.0
kiwisolver                         1.3.2
lazy-object-proxy                  1.6.0
libarchive-c                       2.9
llvmlite                           0.36.0
locket                             0.2.1
lxml                               4.8.0
MarkupSafe                         2.0.1
matplotlib                         3.5.1
matplotlib-inline                  0.1.2
mayavi                             4.7.4
mccabe                             0.6.1
menuinst                           1.4.16
mistune                            0.8.4
mkl-fft                            1.3.1
mkl-random                         1.2.2
mkl-service                        2.4.0
mock                               4.0.3
more-itertools                     8.12.0
mpmath                             1.2.1
msgpack                            1.0.2
multidict                          6.0.2
multipledispatch                   0.6.0
munkres                            1.1.4
mypy-extensions                    0.4.3
navigator-updater                  0.2.1
nbclassic                          0.3.5
nbclient                           0.5.11
nbconvert                          6.4.4
nbformat                           5.3.0
nest-asyncio                       1.5.5
networkx                           2.7.1
nltk                               3.7
nose                               1.3.7
notebook                           6.4.8
numba                              0.53.0
numexpr                            2.8.1
numpy                              1.21.5
numpydoc                           1.2
olefile                            0.46
opencv-contrib-python              4.5.2.54
openpyxl                           3.0.9
packaging                          21.3
pandas                             1.4.1
pandocfilters                      1.5.0
paramiko                           2.7.2
parso                              0.7.0
partd                              1.2.0
path                               16.2.0
pathlib2                           2.3.6
pathspec                           0.7.0
pathtools                          0.1.2
patsy                              0.5.2
pep8                               1.7.1
pexpect                            4.8.0
pickleshare                        0.7.5
Pillow                             9.0.1
pip                                22.0.4
pkginfo                            1.8.2
platformdirs                       2.4.0
pluggy                             1.0.0
ply                                3.11
poyo                               0.5.0
prometheus-client                  0.13.1
prompt-toolkit                     3.0.20
psutil                             5.8.0
ptyprocess                         0.7.0
pure-eval                          0.2.2
py                                 1.11.0
pycodestyle                        2.7.0
pycosat                            0.6.3
pycparser                          2.21
pycurl                             7.44.1
pydocstyle                         6.1.1
pyerfa                             2.0.0
pyface                             7.4.1
pyflakes                           2.3.1
Pygments                           2.11.2
PyJWT                              2.1.0
pylint                             2.7.4
pyls-spyder                        0.4.0
PyNaCl                             1.4.0
pyodbc                             4.0.32
pyOpenSSL                          21.0.0
pyparsing                          3.0.4
PyQt5                              5.15.6
PyQt5-Qt5                          5.15.2
PyQt5-sip                          12.10.1
PyQtWebEngine                      5.15.5
PyQtWebEngine-Qt5                  5.15.2
pyreadline                         2.1
pyrsistent                         0.18.0
PySocks                            1.7.1
pytest                             7.1.1
python-dateutil                    2.8.2
python-jsonrpc-server              0.4.0
python-lsp-black                   1.0.0
python-lsp-jsonrpc                 1.0.0
python-lsp-server                  1.2.4
python-slugify                     5.0.2
pytz                               2021.3
PyWavelets                         1.3.0
pywin32                            302
pywin32-ctypes                     0.2.0
pywinpty                           2.0.2
PyYAML                             6.0
pyzmq                              22.3.0
QDarkStyle                         3.0.2
qstylizer                          0.1.10
QtAwesome                          1.0.3
qtconsole                          5.3.0
QtPy                               2.0.1
regex                              2022.3.15
requests                           2.27.1
rope                               0.22.0
Rtree                              0.9.7
ruamel-yaml-conda                  0.15.100
scikit-image                       0.19.2
scikit-learn                       1.0.2
scikit-learn-intelex               2021.20220215.153006
scipy                              1.7.3
seaborn                            0.11.2
Send2Trash                         1.8.0
setuptools                         61.2.0
simplegeneric                      0.8.1
singledispatch                     3.7.0
sip                                4.19.13
six                                1.16.0
sniffio                            1.2.0
snowballstemmer                    2.2.0
sortedcollections                  2.1.0
sortedcontainers                   2.4.0
soupsieve                          2.3.1
Sphinx                             4.4.0
sphinxcontrib-applehelp            1.0.2
sphinxcontrib-devhelp              1.0.2
sphinxcontrib-htmlhelp             2.0.0
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-qthelp               1.0.3
sphinxcontrib-serializinghtml      1.1.5
sphinxcontrib-websupport           1.2.4
spyder                             5.1.5
spyder-kernels                     2.1.3
SQLAlchemy                         1.4.32
stack-data                         0.2.0
statsmodels                        0.13.2
sympy                              1.10.1
tables                             3.6.1
TBB                                0.2
tblib                              1.7.0
terminado                          0.13.1
testpath                           0.5.0
text-unidecode                     1.3
textdistance                       4.2.1
threadpoolctl                      2.2.0
three-merge                        0.1.1
tifffile                           2021.7.2
tinycss                            0.4
toml                               0.10.2
tomli                              1.2.2
toolz                              0.11.2
tornado                            6.1
tqdm                               4.63.0
traitlets                          5.1.1
traits                             6.3.2
traitsui                           7.3.1
typed-ast                          1.4.3
typing_extensions                  4.1.1
ujson                              5.1.0
unicodecsv                         0.14.1
Unidecode                          1.2.0
urllib3                            1.26.8
vtk                                9.1.0
watchdog                           1.0.2
wcwidth                            0.2.5
webencodings                       0.5.1
websocket-client                   0.58.0
Werkzeug                           2.0.3
wheel                              0.37.1
whichcraft                         0.6.1
widgetsnbextension                 3.5.2
win-inet-pton                      1.1.0
win-unicode-console                0.5
wincertstore                       0.2
wrapt                              1.13.3
wslink                             1.5.3
xlrd                               2.0.1
XlsxWriter                         3.0.3
xlwings                            0.24.9
xlwt                               1.3.0
xmltodict                          0.12.0
yapf                               0.31.0
yarl                               1.7.2
zict                               2.0.0
zipp                               3.7.0
zope.event                         4.5.0
zope.interface                     5.4.0

**Comment by CCMCAGP** [comment]
Here's the complete log of what happened: 

WARNING|2022-04-19 10:28:22,027|Can't find the Python shell to bind variables
WARNING|2022-04-19 10:28:22,027|'PythonShellView' object has no attribute 'shell'
ERROR|2022-04-19 10:28:21,842|Exception occurred in traits notification handler for object: <envisage.ui.workbench.workbench_window.WorkbenchWindow object at 0x0000029BDDBAE950>, trait: active_perspective, old value: None, new value: Perspective(Mayavi)
Traceback (most recent call last):
  File "C:\Users\ccmcagp\Anaconda3\lib\site-packages\pyface\ui\qt4\workbench\workbench_window_layout.py", line 106, in add_view
    self._qt4_add_view(view, position, relative_to, size)
  File "C:\Users\ccmcagp\Anaconda3\lib\site-packages\pyface\ui\qt4\workbench\workbench_window_layout.py", line 470, in _qt4_add_view
    dw = self._qt4_create_view_dock_widget(view, size)
  File "C:\Users\ccmcagp\Anaconda3\lib\site-packages\pyface\ui\qt4\workbench\workbench_window_layout.py", line 542, in _qt4_create_view_dock_widget
    view.control = view.create_control(dw.widget())
  File "C:\Users\ccmcagp\Anaconda3\lib\site-packages\envisage\plugins\python_shell\view\python_shell_view.py", line 109, in create_control
    self.shell = shell = PythonShell(parent)
  File "C:\Users\ccmcagp\Anaconda3\lib\site-packages\pyface\ui\qt4\python_shell.py", line 68, in __init__
    self.create()
  File "C:\Users\ccmcagp\Anaconda3\lib\site-packages\pyface\i_widget.py", line 128, in create
    self._create()
  File "C:\Users\ccmcagp\Anaconda3\lib\site-packages\pyface\i_widget.py", line 150, in _create
    self.control = self._create_control(self.parent)
  File "C:\Users\ccmcagp\Anaconda3\lib\site-packages\pyface\ui\qt4\python_shell.py", line 120, in _create_control
    return PyfacePythonWidget(self, parent)
  File "C:\Users\ccmcagp\Anaconda3\lib\site-packages\pyface\ui\qt4\python_shell.py", line 594, in __init__
    super().__init__(*args, **kw)
  File "C:\Users\ccmcagp\Anaconda3\lib\site-packages\pyface\ui\qt4\python_shell.py", line 183, in __init__
    super().__init__(parent)
  File "C:\Users\ccmcagp\Anaconda3\lib\site-packages\pyface\ui\qt4\console\history_console_widget.py", line 28, in __init__
    super().__init__(*args, **kw)
  File "C:\Users\ccmcagp\Anaconda3\lib\site-packages\pyface\ui\qt4\console\console_widget.py", line 189, in __init__
    self.reset_font()
  File "C:\Users\ccmcagp\Anaconda3\lib\site-packages\pyface\ui\qt4\console\console_widget.py", line 843, in reset_font
    self._set_font(font)
  File "C:\Users\ccmcagp\Anaconda3\lib\site-packages\pyface\ui\qt4\console\console_widget.py", line 564, in _set_font
    self._control.setTabStopDistance(self.tab_width * width)
AttributeError: 'QPlainTextEdit' object has no attribute 'setTabStopDistance'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ccmcagp\Anaconda3\lib\site-packages\traits\trait_notifiers.py", line 342, in __call__
    self.handler(*args)
  File "C:\Users\ccmcagp\Anaconda3\lib\site-packages\pyface\workbench\workbench_window.py", line 808, in _active_perspective_changed
    self._show_perspective(old, new)
  File "C:\Users\ccmcagp\Anaconda3\lib\site-packages\pyface\workbench\workbench_window.py", line 756, in _show_perspective
    new.create(self)
  File "C:\Users\ccmcagp\Anaconda3\lib\site-packages\pyface\workbench\perspective.py", line 97, in create
    self._add_contents(window, self.contents)
  File "C:\Users\ccmcagp\Anaconda3\lib\site-packages\pyface\workbench\perspective.py", line 134, in _add_contents
    self._add_perspective_item(window, item)
  File "C:\Users\ccmcagp\Anaconda3\lib\site-packages\pyface\workbench\perspective.py", line 155, in _add_perspective_item
    window.add_view(
  File "C:\Users\ccmcagp\Anaconda3\lib\site-packages\pyface\workbench\workbench_window.py", line 297, in add_view
    self.layout.add_view(view, position, relative_to, size)
  File "C:\Users\ccmcagp\Anaconda3\lib\site-packages\pyface\ui\qt4\workbench\workbench_window_layout.py", line 115, in add_view
    view.destroy_control()
  File "C:\Users\ccmcagp\Anaconda3\lib\site-packages\envisage\plugins\python_shell\view\python_shell_view.py", line 149, in destroy_control
    self.window.application.unregister_service(self._service_id)
AttributeError: 'PythonShellView' object has no attribute '_service_id'
ERROR|2022-04-19 10:28:21,823|error creating view control [envisage.plugins.python_shell_view]
Traceback (most recent call last):
  File "C:\Users\ccmcagp\Anaconda3\lib\site-packages\pyface\ui\qt4\workbench\workbench_window_layout.py", line 106, in add_view
    self._qt4_add_view(view, position, relative_to, size)
  File "C:\Users\ccmcagp\Anaconda3\lib\site-packages\pyface\ui\qt4\workbench\workbench_window_layout.py", line 470, in _qt4_add_view
    dw = self._qt4_create_view_dock_widget(view, size)
  File "C:\Users\ccmcagp\Anaconda3\lib\site-packages\pyface\ui\qt4\workbench\workbench_window_layout.py", line 542, in _qt4_create_view_dock_widget
    view.control = view.create_control(dw.widget())
  File "C:\Users\ccmcagp\Anaconda3\lib\site-packages\envisage\plugins\python_shell\view\python_shell_view.py", line 109, in create_control
    self.shell = shell = PythonShell(parent)
  File "C:\Users\ccmcagp\Anaconda3\lib\site-packages\pyface\ui\qt4\python_shell.py", line 68, in __init__
    self.create()
  File "C:\Users\ccmcagp\Anaconda3\lib\site-packages\pyface\i_widget.py", line 128, in create
    self._create()
  File "C:\Users\ccmcagp\Anaconda3\lib\site-packages\pyface\i_widget.py", line 150, in _create
    self.control = self._create_control(self.parent)
  File "C:\Users\ccmcagp\Anaconda3\lib\site-packages\pyface\ui\qt4\python_shell.py", line 120, in _create_control
    return PyfacePythonWidget(self, parent)
  File "C:\Users\ccmcagp\Anaconda3\lib\site-packages\pyface\ui\qt4\python_shell.py", line 594, in __init__
    super().__init__(*args, **kw)
  File "C:\Users\ccmcagp\Anaconda3\lib\site-packages\pyface\ui\qt4\python_shell.py", line 183, in __init__
    super().__init__(parent)
  File "C:\Users\ccmcagp\Anaconda3\lib\site-packages\pyface\ui\qt4\console\history_console_widget.py", line 28, in __init__
    super().__init__(*args, **kw)
  File "C:\Users\ccmcagp\Anaconda3\lib\site-packages\pyface\ui\qt4\console\console_widget.py", line 189, in __init__
    self.reset_font()
  File "C:\Users\ccmcagp\Anaconda3\lib\site-packages\pyface\ui\qt4\console\console_widget.py", line 843, in reset_font
    self._set_font(font)
  File "C:\Users\ccmcagp\Anaconda3\lib\site-packages\pyface\ui\qt4\console\console_widget.py", line 564, in _set_font
    self._control.setTabStopDistance(self.tab_width * width)
AttributeError: 'QPlainTextEdit' object has no attribute 'setTabStopDistance'

**Comment by stigersh** [comment]
Hello I would appreciate your help a lot
I have a similar issue..
I'm trying to use Mayavi2 in vscode jupyter notebooks and no plots are shown. This error is written instead. I work on Mac
my environment has:
PyQt5                         5.12.3
PyQt5-Qt5                     5.15.2
PyQt5-sip                     12.11.0
vtk                           9.0.3
mayavi                        4.8.1.dev0

I think I have an installation problem.  Running the app in the terminal gets totally stuck
if I test with "nosetests tests" I get

qt.qpa.window: <QNSWindow: 0x7fae7964c7e0; contentView=<QNSView: 0x7fae7964c3d0; QCocoaWindow(0x7fae79648d40, window=QWidgetWindow(0x7fae779bae10, name="QWidgetClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
......S.......................................................................2022-10-15 19:40:58.379 (   9.080s) [          2768A7]vtkGenericDataArray.txx:575    ERR| vtkDoubleArray (0x7fae62330a60): Source array too small, requested tuple at index 10, but there are only 10 tuples in the array.
2022-10-15 19:40:58.380 (   9.080s) [          2768A7]vtkGenericDataArray.txx:575    ERR| vtkDoubleArray (0x7fae62330a60): Source array too small, requested tuple at index 11, but there are only 10 tuples in the array.
2022-10-15 19:40:58.380 (   9.080s) [          2768A7]vtkGenericDataArray.txx:575    ERR| vtkDoubleArray (0x7fae62330a60): Source array too small, requested tuple at index 12, but there are only 10 tuples in the array.
2022-10-15 19:40:58.380 (   9.080s) [          2768A7]vtkGenericDataArray.txx:575    ERR| vtkDoubleArray (0x7fae62330a60): Source array too small, requested tuple at index 13, but there are only 10 tuples in the array.
2022-10-15 19:40:58.380 (   9.080s) [          2768A7]vtkGenericDataArray.txx:575    ERR| vtkDoubleArray (0x7fae62330a60): Source array too small, requested tuple at index 14, but there are only 10 tuples in the array.
2022-10-15 19:40:58.380 (   9.080s) [          2768A7]vtkGenericDataArray.txx:575    ERR| vtkDoubleArray (0x7fae62330a60): Source array too small, requested tuple at index 15, but there are only 10 tuples in the array.

Thanks a lot for your time!
