### ISSUE TITLE
[regression in 4.8.2] TVTK not built properly.

### ISSUE THREAD

**Issue by yurivict** [enthought/mayavi#1302]
Many examples, ex. examples/mayavi/mlab/wigner.py, fail:
```
$ python3.9 ./work-py39/mayavi-4.8.2/examples/mayavi/mlab/wigner.py 
Traceback (most recent call last):
  File "/usr/ports/graphics/py-mayavi/./work-py39/mayavi-4.8.2/examples/mayavi/mlab/wigner.py", line 25, in <module>
    from mayavi import mlab
  File "/usr/local/lib/python3.9/site-packages/mayavi/mlab.py", line 16, in <module>
    from mayavi.tools.camera import view, roll, yaw, pitch, move
  File "/usr/local/lib/python3.9/site-packages/mayavi/tools/camera.py", line 24, in <module>
    from .engine_manager import get_engine
  File "/usr/local/lib/python3.9/site-packages/mayavi/tools/engine_manager.py", line 14, in <module>
    from mayavi.core.registry import registry
  File "/usr/local/lib/python3.9/site-packages/mayavi/core/registry.py", line 16, in <module>
    from mayavi.core.metadata import Metadata, import_symbol
  File "/usr/local/lib/python3.9/site-packages/mayavi/core/metadata.py", line 11, in <module>
    from mayavi.core.pipeline_info import PipelineInfo
  File "/usr/local/lib/python3.9/site-packages/mayavi/core/pipeline_info.py", line 12, in <module>
    from .utils import get_tvtk_dataset_name
  File "/usr/local/lib/python3.9/site-packages/mayavi/core/utils.py", line 6, in <module>
    from tvtk.api import tvtk
  File "/usr/local/lib/python3.9/site-packages/tvtk/api.py", line 10, in <module>
    from tvtk.tvtk_access import tvtk
  File "/usr/local/lib/python3.9/site-packages/tvtk/tvtk_access.py", line 27, in <module>
    raise ImportError("TVTK not built properly. "
ImportError: TVTK not built properly. Unable to find either a directory: /usr/local/lib/python3.9/site-packages/tvtk/tvtk_classes or a file: /usr/local/lib/python3.9/site-packages/tvtk/tvtk_classes.zip with the TVTK classes.
```

The immediate reason is that /usr/local/lib/python3.9/site-packages/tvtk/tvtk_classes.zip isn't installed.

4.8.1 didn't have such problem.

Python-3.9
FreeBSD 14.0

**Comment by prabhuramachandran** [comment]
Am not sure how you installed things. I just tested the following:
```bash
$ conda create -n junk python numpy
$ conda activate junk
$ pip install mayavi pyqt5
```
And things worked fine.

**Comment by yurivict** [comment]
We use setup.py to install Mayavi.

**Comment by yurivict** [comment]
The "code_gen.py" exacutble script is supposed to generate the tvtk_classes.zip file, but it isn't called anywhere in the project.

Do you know where is it supposed to be called?
