### ISSUE TITLE
wxPython not supported

### ISSUE THREAD

**Issue by jmoraleda** [enthought/mayavi#1309]
The website mentions support for wxPython. But none of the examples can be made to work.

The fundamental error when trying to add a mayavi control to a wxPython window appears to be:

```
    sizer.Add(self.control, 0, wx.ALL, 10)
TypeError: Sizer.Add(): arguments did not match any overloaded call:
  overload 1: argument 1 has unexpected type 'QWidget'
```

Searching in my email I notice I participated in a discussion about this as far back as 2020: https://github.com/enthought/mayavi/issues/726 but that issue appears to have been removed.

Is there any interest now in adding support for wxPython back? 

If there is interest in adding this support, I can potentially help. I am not familiar with the mayavi implementation, but I am a regularcontributor to wxPython, and I have contributed to the integration between matplotlib and wxPython. (e.g. https://github.com/matplotlib/matplotlib/pull/26710)

**Comment by larsoner** [comment]
The wx examples now work (https://github.com/enthought/mayavi/pull/1389), can you check again?

**Comment by jmoraleda** [comment]
Thank you. This is still not working from me:
```
(mayavi_wx_test) jorge@indus:/tmp$ python wx_mayavi_embed_in_notebook.py 

(python:2879691): Gtk-WARNING **: 16:18:36.429: gtk_disable_setlocale() must be called before gtk_init()
Traceback (most recent call last):
  File "/tmp/wx_mayavi_embed_in_notebook.py", line 80, in <module>
    frame = MainWindow(None, wx.ID_ANY)
  File "/tmp/wx_mayavi_embed_in_notebook.py", line 62, in __init__
    self.notebook.AddPage(page=self.control, caption='Display 1')
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AuiNotebook.AddPage(): arguments did not match any overloaded call:
  overload 1: argument 'page' has unexpected type 'QWidget'
  overload 2: argument 'page' has unexpected type 'QWidget'
```

**Comment by larsoner** [comment]
Do you have both wx and a Qt binding installed? Does setting `ETS_TOOLKIT=wx` before running fix it?

**Comment by jmoraleda** [comment]
Thank you. Tested in a fresh venv with both `wxPython` (4.3.1) and a Qt binding (PyQt5 + PySide6) installed, since that's what I have. Two separate things going on here:

**1. Toolkit auto-detection** — with a Qt binding also installed, ETS defaults to Qt, so the wx examples try to embed a `QWidget` in a wx container and blow up with the original error. `ETS_TOOLKIT=wx` fixes that, as you suspected.

**2. A real bug in the example itself**, which only surfaces once the toolkit is actually wx. With `ETS_TOOLKIT=wx` set, `wx_mayavi_embed_in_notebook.py` still fails, but with a different, legitimate error:

```
wx._core.wxAssertionError: C++ assertion "page->GetParent() == this" failed at .../auibook.cpp(2335) in InsertPage(): page must be a child of the notebook
```

Cause: [`examples/mayavi/interactive/wx_mayavi_embed_in_notebook.py`](https://github.com/enthought/mayavi/blob/main/examples/mayavi/interactive/wx_mayavi_embed_in_notebook.py) lines 60 and 68 call

```python
self.control = self.mayavi_view.edit_traits(
                parent=self,
                kind='subpanel').control
```

passing `parent=self` (the `wx.Frame`) instead of `parent=self.notebook`. Under Qt this is harmless because a widget gets silently reparented when added to a layout, but wx's `AuiNotebook.AddPage` requires the page to already be a child of the notebook, so it raises.

Fix is to parent the controls to the notebook instead of the frame:

```python
self.control = self.mayavi_view.edit_traits(
                parent=self.notebook,
                kind='subpanel').control
...
self.control2 = self.mayavi_view2.edit_traits(
                parent=self.notebook,
                kind='subpanel').control
```

With both `ETS_TOOLKIT=wx` and the parenting fix in `wx_mayavi_embed_in_notebook.py`, the example runs cleanly for me — window opens with both tabs, no crash, and the 3D object is displayed. The other example `wx_embedding.py` also runs and the 3D object is displayed.

**Comment by larsoner** [comment]
Good call, I'll add to #1410
