### ISSUE TITLE
mayavi 4.0.0 fails to run tests in linux x86

### ISSUE THREAD

**Issue by pmav99** [enthought/mayavi#14]
I am on Arch Linux x86. 

I installed using this [AUR package](http://aur.archlinux.org/packages.php?ID=46179) which essentially  downloads the tarball from github and runs setup.py

I try to run the test suite but I get this error:

```python
----------------------------------------------------------------------
Running TVTK tests.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mayavi/tests/runtests.py", line 225, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/mayavi/tests/runtests.py", line 217, in main
    status = m2_tests(verbose)
  File "/usr/lib/python2.7/site-packages/mayavi/tests/runtests.py", line 170, in m2_tests
    tests = find_tests(['tvtk'])
  File "/usr/lib/python2.7/site-packages/mayavi/tests/runtests.py", line 63, in find_tests
    mod = __import__(modname, globals(), locals(), [symbol])
ValueError: Empty module name
```

**Comment by stefanoborini** [comment]
Still relevant? I can't seem to reproduce the problem anymore. Closing.
