### ISSUE TITLE
QT/wx embedding broken? (traits.trait_errors.TraitError: The 'name' trait of a SceneEditor instance must be a unicode string, ...)

### ISSUE THREAD

**Issue by jamasi** [enthought/mayavi#161]
So I upgraded to mayavi 4.4.0 (and vtk-6.1.0) on a sabayon linux machine and now my [visualisation widget](https://github.com/jamasi/Xtal-xplore-R/blob/master/gui/mayaviqwidget.py) (PyQt4) gives me this traceback:

```
  File "/home/jan/Arbeit/Xtal-xplore-R/gui/mayaviqwidget.py", line 376, in __init__
    self.ui = self.visualization.edit_traits(parent=self, kind='subpanel').control
  File "/usr/lib64/python2.7/site-packages/traits/has_traits.py", line 1859, in edit_traits
    handler, id, scrollable, args )
  File "/usr/lib64/python2.7/site-packages/traitsui/view.py", line 433, in ui
    ui.ui( parent, kind )
  File "/usr/lib64/python2.7/site-packages/traitsui/ui.py", line 221, in ui
    self.rebuild( self, parent )
  File "/usr/lib64/python2.7/site-packages/traitsui/qt4/toolkit.py", line 140, in ui_subpanel
    ui_panel.ui_subpanel( ui, parent )
  File "/usr/lib64/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 79, in ui_subpanel
    _ui_panel_for(ui, parent, True)
  File "/usr/lib64/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 85, in _ui_panel_for
    ui.control = control = _Panel(ui, parent, is_subpanel).control
  File "/usr/lib64/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 143, in __init__
    self.control = panel(ui)
  File "/usr/lib64/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 231, in panel
    panel = _GroupPanel(content[0], ui).control
  File "/usr/lib64/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 572, in __init__
    layout = self._add_items(content, inner)
  File "/usr/lib64/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 832, in _add_items
    ui, object, name, item.tooltip, None
  File "/usr/lib64/python2.7/site-packages/traitsui/editor_factory.py", line 140, in simple_editor
    description = description )
  File "/usr/lib64/python2.7/site-packages/traitsui/editor.py", line 133, in __init__
    self.old_value = getattr( self.object, self.name )
  File "/usr/lib64/python2.7/site-packages/traits/trait_types.py", line 2801, in create_default_value
    return klass( *args[1:], **kw )
  File "/usr/lib64/python2.7/site-packages/mayavi/tools/mlab_scene_model.py", line 36, in __init__
    self.engine.new_scene(self)
  File "/usr/lib64/python2.7/site-packages/apptools/scripting/recordable.py", line 45, in _wrapper                                             
    result = func(*args, **kw)                                                                                                                 
  File "/usr/lib64/python2.7/site-packages/mayavi/plugins/envisage_engine.py", line 88, in new_scene                                           
    editor.name = name                                                                                                                         
  File "/usr/lib64/python2.7/site-packages/traits/trait_handlers.py", line 172, in error                                                       
    value )                                                                                                                                    
traits.trait_errors.TraitError: The 'name' trait of a SceneEditor instance must be a unicode string, but a value of <mayavi.tools.mlab_scene_model.MlabSceneModel object at 0x7eff5017abf0> <class 'mayavi.tools.mlab_scene_model.MlabSceneModel'> was specified.
```
with the previous version it was working like expected. Has the API been changed or is this a regression?

**Comment by jamasi** [comment]
The same error also occurs with the example code:

```
$ python2.7 qt_embedding.py 
Traceback (most recent call last):
  File "qt_embedding.py", line 95, in <module>
    mayavi_widget = MayaviQWidget(container)
  File "qt_embedding.py", line 70, in __init__
    kind='subpanel').control
  File "/usr/lib64/python2.7/site-packages/traits/has_traits.py", line 1859, in edit_traits
    handler, id, scrollable, args )
  File "/usr/lib64/python2.7/site-packages/traitsui/view.py", line 433, in ui
    ui.ui( parent, kind )
  File "/usr/lib64/python2.7/site-packages/traitsui/ui.py", line 221, in ui
    self.rebuild( self, parent )
  File "/usr/lib64/python2.7/site-packages/traitsui/qt4/toolkit.py", line 140, in ui_subpanel
    ui_panel.ui_subpanel( ui, parent )
  File "/usr/lib64/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 79, in ui_subpanel
    _ui_panel_for(ui, parent, True)
  File "/usr/lib64/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 85, in _ui_panel_for
    ui.control = control = _Panel(ui, parent, is_subpanel).control
  File "/usr/lib64/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 143, in __init__
    self.control = panel(ui)
  File "/usr/lib64/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 231, in panel
    panel = _GroupPanel(content[0], ui).control
  File "/usr/lib64/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 572, in __init__
    layout = self._add_items(content, inner)
  File "/usr/lib64/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 832, in _add_items
    ui, object, name, item.tooltip, None
  File "/usr/lib64/python2.7/site-packages/traitsui/editor_factory.py", line 140, in simple_editor
    description = description )
  File "/usr/lib64/python2.7/site-packages/traitsui/editor.py", line 133, in __init__
    self.old_value = getattr( self.object, self.name )
  File "/usr/lib64/python2.7/site-packages/traits/trait_types.py", line 2801, in create_default_value
    return klass( *args[1:], **kw )
  File "/usr/lib64/python2.7/site-packages/mayavi/tools/mlab_scene_model.py", line 36, in __init__
    self.engine.new_scene(self)
  File "/usr/lib64/python2.7/site-packages/apptools/scripting/recordable.py", line 45, in _wrapper
    result = func(*args, **kw)
  File "/usr/lib64/python2.7/site-packages/mayavi/plugins/envisage_engine.py", line 88, in new_scene
    editor.name = name
  File "/usr/lib64/python2.7/site-packages/traits/trait_handlers.py", line 172, in error
    value )
traits.trait_errors.TraitError: The 'name' trait of a SceneEditor instance must be a unicode string, but a value of <mayavi.tools.mlab_scene_model.MlabSceneModel object at 0x7fe54c4c5d70> <class 'mayavi.tools.mlab_scene_model.MlabSceneModel'> was specified.

$ mayavi2 --version
Mayavi 4.4.0

vtk is version 6.1.0
```

**Comment by jamasi** [comment]
The wx example from the documentation does not work as well:

```
python2.7 wx_embedding.py 
Traceback (most recent call last):
  File "wx_embedding.py", line 64, in <module>
    frame = MainWindow(None, wx.ID_ANY)
  File "wx_embedding.py", line 55, in __init__
    self.mayavi_view = MayaviView()
  File "wx_embedding.py", line 44, in __init__
    self.scene.engine.add_source(src)
  File "/usr/lib64/python2.7/site-packages/traits/trait_types.py", line 2801, in create_default_value
    return klass( *args[1:], **kw )
  File "/usr/lib64/python2.7/site-packages/mayavi/tools/mlab_scene_model.py", line 36, in __init__
    self.engine.new_scene(self)
  File "/usr/lib64/python2.7/site-packages/apptools/scripting/recordable.py", line 45, in _wrapper
    result = func(*args, **kw)
  File "/usr/lib64/python2.7/site-packages/mayavi/plugins/envisage_engine.py", line 88, in new_scene
    editor.name = name
  File "/usr/lib64/python2.7/site-packages/traits/trait_handlers.py", line 172, in error
    value )
traits.trait_errors.TraitError: The 'name' trait of a SceneEditor instance must be a unicode string, but a value of <mayavi.tools.mlab_scene_model.MlabSceneModel object at 0x7faca887fe30> <class 'mayavi.tools.mlab_scene_model.MlabSceneModel'> was specified.
```

**Comment by jamasi** [comment]
This error persists with mayavi 4.4.2 (using the qt_embedding exampl code from the documentation):

```
$ python qt_embedding.py                                        
Traceback (most recent call last):
  File "qt_embedding.py", line 95, in <module>
    mayavi_widget = MayaviQWidget(container)
  File "qt_embedding.py", line 70, in __init__
    kind='subpanel').control
  File "/usr/lib64/python2.7/site-packages/traits/has_traits.py", line 1859, in edit_traits
    handler, id, scrollable, args )
  File "/usr/lib64/python2.7/site-packages/traitsui/view.py", line 433, in ui
    ui.ui( parent, kind )
  File "/usr/lib64/python2.7/site-packages/traitsui/ui.py", line 221, in ui
    self.rebuild( self, parent )
  File "/usr/lib64/python2.7/site-packages/traitsui/qt4/toolkit.py", line 140, in ui_subpanel
    ui_panel.ui_subpanel( ui, parent )
  File "/usr/lib64/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 79, in ui_subpanel
    _ui_panel_for(ui, parent, True)
  File "/usr/lib64/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 85, in _ui_panel_for
    ui.control = control = _Panel(ui, parent, is_subpanel).control
  File "/usr/lib64/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 143, in __init__
    self.control = panel(ui)
  File "/usr/lib64/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 231, in panel
    panel = _GroupPanel(content[0], ui).control
  File "/usr/lib64/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 572, in __init__
    layout = self._add_items(content, inner)
  File "/usr/lib64/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 832, in _add_items
    ui, object, name, item.tooltip, None
  File "/usr/lib64/python2.7/site-packages/traitsui/editor_factory.py", line 140, in simple_editor
    description = description )
  File "/usr/lib64/python2.7/site-packages/traitsui/editor.py", line 133, in __init__
    self.old_value = getattr( self.object, self.name )
  File "/usr/lib64/python2.7/site-packages/traits/trait_types.py", line 2801, in create_default_value
    return klass( *args[1:], **kw )
  File "/usr/lib64/python2.7/site-packages/mayavi/tools/mlab_scene_model.py", line 36, in __init__
    self.engine.new_scene(self)
  File "/usr/lib64/python2.7/site-packages/apptools/scripting/recordable.py", line 45, in _wrapper
    result = func(*args, **kw)
  File "/usr/lib64/python2.7/site-packages/mayavi/plugins/envisage_engine.py", line 88, in new_scene
    editor.name = name
  File "/usr/lib64/python2.7/site-packages/traits/trait_handlers.py", line 172, in error
    value )
traits.trait_errors.TraitError: The 'name' trait of a SceneEditor instance must be a unicode string, but a value of <mayavi.tools.mlab_scene_model.MlabSceneModel object at 0x7fd77f5cddd0> <class 'mayavi.tools.mlab_scene_model.MlabSceneModel'> was specified.
```

I'm using VTK 6.1.0, traits 4.5.0 and traitsui 4.4.0 on a gentoo/sabayon 64bit linux.

Is there no fix for this?

**Comment by dmsurti** [comment]
Set `ETS_TOOLKIT=qt4`.

Then `python qt_embedding` example works fine.

**Comment by dmsurti** [comment]
Yet to investigate `wx` issue.

**Comment by jamasi** [comment]
Sadly setting the TOOLKIT does not work here:

```
$ ETS_TOOLKIT=qt4 python qt_embedding.py 
Traceback (most recent call last):
  File "qt_embedding.py", line 95, in <module>
    mayavi_widget = MayaviQWidget(container)
  File "qt_embedding.py", line 70, in __init__
    kind='subpanel').control
  File "/usr/lib64/python2.7/site-packages/traits/has_traits.py", line 1859, in edit_traits
    handler, id, scrollable, args )
  File "/usr/lib64/python2.7/site-packages/traitsui/view.py", line 433, in ui
    ui.ui( parent, kind )
  File "/usr/lib64/python2.7/site-packages/traitsui/ui.py", line 221, in ui
    self.rebuild( self, parent )
  File "/usr/lib64/python2.7/site-packages/traitsui/qt4/toolkit.py", line 140, in ui_subpanel
    ui_panel.ui_subpanel( ui, parent )
  File "/usr/lib64/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 79, in ui_subpanel
    _ui_panel_for(ui, parent, True)
  File "/usr/lib64/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 85, in _ui_panel_for
    ui.control = control = _Panel(ui, parent, is_subpanel).control
  File "/usr/lib64/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 143, in __init__
    self.control = panel(ui)
  File "/usr/lib64/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 231, in panel
    panel = _GroupPanel(content[0], ui).control
  File "/usr/lib64/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 572, in __init__
    layout = self._add_items(content, inner)
  File "/usr/lib64/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 832, in _add_items
    ui, object, name, item.tooltip, None
  File "/usr/lib64/python2.7/site-packages/traitsui/editor_factory.py", line 140, in simple_editor
    description = description )
  File "/usr/lib64/python2.7/site-packages/traitsui/editor.py", line 133, in __init__
    self.old_value = getattr( self.object, self.name )
  File "/usr/lib64/python2.7/site-packages/traits/trait_types.py", line 2801, in create_default_value
    return klass( *args[1:], **kw )
  File "/usr/lib64/python2.7/site-packages/mayavi/tools/mlab_scene_model.py", line 36, in __init__
    self.engine.new_scene(self)
  File "/usr/lib64/python2.7/site-packages/apptools/scripting/recordable.py", line 45, in _wrapper
    result = func(*args, **kw)
  File "/usr/lib64/python2.7/site-packages/mayavi/plugins/envisage_engine.py", line 88, in new_scene
    editor.name = name
  File "/usr/lib64/python2.7/site-packages/traits/trait_handlers.py", line 172, in error
    value )
traits.trait_errors.TraitError: The 'name' trait of a SceneEditor instance must be a unicode string, but a value of <mayavi.tools.mlab_scene_model.MlabSceneModel object at 0x7f026de86dd0> <class 'mayavi.tools.mlab_scene_model.MlabSceneModel'> was specified.
```

**Comment by dmsurti** [comment]
I will have to test this on Linux box. The turnaround time to respond may not be quick.

**Comment by stefanoborini** [comment]
Cannot reproduce on mayavi 4.4.4 on ubuntu, but I definitely see the problem here.
mlab_scene_model calls `new_scene` passing `self` as first argument, which is bound to `name`, so it is definitely there as a bug, and the fact that I can't reproduce it is irrelevant.
