### ISSUE TITLE
Errors in master

### ISSUE THREAD

**Issue by itziakos** [enthought/mayavi#224]
Due to merging multiple PRs at the same time some tests have passed through, sorry about that.

```python
======================================================================
ERROR: test_compare_mesh_datasets_equal (simphony.testing.tests.test_utils.TestCompareMeshDatasets)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "simphony/testing/tests/test_utils.py", line 123, in test_compare_mesh_datasets_equal
    mesh.add_point(point)
AttributeError: 'Mesh' object has no attribute 'add_point'
======================================================================
ERROR: test_compare_mesh_datasets_not_equal (simphony.testing.tests.test_utils.TestCompareMeshDatasets)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "simphony/testing/tests/test_utils.py", line 154, in test_compare_mesh_datasets_not_equal
    mesh.add_point(point)
AttributeError: 'Mesh' object has no attribute 'add_point'
----------------------------------------------------------------------
Ran 509 tests in 101.489s
```

**Comment by itziakos** [comment]
sorry wring repo
