### ISSUE TITLE
imshow ignores colormap kwarg in 4.4.3?

### ISSUE THREAD

**Issue by dbrakenhoff** [enthought/mayavi#262]
When using imshow in mayavi version 4.4.3, the colormap keyword argument is seemingly ignored. Following code produces an image with the default jet colormap despite providing the colormap argument. The code works fine in mayavi version 4.3.1.

    import mayavi.mlab as mlab
    import numpy as np

    a = np.random.random_integers(0, 10, (100, 100))
    
    mlab.imshow(a, colormap="cool")

    mlab.show()

Similarly, setting a different LUT after creating the image does not change anything, and going through the mayavi pipeline also does not change the colormap of the image. Mayavi issue? Or is something strange going on on my computer?

**Comment by stefanoborini** [comment]
Verified, investigating.

**Comment by stefanoborini** [comment]
I tried to verify its functionality on 4.3.1, but I can't reproduce it. I actually get an error.

```
Traceback (most recent call last):
  File "test2.py", line 6, in <module>
    mlab.imshow(a, colormap="cool")
  File "/Users/sborini/Work/github/mayavi/mayavi/tools/helper_functions.py", line 37, in the_function
    return pipeline(*args, **kwargs)
  File "/Users/sborini/Work/github/mayavi/mayavi/tools/helper_functions.py", line 77, in __call__
    scene = tools.gcf().scene
  File "/Users/sborini/Work/github/mayavi/mayavi/tools/figure.py", line 117, in gcf
    return figure(engine=engine)
  File "/Users/sborini/Work/github/mayavi/mayavi/tools/figure.py", line 69, in figure
    engine.new_scene(name=name, size=size)
  File "/Users/sborini/Work/github/apptools/apptools/scripting/recordable.py", line 45, in _wrapper
    result = func(*args, **kw)
  File "/Users/sborini/Work/github/mayavi/mayavi/core/engine.py", line 434, in new_scene
    viewer = self.scene_factory(**factory_kwargs)
  File "/Users/sborini/Work/github/mayavi/mayavi/core/ui/mayavi_scene.py", line 89, in viewer_factory
    viewer.open()
  File "/Users/sborini/Work/github/pyface/pyface/i_window.py", line 166, in open
    self._create()
  File "/Users/sborini/Work/github/pyface/pyface/ui/wx/application_window.py", line 151, in _create
    contents = self._create_contents(body)
  File "/Users/sborini/Work/github/mayavi/tvtk/tools/ivtk.py", line 392, in _create_contents
    self.scene = self._scene_factory(parent)
  File "/Users/sborini/Work/github/mayavi/mayavi/core/ui/mayavi_scene.py", line 68, in mayavi_scene_factory
    s = MayaviScene(parent, stereo=p['stereo'])
  File "/Users/sborini/Work/github/mayavi/tvtk/pyface/ui/wx/decorated_scene.py", line 69, in __init__
    super(DecoratedScene, self).__init__(parent, **traits)
  File "/Users/sborini/Work/github/mayavi/tvtk/pyface/ui/wx/scene.py", line 305, in __init__
    self.picker = picker.Picker(self)
  File "/Users/sborini/Work/github/mayavi/tvtk/pyface/picker.py", line 260, in __init__
    self.p_mapper.input = self.p_source.output
  File "/Users/sborini/.jaguar/envs/jaguar/lib/python2.7/site-packages/traits/trait_handlers.py", line 104, in _read_only
    name, class_of( object ) )
traits.trait_errors.TraitError: The 'input' trait of a PolyDataMapper instance is 'read only'.
```
