### ISSUE TITLE
Building TVTK classes fails: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by scbarton** [enthought/mayavi#271]
Using VTK 6.3 installed by homebrew and mayavi[app] installed by pip, I received this error:
> `>>> import mayavi.mlab`
>    ********************************************************************************
>    WARNING: Imported VTK version (6.3) does not match the one used
>         to build the TVTK classes (5.1). This may cause problems.
>         Please rebuild TVTK.
>    ********************************************************************************

So I tried to install mayavi from source using `python setup.py build` and received this error:

	running build
	----------------------------------------------------------------------
	Building TVTK classes...
	Traceback (most recent call last):
	  File "setup.py", line 471, in <module>
	
	  File "/usr/local/lib/python2.7/site-packages/numpy/distutils/core.py", line 169, in setup
		return old_setup(**new_attr)
	  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
		dist.run_commands()
	  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
		self.run_command(cmd)
	  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
		cmd_obj.run()
	  File "setup.py", line 303, in run
	
	  File "setup.py", line 290, in build_tvtk_classes_zip
	
	  File "tvtk/setup.py", line 62, in gen_tvtk_classes_zip
		# numpy.distutils does the Wrong(TM) thing.
	  File "tvtk/code_gen.py", line 101, in generate_code
	  File "tvtk/code_gen.py", line 191, in _write_wrapper_class
	  File "tvtk/wrapper_gen.py", line 80, in generate_code
	  File "tvtk/wrapper_gen.py", line 180, in _gen_methods
	  File "tvtk/wrapper_gen.py", line 764, in _gen_other_methods
	  File "tvtk/wrapper_gen.py", line 1066, in _write_tvtk_method
	  File "tvtk/vtk_parser.py", line 311, in get_method_signature
	AttributeError: 'NoneType' object has no attribute 'find'

I think this is the same issue as [159](https://github.com/enthought/mayavi/issues/159) except for a newer version of VTK.

**Comment by jenshnielsen** [comment]
I was able to build mayavi against vtk 6.3 with #247 merged manually. Unfortunatly that is still not part of the main tree

**Comment by scbarton** [comment]
Yes, thanks, I was able to build with that as well. I used:

    pip install https://github.com/dmsurti/mayavi/archive/4d4aaf315a29d6a86707dd95149e27d9ed2225bf.zip

**Comment by prabhuramachandran** [comment]
PR #247 is merged so am closing this.
