### ISSUE TITLE
Mayavi unit test_recorder fails on VTK 6.3

### ISSUE THREAD

**Issue by dmsurti** [enthought/mayavi#279]
After merging PR #250, with VTK 6.3, the following test fails with VTK 6.3:

```
======================================================================
ERROR: Test if saving tape to file works.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/deepaksurti/repos/git/mayavi/mayavi/tests/test_recorder.py", line 444, in test_save
    tape.save(f)
  File "/Users/deepaksurti/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/apptools/scripting/recorder.py", line 375, in save
    file.write(self.get_code())
TypeError: unicode argument expected, got 'str'
```

All other unit tests (tvtk/mayavi), integration tests pass.

**Comment by dmsurti** [comment]
Using the current `apptools` from the `master` branch resolves this error. Closing.

So `VTK 6.3` compatibility looks good after PR #250 merge.

@prabhuramachandran Thanks.
