### ISSUE TITLE
Failures with VTK 7.0

### ISSUE THREAD

**Issue by dmsurti** [enthought/mayavi#288]
I tested with VTK 7.0 on Mac OS X 10.10. These are the failures: 
* TVTK:   FAILED (errors=1, failures=5)
* Mayavi: FAILED (errors=1).

TVTK Failures
---
```
...........F......SS...........................F....S.......E.......F..............FF......
======================================================================
ERROR: Case where parent has GetInput and child SetInput.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/deepaksurti/repos/git/mayavi/tvtk/tests/test_tvtk.py", line 599,
in test_parent_child_input
    vm = tvtk.VolumeTextureMapper2D()
AttributeError: 'TVTK' object has no attribute 'VolumeTextureMapper2D'

======================================================================
FAIL: Basic tests for the VTK module.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/deepaksurti/repos/git/mayavi/tvtk/tests/test_class_tree.py",
line 79, in test_basic_vtk
    self.assertEqual(names, expect)
AssertionError: Lists differ: ['object', 'vtkColor3', 'vtkCo... != ['object',
'vtkColor3', 'vtkCo...

First differing element 9:
vtkVariantStrictWeakOrderKey
vtkVector

First list contains 1 additional elements.
First extra element 12:
vtkVector3

  ['object',
   'vtkColor3',
   'vtkColor4',
   'vtkDenseArray',
   'vtkQuaternion',
   'vtkRect',
   'vtkSparseArray',
   'vtkTuple',
   'vtkTypedArray',
-  'vtkVariantStrictWeakOrderKey',
   'vtkVector',
   'vtkVector2',
   'vtkVector3']

======================================================================
FAIL: Test if custom modules can be imported.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/deepaksurti/repos/git/mayavi/tvtk/tests/test_tvtk.py", line 114,
in test_custom
    self.assertEqual(r.__class__.__bases__, expect)
AssertionError: Tuples differ: () != (<type 'object'>,)

Second tuple contains 1 additional elements.
First extra element 0:
<type 'object'>

- ()
+ (<type 'object'>,)

======================================================================
FAIL: Test if all the TVTK classes can be instantiated
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/deepaksurti/repos/git/mayavi/tvtk/tests/test_tvtk.py", line 665,
in test_all_instantiable
    raise AssertionError(message.format(''.join(errors)))
AssertionError: Not all classes could be instantiated:
Traceback (most recent call last):
  File "/Users/deepaksurti/repos/git/mayavi/tvtk/tests/test_tvtk.py", line 660,
in test_all_instantiable
    tvtk_klass()
  File "tvtk_classes/span_space.py", line 51, in __init__
    tvtk_base.TVTKBase.__init__(self, vtk.vtkSpanSpace, obj, update, **traits)
  File "/Users/deepaksurti/repos/git/mayavi/tvtk/tvtk_base.py", line 321, in
__init__
    self.update_traits()
  File "/Users/deepaksurti/repos/git/mayavi/tvtk/tvtk_base.py", line 469, in
update_traits
    setattr(self, name, val)
  File
"/Users/deepaksurti/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traits/trait_handlers.py",
line 172, in error
    value )
TraitError: The 'resolution' trait of a SpanSpace instance must be 1 <= a long
integer <= 2147483647 or 4759352976, but a value of 0L <type 'long'> was
specified.



======================================================================
FAIL: Check if parser is usable without the tree.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/deepaksurti/repos/git/mayavi/tvtk/tests/test_vtk_parser.py",
line 266, in test_no_tree
    self.test_parse()
  File "/Users/deepaksurti/repos/git/mayavi/tvtk/tests/test_vtk_parser.py",
line 163, in test_parse
    self.assertEqual(p.get_other_methods(), res)
AssertionError: Lists differ: ['AddShaderVariable', 'Backfac... !=
['AddShaderVariable', 'Backfac...

First differing element 3:
PostRender
LoadMaterial

Second list contains 1 additional elements.
First extra element 9:
Render

  ['AddShaderVariable',
   'BackfaceRender',
   'DeepCopy',
+  'LoadMaterial',
+  'LoadMaterialFromString',
   'PostRender',
   'ReleaseGraphicsResources',
   'RemoveAllTextures',
   'RemoveTexture',
-  'Render',
?          ^

+  'Render']
?          ^

-  'VTKTextureUnit']

======================================================================
FAIL: Check if the methods are organized correctly.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/deepaksurti/repos/git/mayavi/tvtk/tests/test_vtk_parser.py",
line 163, in test_parse
    self.assertEqual(p.get_other_methods(), res)
AssertionError: Lists differ: ['AddShaderVariable', 'Backfac... !=
['AddShaderVariable', 'Backfac...

First differing element 3:
PostRender
LoadMaterial

Second list contains 1 additional elements.
First extra element 9:
Render

  ['AddShaderVariable',
   'BackfaceRender',
   'DeepCopy',
+  'LoadMaterial',
+  'LoadMaterialFromString',
   'PostRender',
   'ReleaseGraphicsResources',
   'RemoveAllTextures',
   'RemoveTexture',
-  'Render',
?          ^

+  'Render']
?          ^

-  'VTKTextureUnit']

----------------------------------------------------------------------
Ran 91 tests in 9.921s

FAILED (SKIP=3, errors=1, failures=5)
```

Mayavi Failures
---
```
ERROR: Test if saving tape to file works.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/deepaksurti/repos/git/mayavi/mayavi/tests/test_recorder.py",
line 444, in test_save
    tape.save(f)
  File
"/Users/deepaksurti/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/apptools/scripting/recorder.py",
line 375, in save
    file.write(self.get_code())
TypeError: unicode argument expected, got 'str'

----------------------------------------------------------------------
Ran 239 tests in 14.433s
```

**Comment by dmsurti** [comment]
Closed by #299.
