### ISSUE TITLE
Exception at exit if mayavi is opened and then closed without additional operation

### ISSUE THREAD

**Issue by stefanoborini** [enthought/mayavi#319]
To reproduce: start mayavi2, then quit it immediately afterwards.

```
Traceback (most recent call last):
  File "/Users/sborini/.jaguar/envs/jaguar/lib/python2.7/site-packages/traitsui/qt4/list_str_model.py", line 59, in rowCount
    return editor.adapter.len(editor.object, editor.name)
  File "/Users/sborini/.jaguar/envs/jaguar/lib/python2.7/site-packages/traitsui/list_str_adapter.py", line 204, in len
    return len( getattr( object, trait ) )
AttributeError: 'NoneType' object has no attribute '_pending_engine_sources'
Traceback (most recent call last):
  File "/Users/sborini/.jaguar/envs/jaguar/lib/python2.7/site-packages/traitsui/qt4/list_str_model.py", line 59, in rowCount
    return editor.adapter.len(editor.object, editor.name)
  File "/Users/sborini/.jaguar/envs/jaguar/lib/python2.7/site-packages/traitsui/list_str_adapter.py", line 204, in len
    return len( getattr( object, trait ) )
AttributeError: 'NoneType' object has no attribute '_pending_engine_sources'
Traceback (most recent call last):
  File "/Users/sborini/.jaguar/envs/jaguar/lib/python2.7/site-packages/traitsui/qt4/list_str_model.py", line 59, in rowCount
    return editor.adapter.len(editor.object, editor.name)
  File "/Users/sborini/.jaguar/envs/jaguar/lib/python2.7/site-packages/traitsui/list_str_adapter.py", line 204, in len
    return len( getattr( object, trait ) )
AttributeError: 'NoneType' object has no attribute '_pending_engine_sources'
Traceback (most recent call last):
  File "/Users/sborini/.jaguar/envs/jaguar/lib/python2.7/site-packages/traitsui/qt4/list_str_model.py", line 59, in rowCount
    return editor.adapter.len(editor.object, editor.name)
  File "/Users/sborini/.jaguar/envs/jaguar/lib/python2.7/site-packages/traitsui/list_str_adapter.py", line 204, in len
    return len( getattr( object, trait ) )
AttributeError: 'NoneType' object has no attribute '_pending_engine_sources'
****
```

**Comment by stefanoborini** [comment]
Should be trivial to fix. Assigning to me.

**Comment by stefanoborini** [comment]
Information: this is actually due to simphony-mayavi. Keeping it here.

**Comment by itziakos** [comment]
@stefanoborini you mean `mayavi2` correct?

**Comment by stefanoborini** [comment]
@itziakos Yes. I am digging quite a lot in traitsui. It looks like there's a problem with the deregistration at dispose, meaning that a Qt connection is probably not cleaned and when disposal happen, a slot is invoked but the model object is already gone.

**Comment by stefanoborini** [comment]
@itziakos Unfortunately all the cleanup is performed in multiple phases through the event loop, so it's hard to track the root cause.

**Comment by stefanoborini** [comment]
Found the root cause. it's a traitsui bug. I am opening a bug there and propose a PR against that description. Will add reference.

**Comment by stefanoborini** [comment]
Bug has been fixed and fix is merged into traitsui master. Closing this one.
