### ISSUE TITLE
Exception when opening and closing Views

### ISSUE THREAD

**Issue by stefanoborini** [enthought/mayavi#321]
In mayavi2, while I was playing with the View visibility, I got this exception

```
Exception occurred in traits notification handler for object: <envisage.ui.workbench.workbench_window.WorkbenchWindow object at 0x11f226ef0>, trait: active_editor, old value: Editor(TVTK Scene 1), new value: None
Traceback (most recent call last):
  File "/Users/sborini/.jaguar/envs/jaguar/lib/python2.7/site-packages/traits/trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/Users/sborini/.jaguar/envs/jaguar/lib/python2.7/site-packages/traits/trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "/Users/sborini/.jaguar/envs/jaguar/lib/python2.7/site-packages/pyface/ui/qt4/workbench/workbench_window_layout.py", line 339, in _qt4_active_editor_changed
    self._qt4_editor_area.setTabTextColor(new.control)
AttributeError: 'NoneType' object has no attribute 'control'
ERROR|2016-03-22 11:02:31,274|Exception occurred in traits notification handler for object: <envisage.ui.workbench.workbench_window.WorkbenchWindow object at 0x11f226ef0>, trait: active_editor, old value: Editor(TVTK Scene 1), new value: None
Traceback (most recent call last):
  File "/Users/sborini/.jaguar/envs/jaguar/lib/python2.7/site-packages/traits/trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/Users/sborini/.jaguar/envs/jaguar/lib/python2.7/site-packages/traits/trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "/Users/sborini/.jaguar/envs/jaguar/lib/python2.7/site-packages/pyface/ui/qt4/workbench/workbench_window_layout.py", line 339, in _qt4_active_editor_changed
    self._qt4_editor_area.setTabTextColor(new.control)
AttributeError: 'NoneType' object has no attribute 'control'
```

**Comment by stefanoborini** [comment]
The problem occurs when closing the only tab in the main View, leaving it empty.

**Comment by stefanoborini** [comment]
PR open for it

**Comment by stefanoborini** [comment]
Leaving it open until the new release of pyface is available.

**Comment by stefanoborini** [comment]
@kitchoi should I update against the new version of pyface?

**Comment by kitchoi** [comment]
@stefanoborini if you verify that this issue is solved with the new version of pyface, please feel free to update here.

**Comment by stefanoborini** [comment]
@kitchoi  Seem solved, but apparently the whole mayavi depends on the pyface git master. There was a test added to pyface, so the only thing I can do is to create a trivial PR to let travis retrieve the most recent pyface and build against it.

**Comment by stefanoborini** [comment]
@kitchoi Or any other PR you might have now works well as a test. Closing.
