### ISSUE TITLE
Occasional failure on Windows/appveyor

### ISSUE THREAD

**Issue by stefanoborini** [enthought/mayavi#328]
We get this occasional failure on windows

```
Test if the test fixture works ... ok
 
======================================================================
FAIL: Test if saving a visualization and restoring it works.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\mayavi\mayavi\tests\test_poly_data_reader.py", line 182, in test_save_and_restore
    self.check_saving(self.e, self.scene, self.bounds)
  File "C:\projects\mayavi\mayavi\tests\data_reader_test_base.py", line 75, in check_saving
    self.check(scene,bounds,error)
  File "C:\projects\mayavi\mayavi\tests\data_reader_test_base.py", line 59, in check
    self.assertEqual(numpy.allclose(got, bounds, atol=error), True, msg)
AssertionError: Got: (0.0, 3.0210672776011174e+29, 0.0, 1.0, 0.0, 1.600000023841858); expected: (0.0, 1.0, 0.0, 1.0, 0.0, 1.6)
-------------------- >> begin captured logging << --------------------
mayavi.core.registry: DEBUG: Engine [<mayavi.core.null_engine.NullEngine object at 0x00000000187D4888>] named NullEngine1 registered
--------------------- >> end captured logging << ---------------------
 
----------------------------------------------------------------------
Ran 249 tests in 18.876s
 
FAILED (SKIP=7, failures=1)
```

It's rather frequent, yet not constant.

**Comment by stefanoborini** [comment]
I investigate it because it's frequent enough to be annoying.

**Comment by stefanoborini** [comment]
In pull request https://github.com/enthought/mayavi/pull/329

**Comment by kitchoi** [comment]
Same issue as this one: #233
