### ISSUE TITLE
Consistent test errors on MacOSX

### ISSUE THREAD

**Issue by stefanoborini** [enthought/mayavi#359]
The following test errors occur on my mac consistently on master.

```
======================================================================
ERROR: Tests if TVTK scene can be garbage collected.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sborini/Work/github/mayavi/tvtk/tests/test_garbage_collection.py", line 26, in test_tvtk_scene
    self.check_object_garbage_collected(create_fn, close_fn)
  File "/Users/sborini/Work/github/mayavi/tvtk/tests/common.py", line 61, in check_object_garbage_collected
    self.assertTrue(object_collected[0])
IndexError: list index out of range

======================================================================
ERROR: Test if custom modules can be imported.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sborini/Work/github/mayavi/tvtk/tests/test_tvtk.py", line 107, in test_custom
    r = tvtk.XMLDataReader()
  File "tvtk_classes/xml_data_reader.py", line 46, in __init__
    tvtk_base.TVTKBase.__init__(self, vtk.vtkXMLDataReader, obj, update, **traits)
  File "/Users/sborini/Work/github/mayavi/tvtk/tvtk_base.py", line 321, in __init__
    self._vtk_obj = klass()
TypeError: this is an abstract class and cannot be instantiated

```

**Comment by stefanoborini** [comment]
I want to understand what's going on here.
