### ISSUE TITLE
Occasional prop_color_value set failure on MacOS

### ISSUE THREAD

**Issue by stefanoborini** [enthought/mayavi#360]
The following tests occasionally fail on my mac. 

```
======================================================================
FAIL: Test if all the TVTK classes can be instantiated
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sborini/Work/github/mayavi/tvtk/tests/test_tvtk.py", line 669, in test_all_instantiable
    raise AssertionError(message.format(''.join(errors)))
AssertionError: Not all classes could be instantiated:
Traceback (most recent call last):
  File "/Users/sborini/Work/github/mayavi/tvtk/tests/test_tvtk.py", line 664, in test_all_instantiable
    tvtk_klass()
  File "tvtk_classes/hardware_selector.py", line 81, in __init__
    tvtk_base.TVTKBase.__init__(self, vtk.vtkHardwareSelector, obj, update, **traits)
  File "/Users/sborini/Work/github/mayavi/tvtk/tvtk_base.py", line 334, in __init__
    self.update_traits()
  File "/Users/sborini/Work/github/mayavi/tvtk/tvtk_base.py", line 482, in update_traits
    setattr(self, name, val)
  File "/Users/sborini/.jaguar/envs/jaguar/lib/python2.7/site-packages/traits/trait_handlers.py", line 172, in error
    value )
TraitError: The 'prop_color_value' trait of a HardwareSelector instance must be a tuple of the form: (0.0 <= a floating point number <= 1.0, 0.0 <= a floating point number <= 1.0, 0.0 <= a floating point number <= 1.0), but a value of (1.0720514219217772e-35, 1.5052411792145747e-39, 9218721025359872.0) <type 'tuple'> was specified.
Traceback (most recent call last):
  File "/Users/sborini/Work/github/mayavi/tvtk/tests/test_tvtk.py", line 664, in test_all_instantiable
    tvtk_klass()
  File "tvtk_classes/open_gl_hardware_selector.py", line 44, in __init__
    tvtk_base.TVTKBase.__init__(self, vtk.vtkOpenGLHardwareSelector, obj, update, **traits)
  File "/Users/sborini/Work/github/mayavi/tvtk/tvtk_base.py", line 334, in __init__
    self.update_traits()
  File "/Users/sborini/Work/github/mayavi/tvtk/tvtk_base.py", line 482, in update_traits
    setattr(self, name, val)
  File "/Users/sborini/.jaguar/envs/jaguar/lib/python2.7/site-packages/traits/trait_handlers.py", line 172, in error
    value )
TraitError: The 'prop_color_value' trait of an OpenGLHardwareSelector instance must be a tuple of the form: (0.0 <= a floating point number <= 1.0, 0.0 <= a floating point number <= 1.0, 0.0 <= a floating point number <= 1.0), but a value of (0.0, 0.0, -3.837566375786139e-11) <type 'tuple'> was specified.
```

**Comment by kitchoi** [comment]
Almost certainly a vtk bug.
Reproduce using vtk python wrapper (vtk 6.3)
```
import vtk
import time

for _ in range(10):
    vtk_obj = vtk.vtkOpenGLHardwareSelector()
    print vtk_obj.GetPropColorValue()
    time.sleep(1)
```

Output:
```
(2.975582179396061e-38, 1.401298464324817e-45, 1.0722085646526054e-38)
(0.0, 0.0, 0.0)
(2.975582179396061e-38, 1.401298464324817e-45, 1.0722085646526054e-38)
(5.344585974097996e-39, 1.401298464324817e-45, 5.344866233790861e-39)
(2.975582179396061e-38, 1.401298464324817e-45, 1.0722085646526054e-38)
(0.0, 0.0, 0.0)
(4.6179809698425413e+24, 2.0110569049325306e+20, 175.439208984375)
(1.7033563725959244e+35, 4.591634678053128e-41, 1.7033167585146673e+35)
(4.6179809698425413e+24, 2.0110569049325306e+20, 175.439208984375)
(5.344585974097996e-39, 1.401298464324817e-45, 5.344866233790861e-39)
```

**Comment by kitchoi** [comment]
Perhaps not a bug in VTK's point of view, i.e. `PropColorValue` is meant to be undefined until some events happen, and yet before these events occur, we already want to update `prop_color_value` with these undefined values.  There are many such instances as I have come across them while implementing #362 

For the record:
`PropColorValue` is defined in vtkHardwardSelector.cxx as float[3], and is only specified in vtkOpenGLHardwareSelector.cxx on calling methods such as `vtkOpenGLHardwareSelector.BeginRenderProp`.

**Comment by stefanoborini** [comment]
ok, so basically undefined value. Will file a bug report on vtk.

**Comment by stefanoborini** [comment]
Filed as http://www.vtk.org/Bug/view.php?id=16098

**Comment by kitchoi** [comment]
Working on it.

**Comment by stefanoborini** [comment]
is this fixed?
