### ISSUE TITLE
'extent' argument in mlab.imshow raises exception

### ISSUE THREAD

**Issue by pberkes** [enthought/mayavi#37]
In [21]: mlab.imshow(np.random.rand(10,20), interpolate=False, extent=[-1,11,-1,21,0,0])
Exception occurred in traits notification handler for object: <mayavi.tools.modules.ImageActorFactory object at 0x1d4487b0>, trait: extent, old value: [0 0 0 0 0 0], new value: [-1 11 -1 21  0  0]
Traceback (most recent call last):
  File "/Users/pberkes/egit/ETS/traits/traits/trait_notifiers.py", line 366, in call_1
    self.handler( object )
  File "/Users/pberkes/egit/ETS/mayavi/mayavi/tools/modules.py", line 96, in _extent_changed
    tools.set_extent(self._target, self.extent)
  File "/Users/pberkes/egit/ETS/mayavi/mayavi/tools/tools.py", line 294, in set_extent
    xmin, xmax, ymin, ymax, zmin, zmax = module.actor.actor.bounds
AttributeError: 'ImageActor' object has no attribute 'actor'

**Comment by stefanoborini** [comment]
confirmed. Investigating.

**Comment by stefanoborini** [comment]
Fix available. Waiting for PR merge.
