### ISSUE TITLE
Getting KeyError while installing with pip

### ISSUE THREAD

**Issue by cemysf** [enthought/mayavi#401]
Hello, I'm getting this error when installing with pip:
`KeyError: 'input_connection'`

Log is below:

```
----------------------------------------------------------------------

Deleting possibly old TVTK classes

Building TVTK classes... Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/pip_build_root/mayavi/setup.py", line 476, in <module>

    **config

  File "/usr/lib/python2.7/dist-packages/numpy/distutils/core.py", line 169, in setup

    return old_setup(**new_attr)

  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup

    dist.run_commands()

  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands

    self.run_command(cmd)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/usr/lib/python2.7/dist-packages/numpy/distutils/command/install.py", line 59, in run

    r = self.setuptools_run()

  File "/usr/lib/python2.7/dist-packages/numpy/distutils/command/install.py", line 33, in setuptools_run

    return old_install_mod._install.run(self)

  File "/usr/lib/python2.7/distutils/command/install.py", line 613, in run

    self.run_command(cmd_name)

  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/tmp/pip_build_root/mayavi/setup.py", line 361, in run

    build_tvtk_classes_zip()

  File "/tmp/pip_build_root/mayavi/setup.py", line 294, in build_tvtk_classes_zip

    gen_tvtk_classes_zip()

  File "tvtk/setup.py", line 66, in gen_tvtk_classes_zip

    import numpy

  File "/tmp/pip_build_root/mayavi/tvtk/code_gen.py", line 117, in generate_code

    self._write_wrapper_class(node, tvtk_name)

  File "/tmp/pip_build_root/mayavi/tvtk/code_gen.py", line 207, in _write_wrapper_class

    self.wrap_gen.generate_code(node, out)

  File "/tmp/pip_build_root/mayavi/tvtk/wrapper_gen.py", line 84, in generate_code

    self._gen_methods(node, out)

  File "/tmp/pip_build_root/mayavi/tvtk/wrapper_gen.py", line 195, in _gen_methods

    get_set = self._gen_get_set_methods(klass, out)

  File "/tmp/pip_build_root/mayavi/tvtk/wrapper_gen.py", line 570, in _gen_get_set_methods

    del updateable_traits['input_connection']

KeyError: 'input_connection'

----------------------------------------
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/mayavi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-4k301K-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/mayavi
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 707, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 715, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/mayavi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-4k301K-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/mayavi
```

**Comment by kitchoi** [comment]
Thanks for your report.  Could you provide the version of VTK please?
Unless your vtk is a very old one, you may get the version by typing these in your python prompt:
```
import vtk
vtk.vtkVersion.GetVTKVersion()
```
Thanks.

**Comment by cemysf** [comment]
```
$ python -c "import vtk; print vtk.vtkVersion.GetVTKVersion()"
5.8.0

```

**Comment by prabhuramachandran** [comment]
Can you please test with the version of Mayavi from git if possible, you should be able to do this:

``` pip install git+https://github.com/enthought/mayavi
```

If this does not work, please let us know.
