### ISSUE TITLE
Problem installing mayavi 

### ISSUE THREAD

**Issue by danovar** [enthought/mayavi#438]
Hello everyone,

due to some rendering issues with 3dbarplot in matplotlib I wanted to try plotting with mayavi. First I tried to install it via pip install mayavi. Then I downloaded the zipped package on the mayavi website and started setup.py.

Both ways finaly produced an error:
...
copying tvtk\pyface\ui\wx\__init__.py -> build\lib.win32-2.7\tvtk\pyface\ui\wx
running build_ext
customize MSVCCompiler
customize MSVCCompiler using build_ext
building 'tvtk.array_ext' extension
compiling C sources
error: [Error 2] Das System kann die angegebene Datei nicht finden 
...

Is there anything missing in the tvtk-sourcecode? I also tried to install tvtk only, but I can't find a download website.

I also made sure that all other required packages are alreadyx installed.

Running Python 2,7 on Windows 7, with VTK 7.0. And I am a Python newbie (with bad english :-))

Thanks in advance.

**Comment by prabhuramachandran** [comment]
If you install canopy or conda it should be much easier for you to install mayavi.  Installing via pip is a bit difficult because you will need to install VTK.  One possibility for you to install into your current setup might also be to install the packages from here: http://www.lfd.uci.edu/~gohlke/pythonlibs/

**Comment by mforbes** [comment]
[The instructions](https://docs.enthought.com/mayavi/mayavi/installation.html) suggest `conda create --name pyforge python=2.7`... these should at least be updated!  Python 2.7 died in 2020.

The instructions for installing from source are also wrong, referencing a non-existent  `requirements.txt` (https://github.com/enthought/mayavi/issues/1093, https://github.com/enthought/mayavi/issues/1284)

Using Pixi to try to install this on a Mac OS M1 Max system from conda-forge, I run into the following issues:

```
$ pixi add vtk pyqt mayavi
...
✔ Added vtk >=9.4.2,<10
✔ Added pyqt >=5.15.11,<6
✔ Added mayavi >=4.8.3,<5
$ pixi shell
$ mayavi2
objc[71404]: Class QT_ROOT_LEVEL_POOL__THESE_OBJECTS_WILL_BE_RELEASED_WHEN_QAPP_GOES_OUT_OF_SCOPE is implemented in both .../envs/default/lib/libQt6Core.6.9.3.dylib (0x154c41698) and .../envs/default/lib/libQt5Core.5.15.15.dylib (0x17eec52f8). One of the two will be used. Which one is undefined.
objc[71404]: Class KeyValueObserver is implemented in both .../envs/default/lib/libQt6Core.6.9.3.dylib (0x154c416c0) and .../envs/default/lib/libQt5Core.5.15.15.dylib (0x17eec5320). One of the two will be used. Which one is undefined.
objc[71404]: Class RunLoopModeTracker is implemented in both .../envs/default/lib/libQt6Core.6.9.3.dylib (0x154c415d0) and .../envs/default/lib/libQt5Core.5.15.15.dylib (0x17eec5370). One of the two will be used. Which one is undefined.
Traceback (most recent call last):
  File ".../envs/default/bin/mayavi2", line 7, in <module>
    from mayavi.scripts.mayavi2 import main
  File ".../envs/default/lib/python3.13/site-packages/mayavi/scripts/mayavi2.py", line 462, in <module>
    from mayavi.plugins.app import Mayavi, setup_logger
  File ".../envs/default/lib/python3.13/site-packages/mayavi/plugins/app.py", line 19, in <module>
    from .mayavi_workbench_application import MayaviWorkbenchApplication
  File ".../envs/default/lib/python3.13/site-packages/mayavi/plugins/mayavi_workbench_application.py", line 13, in <module>
    from envisage.ui.workbench.api import WorkbenchApplication
  File ".../envs/default/lib/python3.13/site-packages/envisage/ui/workbench/api.py", line 13, in <module>
    from .workbench import Workbench
  File ".../envs/default/lib/python3.13/site-packages/envisage/ui/workbench/workbench.py", line 18, in <module>
    from envisage.api import IApplication
  File ".../envs/default/lib/python3.13/site-packages/envisage/api.py", line 71, in <module>
    from .egg_plugin_manager import EggPluginManager
  File ".../envs/default/lib/python3.13/site-packages/envisage/egg_plugin_manager.py", line 19, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

So even `conda-forge` does not provide a reliable installation path on all platforms.
