### ISSUE TITLE
Workaround for Anaconda Python 3.5.2 Distribution

### ISSUE THREAD

**Issue by mwl5399** [enthought/mayavi#448]
I am trying to use Mayavi to visualize radar data collected during thunderstorms over the plains. The code does not get past the line: from mayavi import *. The error I receive in the IPython console is:
Traceback (most recent call last):

  File "<ipython-input-12-154651487c81>", line 1, in <module>
    runfile('C:/Users/Matt/.spyder-py3/RadarMovieMaker.py', wdir='C:/Users/Matt/.spyder-py3')

  File "C:\Users\Matt\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "C:\Users\Matt\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Matt/.spyder-py3/RadarMovieMaker.py", line 10, in <module>
    from mayavi.mlab import *

  File "C:\Users\Matt\Anaconda3\lib\site-packages\mayavi-4.5.0-py3.5-win-amd64.egg\mayavi\mlab.py", line 27, in <module>
    from mayavi.tools.camera import view, roll, yaw, pitch, move

  File "C:\Users\Matt\Anaconda3\lib\site-packages\mayavi-4.5.0-py3.5-win-amd64.egg\mayavi\tools\camera.py", line 25, in <module>
    from .engine_manager import get_engine

  File "C:\Users\Matt\Anaconda3\lib\site-packages\mayavi-4.5.0-py3.5-win-amd64.egg\mayavi\tools\engine_manager.py", line 12, in <module>
    from mayavi.preferences.api import preference_manager

  File "C:\Users\Matt\Anaconda3\lib\site-packages\mayavi-4.5.0-py3.5-win-amd64.egg\mayavi\preferences\api.py", line 4, in <module>
    from .preference_manager import preference_manager

  File "C:\Users\Matt\Anaconda3\lib\site-packages\mayavi-4.5.0-py3.5-win-amd64.egg\mayavi\preferences\preference_manager.py", line 29, in <module>
    from traitsui.api import View, Group, Item

  File "C:\Users\Matt\Anaconda3\lib\site-packages\traitsui\api.py", line 36, in <module>
    from .editors.api import ArrayEditor

  File "C:\Users\Matt\Anaconda3\lib\site-packages\traitsui\editors\__init__.py", line 23, in <module>
    from .api import ArrayEditor

  File "C:\Users\Matt\Anaconda3\lib\site-packages\traitsui\editors\api.py", line 24, in <module>
    from .code_editor import CodeEditor

  File "C:\Users\Matt\Anaconda3\lib\site-packages\traitsui\editors\code_editor.py", line 36, in <module>
    class ToolkitEditorFactory ( EditorFactory ):

  File "C:\Users\Matt\Anaconda3\lib\site-packages\traitsui\editors\code_editor.py", line 48, in ToolkitEditorFactory
    mark_color = Color( 0xECE9D8 )

  File "C:\Users\Matt\Anaconda3\lib\site-packages\traits\traits.py", line 489, in __call__
    return self.maker_function( *args, **metadata )

  File "C:\Users\Matt\Anaconda3\lib\site-packages\traits\traits.py", line 1203, in Color
    return ColorTrait( *args, **metadata )

  File "C:\Users\Matt\Anaconda3\lib\site-packages\traitsui\toolkit_traits.py", line 7, in ColorTrait
    return toolkit().color_trait( *args, **traits )

  File "C:\Users\Matt\Anaconda3\lib\site-packages\traitsui\toolkit.py", line 162, in toolkit
    return _toolkit

  File "C:\Users\Matt\Anaconda3\lib\contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)

  File "C:\Users\Matt\Anaconda3\lib\site-packages\traitsui\toolkit.py", line 75, in provisional_toolkit
    yield

  File "C:\Users\Matt\Anaconda3\lib\site-packages\traitsui\toolkit.py", line 161, in toolkit
    _toolkit = _import_toolkit(toolkit_name)

  File "C:\Users\Matt\Anaconda3\lib\site-packages\traitsui\toolkit.py", line 83, in _import_toolkit
    return __import__( name, globals=globals(), level=1 ).toolkit

  File "C:\Users\Matt\Anaconda3\lib\site-packages\traitsui\qt4\__init__.py", line 18, in <module>
    import pyface.qt

  File "C:\Users\Matt\Anaconda3\lib\site-packages\pyface\qt\__init__.py", line 44, in <module>
    % qt_api)

RuntimeError: Invalid Qt API 'pyqt5', valid values are: 'pyqt' or 'pyside'

I cannot revert pyqt5 to pyqt4 without degrading the version of Anaconda I have and the Spyder editor I am using. Is there a known workaround or do I have to find another version of Anaconda/Python to use?

**Comment by prabhuramachandran** [comment]
Unfortunately, ETS does not yet support Qt5.  You will probably need to create another environment with qt4 instead of qt5. @corranwebster -- do you have any suggestions for what is needed if we want traits/pyface/traitsui/envisage to work with Qt5?  Thanks!

**Comment by scienceopen** [comment]
You can [workaround](https://www.scivision.co/mayavi-qt5-create-conda-env-qt4/) this in Anaconda/Miniconda Python by setting up a QT4 environment:

    conda create -n oldqt python=3 pyqt=4
    source activate oldqt

    conda install -c menpo mayavi
