### ISSUE TITLE
mayavi not running

### ISSUE THREAD

**Issue by debbisrs** [enthought/mayavi#456]
Dear, 

After installation of mayavi I see the the following errors on running mayavi2 in terminal:

debabrata@debabrata-LIFEBOOK-A544:~$ mayavi2
Traceback (most recent call last):
  File "/usr/local/bin/mayavi2", line 11, in <module>
    load_entry_point('mayavi==4.5.0', 'gui_scripts', 'mayavi2')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 567, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2604, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2264, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2270, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/mayavi/scripts/mayavi2.py", line 494, in <module>
    raise ImportError(msg)
ImportError: cannot import name provides
________________________________________________________________________________
Could not load envisage. You might have a missing dependency.
Do you have the EnvisageCore and EnvisagePlugins installed?

If you installed Mayavi with easy_install, try 'easy_install <pkg_name>'.
'easy_install Mayavi[app]' will also work.

If you performed a source checkout and installed via 'python setup.py develop',
be sure to run the same command in the EnvisageCore and EnvisagePlugins folders.

If these packages appear to be installed, check that your numpy and
configobj are installed and working. If you need numpy, 'easy_install numpy'
will install numpy. Similarly, 'easy_install configobj' will install
configobj.

Please suggest.

Thank you

**Comment by jonathanrocher** [comment]
What python distribution are you using? You system's? How did you install mayavi? What platform?

**Comment by debbisrs** [comment]
Dear,
I'm using ubuntu 14.04, 32-bit. I have both python 2.7 & 3. I tired
installing mayavi with all possible ways, eg, pip, easy_install, from
synaptic pack age manager, source code. But always the same error is shown.

Thank You.

**Comment by kitchoi** [comment]
Hi @debbisrs, could you please provide the versions of traits, traitsui and pyface?
Try
`pip show traits traitsui pyface`

**Comment by jonathanrocher** [comment]
Any chance you could install Canopy (https://store.enthought.com/downloads) or Anaconda (https://www.continuum.io/downloads) into your Ubuntu and use that as your distribution? It is by far the best and easiest way to install and manage packages and stay up to date. 

If you have already invested time and installed many packages in your python distribution then `pip` is probably your best bet but it will also require for you to install all of mayavi's dependencies, including `numpy`, `traits`, `traitsui`, `wx-python`, and `envisage`. To do that, `sudo pip install PACKAGE_NAME` should work except for wx-python, I had to do:
```
sudo apt-get install python-wxgtk3.0
```
I am finding the compilation of VTK to be the harder part.

You can make sure each of these dependencies are installed correctly by starting python and typing `import numpy`, `import traits`, `import envisage`... If you have an installation issue, that might help pinpoint which package is the cause of the issue. HTH.

**Comment by debbisrs** [comment]
Dear,
Thank You all for the response.
The version of the package are:
Traits=4.1.0
Traitsui=4.1.0
Pyface=4.1.0

**Comment by debbisrs** [comment]
Dear,
I have checked all &  see they are installed correctly.

**Comment by kitchoi** [comment]
@debbisrs I guess the "ImportError: cannot import name provides" refers to importing `traits.api.provides`, which is available for traits >= 4.4.0
Please could you try to update traits (you might benefit from updating traitsui and pyface as well) and see if that solves the problem?
