### ISSUE TITLE
Bug running MRI example

### ISSUE THREAD

**Issue by ghareth** [enthought/mayavi#458]
I get the following error, when attempting to run the MRI example, 
`http://docs.enthought.com/mayavi/mayavi/auto/example_mri.html#example-mri`

```
ERROR: In /Library/VTK/VTK-7.0.0/Common/ExecutionModel/vtkStreamingDemandDrivenPipeline.cxx, line 857
vtkCompositeDataPipeline (0x11d974a00): The update extent specified in the information for output port 0 on algorithm vtkImageGaussianSmooth(0x11d9cb5d0) is 0 2147483647 0 2147483647 0 2147483647, which is outside the whole extent 0 255 0 255 0 108.

Python(67938,0x700000429000) malloc: *** mach_vm_map(size=13835058045618487296) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
ERROR: In /Library/VTK/VTK-7.0.0/Common/Core/vtkDataArrayTemplate.txx, line 142
vtkUnsignedShortArray (0x14e68baa0): Unable to allocate 6917529022809243648 elements of size 2 bytes. 

aborted (disconnected)
```

I am running VTK 7.0.0. and Mayavi 4.5.0

When running the mayavi tests I get the following errors:

```
---------------------------------------------------------------------
Running TVTK tests.
.....................................................................................F...........................
----------------------------------------------------------------------
Ran 113 tests in 84.76 seconds

FAILED: there were 1 failures and 0 errors
File: /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tvtk/tests/test_tvtk.py

........s........s.................sF.....
======================================================================
FAIL: test_all_instantiable (__main__.TestTVTKModule)
Test if all the TVTK classes can be instantiated
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tvtk/tests/test_tvtk.py", line 877, in test_all_instantiable
    raise AssertionError(message.format(''.join(errors)))
AssertionError: Not all classes could be instantiated:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tvtk/tests/test_tvtk.py", line 872, in test_all_instantiable
    tvtk_klass()
  File "tvtk_classes/span_space.py", line 58, in __init__
    tvtk_base.TVTKBase.__init__(self, vtk.vtkSpanSpace, obj, update, **traits)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tvtk/tvtk_base.py", line 341, in __init__
    self.update_traits()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tvtk/tvtk_base.py", line 496, in update_traits
    setattr(self, name, val)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/traits/trait_handlers.py", line 172, in error
    value )
TraitError: The 'resolution' trait of a SpanSpace instance must be 1 <= a long integer <= 2147483647 or 4475246848, but a value of 4338548944L <type 'long'> was specified.



----------------------------------------------------------------------
Ran 42 tests in 54.721s

FAILED (failures=1, skipped=3)

File: /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tvtk/tests/test_vtk_parser.py

....
----------------------------------------------------------------------
Running Mayavi tests.
............................................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 252 tests in 148.6 seconds

FAILED: there were 0 failures and 0 errors
File: /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mayavi/tests/test_cut_plane.py

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mayavi/tests/test_cut_plane.py", line 9, in <module>
    from . import datasets
ValueError: Attempted relative import in non-package
```

**Comment by 577528249** [comment]
Hi!guys,I get the problem too when running MRI example,Did you know how to fix this?

**Comment by vzickus** [comment]
Same failure when running tests on Mayavi 4.5.1
