### ISSUE TITLE
test_flow() raises error

### ISSUE THREAD

**Issue by pckroon** [enthought/mayavi#499]
Hi all,

first off, thanks for the hard work, the images are amazing!
However, I get an exception when trying to run mayavi.mlab.test_flow().
Here's my setup:
- Ubuntu 16.04
- Python 3.5
- Numpy 1.12.0
- Mayavi 4.5.0 (latest pypi version)
- I compiled VTK 7.1.1 from source:
```
cd build
cmake -DVTK_QT_VERSION:STRING=4 -DVTK_Group_Qt:BOOL=ON \
      -DBUILD_SHARED_LIBS:BOOL=ON -DVTK_PYTHON_VERSION:STRING=3.5 \
      -DVTK_Group_MPI:BOOL=ON -DVTK_USE_CXX11_FEATURES:BOOL=ON \
      -DVTK_WRAP_PYTHON:BOOL=ON -DVTK_WRAP_TCL:BOOL=ON \
      -DVTK_INSTALL_PYTHON_MODULE_DIR:STRING=lib/python3.5/dist-packages \
      -DBUILD_TESTING:BOOL=OFF -DCMAKE_BUILD_TYPE:STRING=Release ..
make -j 12 && make install && ldconfig
```
---------------------------------------------------
Running the following code
```python
from mayavi import mlab
mlab.test_flow()
```
produces
```
Generic Warning: In /root/src/VTK-7.1.1/Common/ExecutionModel/vtkAlgorithm.cxx, line 1808
vtkAlgorithm::SetUpdateExtent was deprecated for VTK 7.1 and will be removed in a future version.

Generic Warning: In /root/src/VTK-7.1.1/Common/ExecutionModel/vtkAlgorithm.cxx, line 1796
vtkAlgorithm::SetUpdateExtent was deprecated for VTK 7.1 and will be removed in a future version.

Generic Warning: In /root/src/VTK-7.1.1/Common/ExecutionModel/vtkStreamingDemandDrivenPipeline.cxx, line 1531
vtkStreamingDemandDrivenPipeline::SetUpdateExtent was deprecated for VTK 7.1 and will be removed in a future version.

Exception occurred in traits notification handler.
Please check the log file for details.
Exception occurred in traits notification handler for object: <mayavi.sources.array_source.ArraySource object at 0x7f2a0334e570>, trait: vector_data, old value: None, new value: [[[[ 0.40877515 -0.40877515  0.05      ]
<snip>
   [ 0.35006463 -0.35006463  0.05      ]]]]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "/usr/local/lib/python3.5/dist-packages/mayavi/sources/array_source.py", line 242, in _vector_data_changed
    img_data.point_data.vectors = numpy.reshape(data_t, (sz/3, 3))
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/fromnumeric.py", line 232, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/fromnumeric.py", line 67, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/fromnumeric.py", line 47, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
TypeError: 'float' object cannot be interpreted as an integer
ERROR: In /root/src/VTK-7.1.1/Filters/Core/vtkVectorNorm.cxx, line 189
vtkVectorNorm (0x46b11f0): No vector norm to compute!
```
and produces a window with a grey wiremesh like sphere. Some other test commands, such as test_quiver3d and test_points3d work as expected.

To investigate further, I ran the Mayavi testsuite. This gives 2 Failures, 10 Errors, and 7 Skipped. I've attached the full terminal output.
[mayavi_nose_output.txt](https://github.com/enthought/mayavi/files/902815/mayavi_nose_output.txt)
And for the TVTK testsuite: 6 failures, 3 errors and 4 skips.
[tvtk_nose_output.txt](https://github.com/enthought/mayavi/files/902829/tvtk_nose_output.txt)

My initial guess is the new Numpy version is to blame, but I'm not comfortable enough with Mayavi or VTK to trace this further. Let me know if I can provide more information!

**Comment by prabhuramachandran** [comment]
I've fixed this in #515.  Closing.
