### ISSUE TITLE
Can't activate mayavi extension in Jupyter notebook

### ISSUE THREAD

**Issue by sergsb** [enthought/mayavi#512]
Hi, 
I have a problem with `mayavi` and `Jupyter notebook`. When I try it to activate, it falls:

```
jupyter nbextension enable mayavi --py
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python2.7/dist-packages/notebook/nbextensions.py", line 969, in start
    super(NBExtensionApp, self).start()
  File "/usr/local/lib/python2.7/dist-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/usr/local/lib/python2.7/dist-packages/notebook/nbextensions.py", line 877, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "/usr/local/lib/python2.7/dist-packages/notebook/nbextensions.py", line 853, in toggle_nbextension_python
    logger=self.log)
  File "/usr/local/lib/python2.7/dist-packages/notebook/nbextensions.py", line 459, in enable_nbextension_python
    logger=logger)
  File "/usr/local/lib/python2.7/dist-packages/notebook/nbextensions.py", line 380, in _set_nbextension_state_python
    for nbext in nbexts]
KeyError: 'require'
```

My version of `mayavi ` is `4.5.0`,  `jupyter --version` is `4.2.1`

Without activation of this module I have troubles with 3D volume rendering, like[ in this post](https://stackoverflow.com/questions/40764116/mayavi-can-not-render-3d-volume)

It was proven on two different computers

**Comment by GinaVulpes** [comment]
With your command, I get the same error but this worked for me.
`jupyter nbextension install --py mayavi --user`

**Comment by prabhuramachandran** [comment]
Yes, I have a fix for this and will send a PR for this soon.
