### ISSUE TITLE
mayavi2 error in decoding

### ISSUE THREAD

**Issue by mestess** [enthought/mayavi#516]
Operating System:  Linux Fedora 24    kernel 4.11.6-101 (up to date)

Installed binary package from the distribution's repositories:  Mayavi-4.5.0.x86_64.rpm (without any error)

Run the command:

> mayavi2

from a bash shell command line, requiring execution of the (installed) script

> /usr/bin/mayavi2

Got the following, instead of the mayavi's window:

Traceback (most recent call last):
  File "/usr/bin/mayavi2", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3141, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3127, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3154, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 631, in _build_master
    ws = cls()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 624, in __init__
    self.add_entry(entry)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 680, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2122, in find_on_path
    path_item, entry, metadata, precedence=DEVELOP_DIST
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2521, in from_location
    py_version=py_version, platform=platform, **kw
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2838, in _reload_version
    md_version = _version_from_file(self._get_metadata(self.PKG_INFO))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2486, in _version_from_file
    line = next(iter(version_lines), '')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2654, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2013, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2008, in get_metadata
    metadata = f.read()
  File "/usr/lib64/python2.7/codecs.py", line 314, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf6 in position 203: invalid start byte

What happens?

**Comment by krishnaw14** [comment]
Hi,  you can run this from the command line before launching the Mayavi2 `application::

    `$ export LC_CTYPE="en_US.UTF-8"`

This should solve your problem.

**Comment by mestess** [comment]
Il giorno lun, 21/08/2017 alle 21.38 +0000, krishnaw14 ha scritto:
> Hi, you can run this from the command line before launching the
> Mayavi2 `application::
> `$ export LC_CTYPE="en_US.UTF-8"`
> This should solve your problem.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

No, it doesn't work yet.
