### ISSUE TITLE
Invalid Qt API 'pyqt5', valid values are: 'pyqt' or 'pyside'

### ISSUE THREAD

**Issue by ramsinghdayal** [enthought/mayavi#519]
_from mayavi import mlab_
### Changing backend to Qt for Mayavi
Traceback (most recent call last):
  File "<ipython-input-4-3f0e4b94a8ea>", line 1, in <module>
    from mayavi import mlab
  File "C:\Users\** \Anaconda3\lib\site-packages\mayavi\mlab.py", line 27, in <module>
    from mayavi.tools.camera import view, roll, yaw, pitch, move
  File "C:\Users\**\Anaconda3\lib\site-packages\mayavi\tools\camera.py", line 25, in <module>
    from .engine_manager import get_engine
  File "C:\Users\**\Anaconda3\lib\site-packages\mayavi\tools\engine_manager.py", line 12, in <module>
    from mayavi.preferences.api import preference_manager
  File "C:\Users\**\Anaconda3\lib\site-packages\mayavi\preferences\api.py", line 4, in <module>
    from .preference_manager import preference_manager
  File "C:\Users\**\Anaconda3\lib\site-packages\mayavi\preferences\preference_manager.py", line 29, in <module>
    from traitsui.api import View, Group, Item
  File "C:\Users\**\Anaconda3\lib\site-packages\traitsui\api.py", line 36, in <module>
    from .editors.api import ArrayEditor
  File "C:\Users\**\Anaconda3\lib\site-packages\traitsui\editors\__init__.py", line 23, in <module>
    from .api import ArrayEditor
  File "C:\Users\manoj_isro\Anaconda3\lib\site-packages\traitsui\editors\api.py", line 24, in <module>
    from .code_editor import CodeEditor
  File "C:\Users\manoj_isro\Anaconda3\lib\site-packages\traitsui\editors\code_editor.py", line 36, in <module>
    class ToolkitEditorFactory ( EditorFactory ):
  File "C:\Users\**\Anaconda3\lib\site-packages\traitsui\editors\code_editor.py", line 48, in ToolkitEditorFactory
    mark_color = Color( 0xECE9D8 )
  File "C:\Users\manoj_isro\Anaconda3\lib\site-packages\traits\traits.py", line 522, in __call__
    return self.maker_function( *args, **metadata )
  File "C:\Users\manoj_isro\Anaconda3\lib\site-packages\traits\traits.py", line 1236, in Color
    return ColorTrait( *args, **metadata )
  File "C:\Users\**\Anaconda3\lib\site-packages\traitsui\toolkit_traits.py", line 7, in ColorTrait
    return toolkit().color_trait( *args, **traits )
  File "C:\Users\manoj_isro\Anaconda3\lib\site-packages\traitsui\toolkit.py", line 161, in toolkit
    _toolkit = _import_toolkit(toolkit_name)
  File "C:\Users\**\Anaconda3\lib\site-packages\traitsui\toolkit.py", line 83, in _import_toolkit
    return __import__( name, globals=globals(), level=1 ).toolkit
  File "C:\Users\**\Anaconda3\lib\site-packages\traitsui\qt4\__init__.py", line 18, in <module>
    import pyface.qt
  File "C:\Users\**\Anaconda3\lib\site-packages\pyface\qt\__init__.py", line 44, in <module>
    % qt_api)
RuntimeError: Invalid Qt API 'pyqt5', valid values are: 'pyqt' or 'pyside'

Installed following .whl files

PyQt4-4.11.4-cp36-cp36m-win32.whl
PyQwt-5.2.1-cp36-cp36m-win32.whl
pyqtgraph-0.10.0-py2.py3-none-any.whl
PyQtdesignerplugins-1.1-py2.py3-none-any.whl
PySide-1.2.4-cp36-cp36m-win32.whl
mayavi-4.5.0+vtk71-cp36-cp36m-win32.whl

How can I correct error?

**Comment by prabhuramachandran** [comment]
This is not a Mayavi issue.  Only the version of pyface in master supports qt5 as does Mayavi.  As such this is not available on conda etc.

**Comment by corranwebster** [comment]
This is an issue with the environment you are running in, not Mayavi.  @ramsinghdayal need to set your `QT_API` environment variable to `pyqt` or `pyside` before importing Mayavi (preferably before starting Python).
