### ISSUE TITLE
tvtk_doc.main()  NotImplementedError

### ISSUE THREAD

**Issue by webMing** [enthought/mayavi#522]
>>> from tvtk.tools import tvtk_doc
>>> tvtk_doc.main()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/apple/anaconda/envs/python3.5/lib/python3.5/site-packages/mayavi-4.5.0-py3.5-macosx-10.6-x86_64.egg/tvtk/tools/tvtk_doc.py", line 403, in main
    s.configure_traits()
  File "/Users/apple/anaconda/envs/python3.5/lib/python3.5/site-packages/traits/has_traits.py", line 2156, in configure_traits
    kind, handler, id, scrollable, args )
  File "/Users/apple/anaconda/envs/python3.5/lib/python3.5/site-packages/traitsui/toolkit.py", line 291, in view_application
    raise NotImplementedError
NotImplementedError

my develop env:
python :3.5
mayavi :4.5.0
vtk:7.0.0
traits:4.5.0

anyone encounter this problem ？ and  how to  resolute ? thanks advance

**Comment by jonathanrocher** [comment]
What are your versions of traitsUI and pyface? Sometimes, this can happen if your TraitsUI backend is Null. Are you on a headless system by chance? Could you try setting your environment variable `ETS_TOOLKIT` to 'qt4'?

**Comment by webMing** [comment]
>>> import os
>>> os.environ['ETS_TOOLKIT'] = 'qt4'

Traceback (most recent call last):
  File "/Users/apple/anaconda/envs/python3.5/lib/python3.5/site-packages/pyface/qt/__init__.py", line 29, in <module>
    import PySide
ImportError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/apple/anaconda/envs/python3.5/lib/python3.5/site-packages/pyface/qt/__init__.py", line 34, in <module>
    import PyQt4
ImportError: No module named 'PyQt4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/apple/anaconda/envs/python3.5/lib/python3.5/site-packages/mayavi-4.5.0-py3.5-macosx-10.6-x86_64.egg/tvtk/tools/tvtk_doc.py", line 27, in <module>
    from traitsui.api import View, Group, Item, EnumEditor,\
  File "/Users/apple/anaconda/envs/python3.5/lib/python3.5/site-packages/traitsui/api.py", line 41, in <module>
    from .editors.api import (BooleanEditor, ButtonEditor,
  File "/Users/apple/anaconda/envs/python3.5/lib/python3.5/site-packages/traitsui/editors/__init__.py", line 27, in <module>
    from .api import (toolkit, BooleanEditor, ButtonEditor,
  File "/Users/apple/anaconda/envs/python3.5/lib/python3.5/site-packages/traitsui/editors/api.py", line 24, in <module>
    from .code_editor import CodeEditor
  File "/Users/apple/anaconda/envs/python3.5/lib/python3.5/site-packages/traitsui/editors/code_editor.py", line 36, in <module>
    class ToolkitEditorFactory ( EditorFactory ):
  File "/Users/apple/anaconda/envs/python3.5/lib/python3.5/site-packages/traitsui/editors/code_editor.py", line 48, in ToolkitEditorFactory
    mark_color = Color( 0xECE9D8 )
  File "/Users/apple/anaconda/envs/python3.5/lib/python3.5/site-packages/traits/traits.py", line 489, in __call__
    return self.maker_function( *args, **metadata )
  File "/Users/apple/anaconda/envs/python3.5/lib/python3.5/site-packages/traits/traits.py", line 1203, in Color
    return ColorTrait( *args, **metadata )
  File "/Users/apple/anaconda/envs/python3.5/lib/python3.5/site-packages/traitsui/toolkit_traits.py", line 7, in ColorTrait
    return toolkit().color_trait( *args, **traits )
  File "/Users/apple/anaconda/envs/python3.5/lib/python3.5/site-packages/traitsui/toolkit.py", line 152, in toolkit
    _toolkit = _import_toolkit(ETSConfig.toolkit)
  File "/Users/apple/anaconda/envs/python3.5/lib/python3.5/site-packages/traitsui/toolkit.py", line 83, in _import_toolkit
    return __import__( name, globals=globals(), level=1 ).toolkit
  File "/Users/apple/anaconda/envs/python3.5/lib/python3.5/site-packages/traitsui/qt4/__init__.py", line 18, in <module>
    import pyface.qt
  File "/Users/apple/anaconda/envs/python3.5/lib/python3.5/site-packages/pyface/qt/__init__.py", line 37, in <module>
    raise ImportError('Cannot import PySide or PyQt4')
ImportError: Cannot import PySide or PyQt4

pyface:5.1.0   
pyqt:5.6.0                  
qt:5.6.2  
traits:4.5.0              
traitsui :5.1.0

**Comment by webMing** [comment]
@jonathanrocher

**Comment by prabhuramachandran** [comment]
Qt5 is not supported with those versions of traits/traitsui.  You'll need those from git, IIRC.
