### ISSUE TITLE
Getting UnicodeDecodeError while trying to close mayavi app

### ISSUE THREAD

**Issue by ajsrk** [enthought/mayavi#576]
OS: Ubuntu 16.04
Python Version -3.6.2 (Anaconda Distribution)

After a lot of toil I was able to install Mayavi on python 3.6.2; however whenever I try to close the app by clicking on the close button, I get the following error and mayavi just freezes. Even if I close the terminal session that I used to start mayavi, the mayavi window remains open. Please find below the log that came up on the terminal - 

```
/root/anaconda3/lib/python3.6/site-packages/traits/etsconfig/etsconfig.py:429: UserWarning: Environment variable "HOME" not set, setting home directory to /tmp
  (environment_variable, parent_directory))
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/site-packages/pyface/ui/qt4/gui.py", line 189, in _dispatch
    self._callable(*self._args, **self._kw)
  File "/root/anaconda3/lib/python3.6/site-packages/pyface/workbench/workbench_window.py", line 180, in close
    self.destroy_views(self.views)
  File "/root/anaconda3/lib/python3.6/site-packages/pyface/workbench/workbench_window.py", line 339, in destroy_views
    view.destroy_control()
  File "/root/anaconda3/lib/python3.6/site-packages/pyface/workbench/traits_ui_view.py", line 73, in destroy_control
    self.ui.dispose()
  File "/root/anaconda3/lib/python3.6/site-packages/traitsui/ui.py", line 237, in dispose
    self.save_prefs()
  File "/root/anaconda3/lib/python3.6/site-packages/traitsui/ui.py", line 569, in save_prefs
    toolkit().save_window( self )
  File "/root/anaconda3/lib/python3.6/site-packages/traitsui/qt4/toolkit.py", line 317, in save_window
    helper.save_window(ui)
  File "/root/anaconda3/lib/python3.6/site-packages/traitsui/qt4/helper.py", line 142, in save_window
    ui.save_prefs( (geom.x(), geom.y(), geom.width(), geom.height()) )
  File "/root/anaconda3/lib/python3.6/site-packages/traitsui/ui.py", line 576, in save_prefs
    db[ id ] = self.get_prefs( prefs )
  File "/root/anaconda3/lib/python3.6/site-packages/traitsui/ui.py", line 597, in get_prefs
    prefs = editor.save_prefs()
  File "/root/anaconda3/lib/python3.6/site-packages/traitsui/qt4/tree_editor.py", line 1667, in save_prefs
    prefs['column_state'] = str(header.saveState())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 3: invalid start byte
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/site-packages/pyface/ui/qt4/workbench/workbench_window_layout.py", line 625, in sizeHint
    sh = self.centralWidget().sizeHint()
AttributeError: 'NoneType' object has no attribute 'sizeHint'
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/site-packages/pyface/ui/qt4/workbench/workbench_window_layout.py", line 625, in sizeHint
    sh = self.centralWidget().sizeHint()
AttributeError: 'NoneType' object has no attribute 'sizeHint'
```
This is what my bash_profile looks like -
```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US:en
export ETS_TOOLKIT=qt4
export LC_CTYPE=en_US.UTF-8
```
Please let me know if any other details are required.

**Comment by ajsrk** [comment]
I zeroed in to the line causing the issue. 
I went to ~/anaconda3/lib/python3.5/site-packages/traitsui/qt4/tree_editor.py and edited line number 1667 from
`prefs['column_state'] = str(header.saveState())`
to 
`prefs['column_state'] = header.saveState().data().decode('utf-16')`
And this issue is gone. I'm not sure if this is the right way to go about it. I was hoping the fix would require me to do OS level config, rather than changing the code. Any pointers?

**Comment by rkern** [comment]
The code is just buggy for Python 3, so yes, it does need to be changed. I suspect that the `.data()` ought not to be `decode()`d, though, but left as a `bytes` string.

**Comment by rkern** [comment]
Try this branch: https://github.com/enthought/traitsui/tree/fix/python3-savestate-data

**Comment by ajsrk** [comment]
This works. Thanks a lot !! 
Is there a release scheduled anytime soon? I'd just like to know if I can wait around for it to get to Pypi or if I need to build my own conda package
