### ISSUE TITLE
Saving to png with vtk8 fails

### ISSUE THREAD

**Issue by JannickWeisshaupt** [enthought/mayavi#619]
With mayavi 4.5.0 and vtk8 saving a mayavi scene to png fails with:
`Traceback (most recent call last):
  File "/home/jannick/.local/lib/python3.4/site-packages/pyface/ui/qt4/action/action_item.py", line 361, in _qt4_on_triggered
    action.perform(action_event)
  File "/home/jannick/.local/lib/python3.4/site-packages/pyface/action/action.py", line 104, in perform
    self.on_perform()
  File "/home/jannick/.local/lib/python3.4/site-packages/tvtk/pyface/ui/qt4/decorated_scene.py", line 155, in _save_snapshot
    self.save(path)
  File "/home/jannick/.local/lib/python3.4/site-packages/tvtk/pyface/tvtk_scene.py", line 418, in save
    meth(file_name, **kw_args)
  File "/home/jannick/.local/lib/python3.4/site-packages/tvtk/pyface/tvtk_scene.py", line 466, in save_png
    w2if.magnification = self.magnification
traits.trait_errors.TraitError: Cannot set the undefined 'magnification' attribute of a 'WindowToImageFilter' object.
`

**Comment by prabhuramachandran** [comment]
Thanks but long since fixed in master, see #597.
