### ISSUE TITLE
What should I do to run the simplest demo correctly??????

### ISSUE THREAD

**Issue by yaaaang** [enthought/mayavi#632]
I consider myself a semi-pro to configure how to use a python package properly, until I entoured mayavi yesterday. After two days of struggling I cannot even run the demo correctly provided on the official website of mayavi.
I followed the installation instruction on the website, both ways: manually and download the big canopy app. None of them worked.
I hope someone could offer me a **clear** requirements of the version of the python, as well as the **precious** steps of how to install mayavi.

I tried two examples, the first one could show the results, with lots of errors and the second one cannot even show anything.

Here is the basic info:
MacOS 10.13.4
python 3.5.4(by the way, I downgraded from 3.6.5, just to use mayavi)
I installed VTK, wxpython and mayavi via pip3, so the versions are the latest.

Anyway, here is the code1:
````
from numpy import pi, sin, cos, mgrid
dphi, dtheta = pi/250.0, pi/250.0
[phi,theta] = mgrid[0:pi+dphi*1.5:dphi,0:2*pi+dtheta*1.5:dtheta]
m0 = 4; m1 = 3; m2 = 2; m3 = 3; m4 = 6; m5 = 2; m6 = 6; m7 = 4;
r = sin(m0*phi)**m1 + cos(m2*phi)**m3 + sin(m4*theta)**m5 + cos(m6*theta)**m7
x = r*sin(phi)*cos(theta)
y = r*cos(phi)
z = r*sin(phi)*sin(theta)

# View it.
from mayavi import mlab
s = mlab.mesh(x, y, z)
mlab.show()
````
code2:

````
import numpy as np
from mayavi import mlab

x, y, z = np.ogrid[-10:10:20j, -10:10:20j, -10:10:20j]
s = np.sin(x*y*z)/(x*y*z)

src = mlab.pipeline.scalar_field(s)
mlab.pipeline.iso_surface(src, contours=[s.min()+0.1*s.ptp(), ], opacity=0.3)
mlab.pipeline.iso_surface(src, contours=[s.max()-0.1*s.ptp(), ],)

mlab.show()
````

And here is the errors from code1:

````
/usr/local/bin/python3 /Users/zhangyangyang/Library/Preferences/PyCharmCE2018.1/scratches/scratch_3.py
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pyface/wx/drag_and_drop.py:94: wxPyDeprecationWarning: Call to deprecated item. Use wx.DataFormat instead.
  PythonObject = wx.CustomDataFormat('PythonObject')
06:36:47 PM: Debug: Adding duplicate image handler for 'Windows bitmap file'
06:36:47 PM: Debug: Adding duplicate image handler for 'Windows bitmap file'
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pyface/ui/wx/clipboard.py:24: wxPyDeprecationWarning: Call to deprecated item. Use wx.DataFormat instead.
  PythonObjectFormat = wx.CustomDataFormat('PythonObject')
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pyface/ui/wx/action/action_item.py:367: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
  self.control_id, label, bmp, wx.NullBitmap, kind, tooltip, longtip, None
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pyface/ui/wx/action/action_item.py:385: wxPyDeprecationWarning: Call to deprecated item __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_TOOL(parent, self.control_id, self._on_tool)
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tvtk/pyface/ui/wx/scene.py:570: wxPyDeprecationWarning: Call to deprecated item __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_CHAR(window, None) # Remove the default handler.
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tvtk/pyface/ui/wx/scene.py:571: wxPyDeprecationWarning: Call to deprecated item __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_CHAR(window, self.OnKeyDown)
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tvtk/pyface/ui/wx/scene.py:572: wxPyDeprecationWarning: Call to deprecated item __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_KEY_UP(window, None) # Remove the default handler.
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tvtk/pyface/ui/wx/scene.py:573: wxPyDeprecationWarning: Call to deprecated item __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_KEY_UP(window, self.OnKeyUp)
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tvtk/pyface/ui/wx/scene.py:574: wxPyDeprecationWarning: Call to deprecated item __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_PAINT(window, None) # Remove the default handler.
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tvtk/pyface/ui/wx/scene.py:575: wxPyDeprecationWarning: Call to deprecated item __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_PAINT(window, self.OnPaint)
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tvtk/pyface/ui/wx/scene.py:576: wxPyDeprecationWarning: Call to deprecated item __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_SIZE(window, None) # Remove the default handler.
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tvtk/pyface/ui/wx/scene.py:577: wxPyDeprecationWarning: Call to deprecated item __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_SIZE(window, self.OnSize)
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tvtk/pyface/ui/wx/scene.py:582: wxPyDeprecationWarning: Call to deprecated item __call__. Use :meth:`EvtHandler.Bind` instead.
  evt(window, None)
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tvtk/pyface/ui/wx/scene.py:583: wxPyDeprecationWarning: Call to deprecated item __call__. Use :meth:`EvtHandler.Bind` instead.
  evt(window, self.OnButtonDown)
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tvtk/pyface/ui/wx/scene.py:586: wxPyDeprecationWarning: Call to deprecated item __call__. Use :meth:`EvtHandler.Bind` instead.
  evt(window, None)
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tvtk/pyface/ui/wx/scene.py:587: wxPyDeprecationWarning: Call to deprecated item __call__. Use :meth:`EvtHandler.Bind` instead.
  evt(window, self.OnButtonUp)
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tvtk/pyface/ui/wx/scene.py:659: wxPyDeprecationWarning: Call to deprecated item __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_IDLE(window, _do_idle)
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tvtk/array_handler.py:268: FutureWarning: Conversion of the second argument of issubdtype from `complex` to `np.complexfloating` is deprecated. In future, it will be treated as `np.complex128 == np.dtype(complex).type`.
  assert not numpy.issubdtype(z.dtype, complex), \
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tvtk/pyface/ui/wx/scene.py:530: wxPyDeprecationWarning: Call to deprecated item __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_PAINT(self._vtk_control, None) # Remove the default handler.
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tvtk/pyface/ui/wx/scene.py:531: wxPyDeprecationWarning: Call to deprecated item __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_PAINT(self._vtk_control, self._vtk_control.OnPaint)
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tvtk/pyface/ui/wx/scene.py:655: wxPyDeprecationWarning: Call to deprecated item __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_IDLE(window, None)
````

and errors from code2:

````
/usr/local/bin/python3 "/Users/zhangyangyang/Library/Mobile Documents/com~apple~CloudDocs/MPF/magnetic_field/mag/test.py"
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pyface/wx/drag_and_drop.py:94: wxPyDeprecationWarning: Call to deprecated item. Use wx.DataFormat instead.
  PythonObject = wx.CustomDataFormat('PythonObject')
06:42:18 PM: Debug: Adding duplicate image handler for 'Windows bitmap file'
06:42:18 PM: Debug: Adding duplicate image handler for 'Windows bitmap file'
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pyface/ui/wx/clipboard.py:24: wxPyDeprecationWarning: Call to deprecated item. Use wx.DataFormat instead.
  PythonObjectFormat = wx.CustomDataFormat('PythonObject')
Exception occurred in traits notification handler for object: <mayavi.sources.array_source.ArraySource object at 0x1305eebf8>, trait: scalar_data, old value: None, new value: [[[ 8.26879541e-04  6.46718926e-04 -1.01835204e-03 ... -1.01835204e-03
Exception occurred in traits notification handler.
    6.46718926e-04  8.26879541e-04]
Please check the log file for details.
  [ 6.46718926e-04  6.55152455e-04  6.62703364e-04 ...  6.62703364e-04
    6.55152455e-04  6.46718926e-04]
  [-1.01835204e-03  6.62703364e-04  1.51396033e-03 ...  1.51396033e-03
    6.62703364e-04 -1.01835204e-03]
  ...
  [-1.01835204e-03  6.62703364e-04  1.51396033e-03 ...  1.51396033e-03
    6.62703364e-04 -1.01835204e-03]
  [ 6.46718926e-04  6.55152455e-04  6.62703364e-04 ...  6.62703364e-04
    6.55152455e-04  6.46718926e-04]
  [ 8.26879541e-04  6.46718926e-04 -1.01835204e-03 ... -1.01835204e-03
    6.46718926e-04  8.26879541e-04]]

 [[ 6.46718926e-04  6.55152455e-04  6.62703364e-04 ...  6.62703364e-04
    6.55152455e-04  6.46718926e-04]
  [ 6.55152455e-04  2.85884154e-06 -8.35370039e-04 ... -8.35370039e-04
    2.85884154e-06  6.55152455e-04]
  [ 6.62703364e-04 -8.35370039e-04 -1.79246050e-03 ... -1.79246050e-03
   -8.35370039e-04  6.62703364e-04]
  ...
  [ 6.62703364e-04 -8.35370039e-04 -1.79246050e-03 ... -1.79246050e-03
   -8.35370039e-04  6.62703364e-04]
  [ 6.55152455e-04  2.85884154e-06 -8.35370039e-04 ... -8.35370039e-04
    2.85884154e-06  6.55152455e-04]
  [ 6.46718926e-04  6.55152455e-04  6.62703364e-04 ...  6.62703364e-04
    6.55152455e-04  6.46718926e-04]]

 [[-1.01835204e-03  6.62703364e-04  1.51396033e-03 ...  1.51396033e-03
    6.62703364e-04 -1.01835204e-03]
  [ 6.62703364e-04 -8.35370039e-04 -1.79246050e-03 ... -1.79246050e-03
   -8.35370039e-04  6.62703364e-04]
  [ 1.51396033e-03 -1.79246050e-03  1.87581421e-03 ...  1.87581421e-03
   -1.79246050e-03  1.51396033e-03]
  ...
  [ 1.51396033e-03 -1.79246050e-03  1.87581421e-03 ...  1.87581421e-03
   -1.79246050e-03  1.51396033e-03]
  [ 6.62703364e-04 -8.35370039e-04 -1.79246050e-03 ... -1.79246050e-03
   -8.35370039e-04  6.62703364e-04]
  [-1.01835204e-03  6.62703364e-04  1.51396033e-03 ...  1.51396033e-03
    6.62703364e-04 -1.01835204e-03]]

 ...

 [[-1.01835204e-03  6.62703364e-04  1.51396033e-03 ...  1.51396033e-03
    6.62703364e-04 -1.01835204e-03]
  [ 6.62703364e-04 -8.35370039e-04 -1.79246050e-03 ... -1.79246050e-03
   -8.35370039e-04  6.62703364e-04]
  [ 1.51396033e-03 -1.79246050e-03  1.87581421e-03 ...  1.87581421e-03
   -1.79246050e-03  1.51396033e-03]
  ...
  [ 1.51396033e-03 -1.79246050e-03  1.87581421e-03 ...  1.87581421e-03
   -1.79246050e-03  1.51396033e-03]
  [ 6.62703364e-04 -8.35370039e-04 -1.79246050e-03 ... -1.79246050e-03
   -8.35370039e-04  6.62703364e-04]
  [-1.01835204e-03  6.62703364e-04  1.51396033e-03 ...  1.51396033e-03
    6.62703364e-04 -1.01835204e-03]]

 [[ 6.46718926e-04  6.55152455e-04  6.62703364e-04 ...  6.62703364e-04
    6.55152455e-04  6.46718926e-04]
  [ 6.55152455e-04  2.85884154e-06 -8.35370039e-04 ... -8.35370039e-04
    2.85884154e-06  6.55152455e-04]
  [ 6.62703364e-04 -8.35370039e-04 -1.79246050e-03 ... -1.79246050e-03
   -8.35370039e-04  6.62703364e-04]
  ...
  [ 6.62703364e-04 -8.35370039e-04 -1.79246050e-03 ... -1.79246050e-03
   -8.35370039e-04  6.62703364e-04]
  [ 6.55152455e-04  2.85884154e-06 -8.35370039e-04 ... -8.35370039e-04
    2.85884154e-06  6.55152455e-04]
  [ 6.46718926e-04  6.55152455e-04  6.62703364e-04 ...  6.62703364e-04
    6.55152455e-04  6.46718926e-04]]

 [[ 8.26879541e-04  6.46718926e-04 -1.01835204e-03 ... -1.01835204e-03
    6.46718926e-04  8.26879541e-04]
  [ 6.46718926e-04  6.55152455e-04  6.62703364e-04 ...  6.62703364e-04
    6.55152455e-04  6.46718926e-04]
  [-1.01835204e-03  6.62703364e-04  1.51396033e-03 ...  1.51396033e-03
    6.62703364e-04 -1.01835204e-03]
  ...
  [-1.01835204e-03  6.62703364e-04  1.51396033e-03 ...  1.51396033e-03
    6.62703364e-04 -1.01835204e-03]
  [ 6.46718926e-04  6.55152455e-04  6.62703364e-04 ...  6.62703364e-04
    6.55152455e-04  6.46718926e-04]
  [ 8.26879541e-04  6.46718926e-04 -1.01835204e-03 ... -1.01835204e-03
    6.46718926e-04  8.26879541e-04]]]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mayavi/sources/array_source.py", line 195, in _scalar_data_changed
    self.change_information_filter.set_update_extent(update_extent)
AttributeError: 'ImageChangeInformation' object has no attribute 'set_update_extent'
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pyface/ui/wx/action/action_item.py:367: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
  self.control_id, label, bmp, wx.NullBitmap, kind, tooltip, longtip, None
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pyface/ui/wx/action/action_item.py:385: wxPyDeprecationWarning: Call to deprecated item __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_TOOL(parent, self.control_id, self._on_tool)
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tvtk/pyface/ui/wx/scene.py:570: wxPyDeprecationWarning: Call to deprecated item __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_CHAR(window, None) # Remove the default handler.
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tvtk/pyface/ui/wx/scene.py:571: wxPyDeprecationWarning: Call to deprecated item __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_CHAR(window, self.OnKeyDown)
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tvtk/pyface/ui/wx/scene.py:572: wxPyDeprecationWarning: Call to deprecated item __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_KEY_UP(window, None) # Remove the default handler.
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tvtk/pyface/ui/wx/scene.py:573: wxPyDeprecationWarning: Call to deprecated item __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_KEY_UP(window, self.OnKeyUp)
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tvtk/pyface/ui/wx/scene.py:574: wxPyDeprecationWarning: Call to deprecated item __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_PAINT(window, None) # Remove the default handler.
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tvtk/pyface/ui/wx/scene.py:575: wxPyDeprecationWarning: Call to deprecated item __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_PAINT(window, self.OnPaint)
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tvtk/pyface/ui/wx/scene.py:576: wxPyDeprecationWarning: Call to deprecated item __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_SIZE(window, None) # Remove the default handler.
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tvtk/pyface/ui/wx/scene.py:577: wxPyDeprecationWarning: Call to deprecated item __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_SIZE(window, self.OnSize)
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tvtk/pyface/ui/wx/scene.py:582: wxPyDeprecationWarning: Call to deprecated item __call__. Use :meth:`EvtHandler.Bind` instead.
  evt(window, None)
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tvtk/pyface/ui/wx/scene.py:583: wxPyDeprecationWarning: Call to deprecated item __call__. Use :meth:`EvtHandler.Bind` instead.
  evt(window, self.OnButtonDown)
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tvtk/pyface/ui/wx/scene.py:586: wxPyDeprecationWarning: Call to deprecated item __call__. Use :meth:`EvtHandler.Bind` instead.
  evt(window, None)
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tvtk/pyface/ui/wx/scene.py:587: wxPyDeprecationWarning: Call to deprecated item __call__. Use :meth:`EvtHandler.Bind` instead.
  evt(window, self.OnButtonUp)
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tvtk/pyface/ui/wx/scene.py:659: wxPyDeprecationWarning: Call to deprecated item __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_IDLE(window, _do_idle)
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tvtk/array_handler.py:268: FutureWarning: Conversion of the second argument of issubdtype from `complex` to `np.complexfloating` is deprecated. In future, it will be treated as `np.complex128 == np.dtype(complex).type`.
  assert not numpy.issubdtype(z.dtype, complex), \
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tvtk/pyface/ui/wx/scene.py:530: wxPyDeprecationWarning: Call to deprecated item __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_PAINT(self._vtk_control, None) # Remove the default handler.
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tvtk/pyface/ui/wx/scene.py:531: wxPyDeprecationWarning: Call to deprecated item __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_PAINT(self._vtk_control, self._vtk_control.OnPaint)
Cannot contour: No scalars in input data!
Cannot contour: No scalars in input data!
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tvtk/pyface/ui/wx/scene.py:655: wxPyDeprecationWarning: Call to deprecated item __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_IDLE(window, None)

Process finished with exit code 0
````

**Comment by yaaaang** [comment]
@prabhuramachandran Thanks for your help! Now everything works. Just one thing, it seems to require _pygments_ package.
Good day!

**Comment by prabhuramachandran** [comment]
OK, good to know.  I guess the requirement of pygments would be for the documentation and sphinx.  Were these fetched automatically or did it require a manual installation?  Anyway, am closing this ticket for now.
