### ISSUE TITLE
Problem with mlab.flow command

### ISSUE THREAD

**Issue by noctuelle** [enthought/mayavi#637]
Hello,

I already used mayavi a few years ago using its great command *flow* to plot field lines. Recently I tried to install it on my mac (mac OS 10.12.6), but I am running into some problems.
I am using Python 2.7.15 and IPython 5.5.0. I installed mayavi through *pip install*.

This is the sequence of commands I use:

`from mayavi import mlab`
`mlab.test_flow()`

and below you can see what I get.
Before writing here, I found some info at #499 which points to #515, but it did not help me.

Please, let me know if you need further information... I am not an expert at all.

Best regards.

################

/usr/local/lib/python2.7/site-packages/tvtk/array_handler.py:268: FutureWarning: Conversion of the second argument of issubdtype from `complex` to `np.complexfloating` is deprecated. In future, it will be treated as `np.complex128 == np.dtype(complex).type`.
  assert not numpy.issubdtype(z.dtype, complex), \
Exception occurred in traits notification handler.
Please check the log file for details.
Exception occurred in traits notification handler for object: <mayavi.sources.array_source.ArraySource object at 0x114959410>, trait: vector_data, old value: None, new value: [[[[ 0.40877515 -0.40877515  0.05      ]
   [ 0.40624096 -0.40624096  0.05      ]
   [ 0.39863276 -0.39863276  0.05      ]
   ...
   [-0.2424187   0.2424187   0.05      ]
   [-0.29817489  0.29817489  0.05      ]
   [-0.35006463  0.35006463  0.05      ]]

  [[ 0.4735834  -0.4991825   0.05      ]
   [ 0.47124034 -0.49671279  0.05      ]
   [ 0.46419649 -0.4892882   0.05      ]
   ...
   [-0.16921887  0.17836584  0.05      ]
   [-0.22826457  0.2406032   0.05      ]
   [-0.28419721  0.29955922  0.05      ]]

  [[ 0.52199669 -0.58165346  0.05      ]
   [ 0.51988813 -0.57930392  0.05      ]
   [ 0.51353889 -0.57222904  0.05      ]
   ...
   [-0.10035359  0.11182257  0.05      ]
   [-0.16144727  0.17989839  0.05      ]
   [-0.22018737  0.24535165  0.05      ]]

  ...

  [[-0.52199669 -0.58165346  0.05      ]
   [-0.51988813 -0.57930392  0.05      ]
   [-0.51353889 -0.57222904  0.05      ]
   ...
   [ 0.10035359  0.11182257  0.05      ]
   [ 0.16144727  0.17989839  0.05      ]
   [ 0.22018737  0.24535165  0.05      ]]

  [[-0.4735834  -0.4991825   0.05      ]
   [-0.47124034 -0.49671279  0.05      ]
   [-0.46419649 -0.4892882   0.05      ]
   ...
   [ 0.16921887  0.17836584  0.05      ]
   [ 0.22826457  0.2406032   0.05      ]
   [ 0.28419721  0.29955922  0.05      ]]

  [[-0.40877515 -0.40877515  0.05      ]
   [-0.40624096 -0.40624096  0.05      ]
   [-0.39863276 -0.39863276  0.05      ]
   ...
   [ 0.2424187   0.2424187   0.05      ]
   [ 0.29817489  0.29817489  0.05      ]
   [ 0.35006463  0.35006463  0.05      ]]]

 [[[ 0.4991825  -0.4735834   0.05      ]
   [ 0.49671279 -0.47124034  0.05      ]
   [ 0.4892882  -0.46419649  0.05      ]
   ...
   [-0.17836584  0.16921887  0.05      ]
   [-0.2406032   0.22826457  0.05      ]
   [-0.29955922  0.28419721  0.05      ]]

  [[ 0.55604577 -0.55604577  0.05      ]
   [ 0.55382482 -0.55382482  0.05      ]
   [ 0.54713645 -0.54713645  0.05      ]
   ...
   [-0.10242953  0.10242953  0.05      ]
   [-0.16731155  0.16731155  0.05      ]
   [-0.22974321  0.22974321  0.05      ]]

  [[ 0.59496855 -0.62896675  0.05      ]
   [ 0.5930386  -0.62692652  0.05      ]
   [ 0.58721339 -0.62076844  0.05      ]
   ...
   [-0.03217691  0.03401559  0.05      ]
   [-0.09839372  0.10401621  0.05      ]
   [-0.16298841  0.17230203  0.05      ]]

  ...

  [[-0.59496855 -0.62896675  0.05      ]
   [-0.5930386  -0.62692652  0.05      ]
   [-0.58721339 -0.62076844  0.05      ]
   ...
   [ 0.03217691  0.03401559  0.05      ]
   [ 0.09839372  0.10401621  0.05      ]
   [ 0.16298841  0.17230203  0.05      ]]

  [[-0.55604577 -0.55604577  0.05      ]
   [-0.55382482 -0.55382482  0.05      ]
   [-0.54713645 -0.54713645  0.05      ]
   ...
   [ 0.10242953  0.10242953  0.05      ]
   [ 0.16731155  0.16731155  0.05      ]
   [ 0.22974321  0.22974321  0.05      ]]

  [[-0.4991825  -0.4735834   0.05      ]
   [-0.49671279 -0.47124034  0.05      ]
   [-0.4892882  -0.46419649  0.05      ]
   ...
   [ 0.17836584  0.16921887  0.05      ]
   [ 0.2406032   0.22826457  0.05      ]
   [ 0.29955922  0.28419721  0.05      ]]]

 [[[ 0.58165346 -0.52199669  0.05      ]
   [ 0.57930392 -0.51988813  0.05      ]
   [ 0.57222904 -0.51353889  0.05      ]
   ...
   [-0.11182257  0.10035359  0.05      ]
   [-0.17989839  0.16144727  0.05      ]
   [-0.24535165  0.22018737  0.05      ]]

  [[ 0.62896675 -0.59496855  0.05      ]
   [ 0.62692652 -0.5930386   0.05      ]
   [ 0.62076844 -0.58721339  0.05      ]
   ...
   [-0.03401559  0.03217691  0.05      ]
   [-0.10401621  0.09839372  0.05      ]
   [-0.17230203  0.16298841  0.05      ]]

  [[ 0.65692409 -0.65692409  0.05      ]
   [ 0.6552337  -0.6552337   0.05      ]
   [ 0.65011437 -0.65011437  0.05      ]
   ...
   [ 0.03677009 -0.03677009  0.05      ]
   [-0.03378622  0.03378622  0.05      ]
   [-0.10352341  0.10352341  0.05      ]]

  ...

  [[-0.65692409 -0.65692409  0.05      ]
   [-0.6552337  -0.6552337   0.05      ]
   [-0.65011437 -0.65011437  0.05      ]
   ...
   [-0.03677009 -0.03677009  0.05      ]
   [ 0.03378622  0.03378622  0.05      ]
   [ 0.10352341  0.10352341  0.05      ]]

  [[-0.62896675 -0.59496855  0.05      ]
   [-0.62692652 -0.5930386   0.05      ]
   [-0.62076844 -0.58721339  0.05      ]
   ...
   [ 0.03401559  0.03217691  0.05      ]
   [ 0.10401621  0.09839372  0.05      ]
   [ 0.17230203  0.16298841  0.05      ]]

  [[-0.58165346 -0.52199669  0.05      ]
   [-0.57930392 -0.51988813  0.05      ]
   [-0.57222904 -0.51353889  0.05      ]
   ...
   [ 0.11182257  0.10035359  0.05      ]
   [ 0.17989839  0.16144727  0.05      ]
   [ 0.24535165  0.22018737  0.05      ]]]

 ...

 [[[ 0.58165346  0.52199669  0.05      ]
   [ 0.57930392  0.51988813  0.05      ]
   [ 0.57222904  0.51353889  0.05      ]
   ...
   [-0.11182257 -0.10035359  0.05      ]
   [-0.17989839 -0.16144727  0.05      ]
   [-0.24535165 -0.22018737  0.05      ]]

  [[ 0.62896675  0.59496855  0.05      ]
   [ 0.62692652  0.5930386   0.05      ]
   [ 0.62076844  0.58721339  0.05      ]
   ...
   [-0.03401559 -0.03217691  0.05      ]
   [-0.10401621 -0.09839372  0.05      ]
   [-0.17230203 -0.16298841  0.05      ]]

  [[ 0.65692409  0.65692409  0.05      ]
   [ 0.6552337   0.6552337   0.05      ]
   [ 0.65011437  0.65011437  0.05      ]
   ...
   [ 0.03677009  0.03677009  0.05      ]
   [-0.03378622 -0.03378622  0.05      ]
   [-0.10352341 -0.10352341  0.05      ]]

  ...

  [[-0.65692409  0.65692409  0.05      ]
   [-0.6552337   0.6552337   0.05      ]
   [-0.65011437  0.65011437  0.05      ]
   ...
   [-0.03677009  0.03677009  0.05      ]
   [ 0.03378622 -0.03378622  0.05      ]
   [ 0.10352341 -0.10352341  0.05      ]]

  [[-0.62896675  0.59496855  0.05      ]
   [-0.62692652  0.5930386   0.05      ]
   [-0.62076844  0.58721339  0.05      ]
   ...
   [ 0.03401559 -0.03217691  0.05      ]
   [ 0.10401621 -0.09839372  0.05      ]
   [ 0.17230203 -0.16298841  0.05      ]]

  [[-0.58165346  0.52199669  0.05      ]
   [-0.57930392  0.51988813  0.05      ]
   [-0.57222904  0.51353889  0.05      ]
   ...
   [ 0.11182257 -0.10035359  0.05      ]
   [ 0.17989839 -0.16144727  0.05      ]
   [ 0.24535165 -0.22018737  0.05      ]]]

 [[[ 0.4991825   0.4735834   0.05      ]
   [ 0.49671279  0.47124034  0.05      ]
   [ 0.4892882   0.46419649  0.05      ]
   ...
   [-0.17836584 -0.16921887  0.05      ]
   [-0.2406032  -0.22826457  0.05      ]
   [-0.29955922 -0.28419721  0.05      ]]

  [[ 0.55604577  0.55604577  0.05      ]
   [ 0.55382482  0.55382482  0.05      ]
   [ 0.54713645  0.54713645  0.05      ]
   ...
   [-0.10242953 -0.10242953  0.05      ]
   [-0.16731155 -0.16731155  0.05      ]
   [-0.22974321 -0.22974321  0.05      ]]

  [[ 0.59496855  0.62896675  0.05      ]
   [ 0.5930386   0.62692652  0.05      ]
   [ 0.58721339  0.62076844  0.05      ]
   ...
   [-0.03217691 -0.03401559  0.05      ]
   [-0.09839372 -0.10401621  0.05      ]
   [-0.16298841 -0.17230203  0.05      ]]

  ...

  [[-0.59496855  0.62896675  0.05      ]
   [-0.5930386   0.62692652  0.05      ]
   [-0.58721339  0.62076844  0.05      ]
   ...
   [ 0.03217691 -0.03401559  0.05      ]
   [ 0.09839372 -0.10401621  0.05      ]
   [ 0.16298841 -0.17230203  0.05      ]]

  [[-0.55604577  0.55604577  0.05      ]
   [-0.55382482  0.55382482  0.05      ]
   [-0.54713645  0.54713645  0.05      ]
   ...
   [ 0.10242953 -0.10242953  0.05      ]
   [ 0.16731155 -0.16731155  0.05      ]
   [ 0.22974321 -0.22974321  0.05      ]]

  [[-0.4991825   0.4735834   0.05      ]
   [-0.49671279  0.47124034  0.05      ]
   [-0.4892882   0.46419649  0.05      ]
   ...
   [ 0.17836584 -0.16921887  0.05      ]
   [ 0.2406032  -0.22826457  0.05      ]
   [ 0.29955922 -0.28419721  0.05      ]]]

 [[[ 0.40877515  0.40877515  0.05      ]
   [ 0.40624096  0.40624096  0.05      ]
   [ 0.39863276  0.39863276  0.05      ]
   ...
   [-0.2424187  -0.2424187   0.05      ]
   [-0.29817489 -0.29817489  0.05      ]
   [-0.35006463 -0.35006463  0.05      ]]

  [[ 0.4735834   0.4991825   0.05      ]
   [ 0.47124034  0.49671279  0.05      ]
   [ 0.46419649  0.4892882   0.05      ]
   ...
   [-0.16921887 -0.17836584  0.05      ]
   [-0.22826457 -0.2406032   0.05      ]
   [-0.28419721 -0.29955922  0.05      ]]

  [[ 0.52199669  0.58165346  0.05      ]
   [ 0.51988813  0.57930392  0.05      ]
   [ 0.51353889  0.57222904  0.05      ]
   ...
   [-0.10035359 -0.11182257  0.05      ]
   [-0.16144727 -0.17989839  0.05      ]
   [-0.22018737 -0.24535165  0.05      ]]

  ...

  [[-0.52199669  0.58165346  0.05      ]
   [-0.51988813  0.57930392  0.05      ]
   [-0.51353889  0.57222904  0.05      ]
   ...
   [ 0.10035359 -0.11182257  0.05      ]
   [ 0.16144727 -0.17989839  0.05      ]
   [ 0.22018737 -0.24535165  0.05      ]]

  [[-0.4735834   0.4991825   0.05      ]
   [-0.47124034  0.49671279  0.05      ]
   [-0.46419649  0.4892882   0.05      ]
   ...
   [ 0.16921887 -0.17836584  0.05      ]
   [ 0.22826457 -0.2406032   0.05      ]
   [ 0.28419721 -0.29955922  0.05      ]]

  [[-0.40877515  0.40877515  0.05      ]
   [-0.40624096  0.40624096  0.05      ]
   [-0.39863276  0.39863276  0.05      ]
   ...
   [ 0.2424187  -0.2424187   0.05      ]
   [ 0.29817489 -0.29817489  0.05      ]
   [ 0.35006463 -0.35006463  0.05      ]]]]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "/usr/local/lib/python2.7/site-packages/mayavi/sources/array_source.py", line 236, in _vector_data_changed
    self.change_information_filter.set_update_extent(update_extent)
AttributeError: 'ImageChangeInformation' object has no attribute 'set_update_extent'
ERROR: In /tmp/vtk-20180420-28226-19khozd/VTK-8.1.0/Filters/Core/vtkVectorNorm.cxx, line 189
vtkVectorNorm (0x7fd6f7fb0f50): No vector norm to compute!

Out[2]: <mayavi.modules.streamline.Streamline at 0x114a1cfb0>

#########################

**Comment by noctuelle** [comment]
Thank you very much for the hint!
First I uninstalled the previous version with `pip uninstall mayavi` then I downloaded the mayavi-master folder and ran `python setup.py install` and... everything works!

Thank you again!
