### ISSUE TITLE
Pip install requires numpy

### ISSUE THREAD

**Issue by chiranthsiddappa** [enthought/mayavi#657]
Hi,

I'm adding mayavi as a requirement to one of my packages. During the test of the install, it fails because numpy is not installed:

Collecting mayavi (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/ff/05/1d38b1fd6ce1779e063b1f3a993552fb975e4e738ae197065f08b8c5f9fd/mayavi-4.6.0.tar.bz2 (7.0MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-oWw2Cz/mayavi/setup.py", line 70, in <module>
        import numpy
    ImportError: No module named numpy

I see some numpy.distutils imports. Is numpy required to be installed first? If so, I would expect the installation instructions to reflect that.

**Comment by chiranthsiddappa** [comment]
Nevermind, this was fixed in 479b8c13fe97c297
