### ISSUE TITLE
volume rendering

### ISSUE THREAD

**Issue by chlooooe** [enthought/mayavi#692]
Dear community,

I have a binary cube n1_sub=np.array(n1[400:600,400:600,400:600]) with only 0 and 1 values.

When I do :
path = '/home/chloe/process/vbap_03_results/production_results/segmentation_results/vbap03_21p5V_s' + '10000'+ 'ring_seg_with_median_filter_9.h5'
hf2 = h5py.File(path, 'r')
n1 = hf2.get('data')
n1 = np.array(n1)
n1_sub=np.array(n1[400:600,400:600,400:600])
mlab.pipeline.volume(mlab.pipeline.scalar_field(n1_sub))
mlab.show() 

I get the error message:

Exception
Traceback (most recent call last):
  File "/home/chloe/.local/lib/python3.5/site-packages/mayavi/core/module_manager.py", line 265, in _handle_children
    obj.start()
  File "/home/chloe/.local/lib/python3.5/site-packages/mayavi/modules/volume.py", line 293, in start
    super(Volume, self).start()
  File "/home/chloe/.local/lib/python3.5/site-packages/mayavi/core/module.py", line 120, in start
    self.update_pipeline()
  File "/home/chloe/.local/lib/python3.5/site-packages/mayavi/modules/volume.py", line 357, in update_pipeline
    self._volume_mapper_type_changed(self.volume_mapper_type)
  File "/home/chloe/.local/lib/python3.5/site-packages/mayavi/modules/volume.py", line 459, in _volume_mapper_type_changed
    new_vm = tvtk.VolumeTextureMapper2D()
AttributeError: 'TVTK' object has no attribute 'VolumeTextureMapper2D'

The following works perfectly though
l=500
x,y,z = np.ogrid[:l,:l,:l]
ball=(x-l/2)**2 + (y-l/2)**2 + (z-l/2)**2 < 200**2
ball=np.array(ball*1)
mlab.pipeline.volume(mlab.pipeline.scalar_field(ball))
mlab.show() 

Do you have any idea that I can try by any chance ?

Thank you

Chloe

**Comment by chlooooe** [comment]
So here is the clue: my data was uint8 and apparently Mayavi didn't like it. We changed it to float and everything worked perfectly :)
n1_sub=np.array(n1[400:600,400:600,400:600]).astype(np.float)

**Comment by prabhuramachandran** [comment]
Could you try with Mayavi master?  I have added several of the more recent volume mappers from VTK and they might do better.  If you still have a problem please send an easy to reproduce example for me on this thread and reopen the issue. Thanks.
