### ISSUE TITLE
tvtk PipelineBrowser Attribute ui changes to _ui

### ISSUE THREAD

**Issue by HowcanoeWang** [enthought/mayavi#734]
When I trying to generate a ivtk GUI interface by:

```python
from tvtk.tools import ivtk

win = ivtk.IVTKWithCrustAndBrowser()
win.open()
```

I get an error:
> Traceback (most recent call last):
  File "D:/OneDrive/Program/Python/StudyArea/py3d/week1/view_pipeline.py", line 12, in <module>
    win.open()
  File "D:\Virtualenv\py3d\lib\site-packages\pyface\i_window.py", line 166, in open
    self._create()
  File "D:\Virtualenv\py3d\lib\site-packages\pyface\ui\qt4\application_window.py", line 121, in _create
    contents = self._create_contents(self.control)
  File "D:\Virtualenv\py3d\lib\site-packages\pyface\split_application_window.py", line 43, in _create_contents
    return self._create_splitter(parent)
  File "D:\Virtualenv\py3d\lib\site-packages\pyface\ui\qt4\split_widget.py", line 59, in _create_splitter
    splitter.addWidget(self._create_lhs(splitter))
  File "D:\Virtualenv\py3d\lib\site-packages\tvtk\tools\ivtk.py", line 342, in _create_lhs
    self.browser_scene = SceneWithBrowser(parent)
  File "D:\Virtualenv\py3d\lib\site-packages\pyface\split_panel.py", line 36, in __init__
    self.control = self._create_splitter(parent)
  File "D:\Virtualenv\py3d\lib\site-packages\pyface\ui\qt4\split_widget.py", line 59, in _create_splitter
    splitter.addWidget(self._create_lhs(splitter))
  File "D:\Virtualenv\py3d\lib\site-packages\tvtk\tools\ivtk.py", line 209, in _create_lhs
    return self.browser.ui.control
AttributeError: 'PipelineBrowser' object has no attribute 'ui'

And when I view the source code, the class PipelineBrower.ui doesn't exist, instead, it changes to ._ui

After modifing file tvtk\tools\ivtk.py line 209
```python
return self.browser.ui.control
```
to
```python
return self.browser._ui.control
```

That works
![tim 20181108084520](https://user-images.githubusercontent.com/19968935/48170492-bd623500-e332-11e8-8921-1e9f79e56aa6.png)

Another bug you can see is that pipeline browser is poped up rather than embeded in the TVTK Scene GUI, in order to fix this, I have to coded like this:
```python
from tvtk.tools import ivtk

win = ivtk.IVTKWithCrustAndBrowser()
win.open()

# fix this pop up bug
dialog = win.control.centralWidget().widget(0).widget(0)
from pyface.qt import QtCore
dialog.setwindowFlags(QtCore.Qt.WindowFlags(0x00000000))
dialog.show()
```
![tim 20181108085454](https://user-images.githubusercontent.com/19968935/48170829-2bf3c280-e334-11e8-975e-82f2343e98f1.png)

May you help to fix these in the source code?

Thanks!

**Comment by prabhuramachandran** [comment]
Thanks!  I've fixed these issues now.

**Comment by fengzhizi32** [comment]
What about rewriting the code for that file?

from tvtk.tools import ivtk

win = ivtk.IVTKWithCrustAndBrowser()
win.open()

# fix this pop up bug
dialog = win.control.centralWidget().widget(0).widget(0)
from pyface.qt import QtCore
dialog.setwindowFlags(QtCore.Qt.WindowFlags(0x00000000))
dialog.show()

**Comment by prabhuramachandran** [comment]
Not needed, I've fixed it as well and it works now for me.

**Comment by ahundt** [comment]
@prabhuramachandran I'm seeing this in the current pypi release, which version should this be in? (cc: @btran97)
