### ISSUE TITLE
set/reset method gives AttributeError

### ISSUE THREAD

**Issue by savantas** [enthought/mayavi#737]
I'm using mayavi version 4.6.2 and encounter the following problem:

```
import mayavi.mlab as mlab

fig = mlab.figure(size=(500, 500), bgcolor=(1,1,1))

l = mlab.plot3d([0,1], [0,1], [0,1])

ls = l.mlab_source
z_values = ls.z
z_values = [z+1 for z in z_values]
ls.set(z = z_values)

mlab.show()
```

and get the following error:

```
Traceback (most recent call last):
  File "mayavi_problem.py", line 10, in <module>
    ls.set(z = z_values)
  File "/home/me/.local/lib/python3.6/site-packages/mayavi/tools/sources.py", line 106, in set
    self.update()
  File "/home/me/.local/lib/python3.6/site-packages/mayavi/tools/sources.py", line 74, in update
    (self.scalars is not None or self.vectors is not None):
AttributeError: 'MLineSource' object has no attribute 'vectors'
```

This issue seems to be related to #696 , but was supposed to be solved in version 4.5.0?

**Comment by prabhuramachandran** [comment]
This is fixed in master and I do not get the errors you mention.  Closing, please reopen if there is an issue.
