### ISSUE TITLE
Cannot animate plot3d: 'MLineSource' object has no attribute 'vectors'

### ISSUE THREAD

**Issue by Felix-neko** [enthought/mayavi#742]
Hi folks! And thank you for great project.

I have to draw some animated line, but cannot do it because of a strange bug.

That's what I do:

```
from __future__ import absolute_import, division, print_function
from mayavi import mlab
import numpy as np
import math



traj_plot = mlab.plot3d([0], [0], [0], tube_radius=0.05)



@mlab.animate(delay=100)
def anim():
    steps_count = 0
    max_n_steps = 1000
    x_total = np.linspace(0, 1, max_n_steps)
    y_total = np.linspace(0, 1, max_n_steps)
    z_total = x_total * y_total
    while steps_count < max_n_steps:
        print(traj_plot.mlab_source)
        traj_plot.mlab_source.set(x=x_total[:steps_count+1], y=y_total[:steps_count+1], z=z_total[:steps_count+1],
                                  s=np.arange(steps_count+1))
        steps_count += 1
        yield

anim()
mlab.show()
```

And that's what I get:

```
C:\Python36\python.exe "C:\Program Files\JetBrains\PyCharm 2018.1.3\helpers\pydev\pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 2917 --file D:/Projects/py3_tutorials/misc/mayavi_animation_fuss.py
pydev debugger: process 8816 is connecting

Connected to pydev debugger (build 181.4892.64)
<mayavi.tools.sources.MLineSource object at 0x0000000015088A98>
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\pyface\ui\qt4\timer\timer.py", line 51, in Notify
    self.callable(*self.args, **self.kw_args)
  File "C:\Python36\lib\site-packages\mayavi\tools\animator.py", line 224, in _step
    self._next()
  File "D:/Projects/py3_tutorials/misc/mayavi_animation_fuss.py", line 22, in anim
    s=np.arange(steps_count+1))
  File "C:\Python36\lib\site-packages\mayavi\tools\sources.py", line 106, in set
    self.update()
  File "C:\Python36\lib\site-packages\mayavi\tools\sources.py", line 74, in update
    (self.scalars is not None or self.vectors is not None):
AttributeError: 'MLineSource' object has no attribute 'vectors'
```

Can you somehow fix it? Or maybe I do something wrong?

**Comment by prabhuramachandran** [comment]
Your code has other bugs but this particular issue is fixed in master, could you try by pip installing master?

`pip install https://github.com/enthought/mayavi/zipball/master` should work I imagine.

Please reopen if an issue still persists.
