### ISSUE TITLE
traits.trait_errors.TraitError

### ISSUE THREAD

**Issue by rickwith** [enthought/mayavi#761]
The code here is for analysing fMRI data, as follow:

  def get_roi_surf(roi,vox_size,origin):
  # calculates the surface area of the ROI represented by the input array
  roi[roi==0]=-1
  grid=tvtk.ImageData(spacing=vox_size,origin=origin) 
  grid.point_data.scalars=roi.T.ravel()
  grid.point_data.scalars.name='scalars'
  grid.dimensions=roi.shape
  iso=tvtk.ImageMarchingCubes(input=grid)     ## failed here
  mass=tvtk.MassProperties(input=iso.output)
  return mass.surface_area 
----------

Traceback (most recent call last):

  File "<ipython-input-5-550818e49b2c>", line 11, in <module>
    origSA[i]=get_roi_surf(rois[:,:,:,i].copy(),voxSize,(0,0,0))

  File "<ipython-input-4-430c4ea6f6e1>", line 24, in get_roi_surf
    iso=tvtk.ImageMarchingCubes(input=grid)

  File "tvtk_classes/image_marching_cubes.py", line 58, in __init__
    tvtk_base.TVTKBase.__init__(self, vtk.vtkImageMarchingCubes, obj, update, **traits)

  File "/home/jack/anaconda3/lib/python3.7/site-packages/tvtk/tvtk_base.py", line 335, in __init__
    super(TVTKBase, self).__init__(**traits)

  File "/home/jack/anaconda3/lib/python3.7/site-packages/traits/trait_handlers.py", line 159, in _read_only
    % (name, class_of(object))

TraitError: The 'input' trait of an ImageMarchingCubes instance is 'read only'.

And vtk version is 8.1.2
        mayavi version is 4.6.2
        traits version is 5.0.0
        python version is 3.7.2

**Comment by mprogram** [comment]
possibly, a duplicate of #521

**Comment by rahulporuri** [comment]
@rickwith i have updated the issue description to be more readable
