### ISSUE TITLE
Error on opening the pipeline with new traitsui

### ISSUE THREAD

**Issue by max3-2** [enthought/mayavi#787]
When using the newest traitsui, that is `6.1.0` instead of `6.0.0`, any mayavi plot crashes when accessing the pipeline. Traceback below. Downgrading to `6.0.0` solves this. macOS 10.14, Python 3.7.3.

Traceback from a simple test_surf
```
mlab.test_surf()
<mayavi.modules.surface.Surface object at 0x127ed3048>
>>> Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyface/ui/qt4/action/action_item.py", line 386, in _qt4_on_triggered
    action.perform(action_event)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyface/action/action.py", line 135, in perform
    self.on_perform()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mayavi/core/ui/mayavi_scene.py", line 46, in show_engine
    return EngineRichView(engine=engine).scene_editing_view(scene=self)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mayavi/core/ui/engine_rich_view.py", line 164, in scene_editing_view
    return self.edit_traits()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/traits/has_traits.py", line 2024, in edit_traits
    args,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/traitsui/view.py", line 449, in ui
    ui.ui(parent, kind)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/traitsui/ui.py", line 237, in ui
    self.rebuild(self, parent)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/traitsui/qt4/toolkit.py", line 166, in ui_live
    ui_live.ui_live(ui, parent)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/traitsui/qt4/ui_live.py", line 41, in ui_live
    _ui_dialog(ui, parent, BaseDialog.NONMODAL)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/traitsui/qt4/ui_live.py", line 63, in _ui_dialog
    BaseDialog.display_ui(ui, parent, style)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/traitsui/qt4/ui_base.py", line 278, in display_ui
    ui.owner.init(ui, parent, style)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/traitsui/qt4/ui_live.py", line 203, in init
    self.add_contents(panel(ui), bbox)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/traitsui/qt4/ui_panel.py", line 265, in panel
    panel = _GroupPanel(content[0], ui).control
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/traitsui/qt4/ui_panel.py", line 558, in __init__
    self._add_splitter_items(content, splitter)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/traitsui/qt4/ui_panel.py", line 638, in _add_splitter_items
    panel = self._add_items([item])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/traitsui/qt4/ui_panel.py", line 876, in _add_items
    editor.prepare(inner)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/traitsui/editor.py", line 172, in prepare
    self.update_editor()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/traitsui/qt4/tree_editor.py", line 319, in update_editor
    self._expand_node(nid)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/traitsui/qt4/tree_editor.py", line 515, in _expand_node
    self._append_node(nid, child_node, child)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/traitsui/qt4/tree_editor.py", line 415, in _append_node
    return self._insert_node(nid, None, node, object)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/traitsui/qt4/tree_editor.py", line 432, in _insert_node
    self._add_listeners(node, object)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/traitsui/qt4/tree_editor.py", line 634, in _add_listeners
    node.when_label_changed(object, self._label_updated, False)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/traitsui/tree_node.py", line 1516, in when_label_changed
    return object.tno_when_label_changed(self, listener, remove)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/traitsui/tree_node.py", line 1898, in tno_when_label_changed
    self._listener_cache[memo] = wrapped_listener
AttributeError: 'Scene' object has no attribute '_listener_cache'
Abort trap: 6

``

**Comment by prabhuramachandran** [comment]
I believe this is fixed in the latest pyface-6.1.1.  Closing.
