### ISSUE TITLE
(just released) Mayavi 4.7.0 does not pick up the requested backend (Qt5) under Python 2 + VTK 6.3.0 (whereas Mayavi 4.6.2 does well)

### ISSUE THREAD

**Issue by mprogram** [enthought/mayavi#797]
Fresh compiled sets (_ceteris paribus_): 

**Demo:** 
https://docs.enthought.com/mayavi/mayavi/mlab.html

```bash
export QT_API=pyqt5
```
Mayavi 4.7.0
Python 2.7.15+
VTK 6.3.0
= doesn't work (seems to select the qt4 backend)

Mayavi 4.6.2
Python 2.7.15+
VTK 6.3.0
= works flawlessly (seems to select the qt5 backend)

Mayavi 4.7.0
Python 3.6.8
VTK 8.0.1
= works flawlessly (seems to select the qt5 backend)

EDIT: `pyface`, `apptools`, `envisage`, `traits`, `traitsui` are all from their respective master branches

P.S. `apptools` for Python 3 may not have module named 'cStringIO', please have a look at: https://stackoverflow.com/q/28200366

**Comment by prabhuramachandran** [comment]
I think this may have to do with traitsui/pyface as I don't recall changing anything in mayavi to break this.  A traceback may help although I am not using a Python 2 environment.

**Comment by mprogram** [comment]
It might be that, but both, v4.6.2 and v4.7.0 where compiled with identical set of dependencies. Anyway, I've transferred the ticket to:
enthought/pyface/issues/412
enthought/apptools/issues/94

**Comment by mprogram** [comment]
```
$ QT_API=pyqt5 ETS_TOOLKIT=qt mayavi2 mayavi2 ~/demo.py

Exception occurred in traits notification handler for object: <mayavi.filters.poly_data_normals.PolyDataNormals object at 0x7ff831ce3770>, trait: name, old value: PolyDataNormals, new value: 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/traits/trait_notifiers.py", line 591, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/usr/lib/python2.7/dist-packages/traits/trait_notifiers.py", line 695, in dispatch
    handler(*args)
  File "/usr/lib/python2.7/dist-packages/traitsui/tree_node.py", line 1899, in wrapped_listener
    return listener(node, name, new)
  File "/usr/lib/python2.7/dist-packages/traitsui/qt4/tree_editor.py", line 1618, in _label_updated
    for name2, nid in self._map[id(object)]:
KeyError: 140704141818384
ERROR|2019-07-01 16:25:18,685|Exception occurred in traits notification handler for object: <mayavi.filters.poly_data_normals.PolyDataNormals object at 0x7ff831ce3770>, trait: name, old value: PolyDataNormals, new value: 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/traits/trait_notifiers.py", line 591, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/usr/lib/python2.7/dist-packages/traits/trait_notifiers.py", line 695, in dispatch
    handler(*args)
  File "/usr/lib/python2.7/dist-packages/traitsui/tree_node.py", line 1899, in wrapped_listener
    return listener(node, name, new)
  File "/usr/lib/python2.7/dist-packages/traitsui/qt4/tree_editor.py", line 1618, in _label_updated
    for name2, nid in self._map[id(object)]:
KeyError: 140704141818384
Terminated
```

**Comment by mprogram** [comment]
_I've upgraded Mayavi2 to the latest sources, and VTK to v8.2.0. Closing the issue as no more relevant and not appearing._
