### ISSUE TITLE
Mayavi 4.7.0 under Python 3 misbehaves when setting preferences

### ISSUE THREAD

**Issue by mprogram** [enthought/mayavi#798]
The following appears in the log upon setting preferences:

```
Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> Exception occurred in traits notification handler.
Please check the log file for details.
```
```
Exception occurred in traits notification handler for object: <apptools.preferences.ui.preferences_page.PreferencesPage object at 0x7fc63dfe6830>, trait: preferences, old value: <apptools.preferences.scoped_preferences.ScopedPreferences object at 0x7fc643984bf8>, new value: <apptools.preferences.scoped_preferences.ScopedPreferences object at 0x7fc63dfe6a98>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/traits/trait_notifiers.py", line 394, in __call__
    self.handler(*args)
  File "/usr/lib/python3/dist-packages/apptools/preferences/preferences_helper.py", line 81, in _preferences_changed
    self._preferences_changed_listener, self._get_path()
  File "/usr/lib/python3/dist-packages/apptools/preferences/preferences_helper.py", line 112, in _get_path
    raise SystemError('no preferences path, %s' % self)
SystemError: no preferences path, <apptools.preferences.ui.preferences_page.PreferencesPage object at 0x7fc63dfe6830>
ERROR|2019-07-01 14:55:54,473|Exception occurred in traits notification handler for object: <apptools.preferences.ui.preferences_page.PreferencesPage object at 0x7fc63dfe6830>, trait: preferences, old value: <apptools.preferences.scoped_preferences.ScopedPreferences object at 0x7fc643984bf8>, new value: <apptools.preferences.scoped_preferences.ScopedPreferences object at 0x7fc63dfe6a98>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/traits/trait_notifiers.py", line 394, in __call__
    self.handler(*args)
  File "/usr/lib/python3/dist-packages/apptools/preferences/preferences_helper.py", line 81, in _preferences_changed
    self._preferences_changed_listener, self._get_path()
  File "/usr/lib/python3/dist-packages/apptools/preferences/preferences_helper.py", line 112, in _get_path
    raise SystemError('no preferences path, %s' % self)
SystemError: no preferences path, <apptools.preferences.ui.preferences_page.PreferencesPage object at 0x7fc63dfe6830>
```

**Comment by prabhuramachandran** [comment]
Did you launch the mayavi2 app to get this?

**Comment by mprogram** [comment]
Well, yes.

**Comment by mprogram** [comment]
_I've upgraded Mayavi2 to the latest sources, and VTK to v8.2.0. Closing the issue as no more relevant and not appearing._

**Comment by mprogram** [comment]
It seems I've closed the issue prematurely
1) Run Mayavi
2) Go To Tools/Preferences, try setting some
3) Observe the following (tested under Python3):
```
$ rm -rf ~/.enthought && env QT_API=pyqt ETS_TOOLKIT=qt4 mayavi2 ~/demo.py
Exception occurred in traits notification handler for object: <apptools.preferences.ui.preferences_page.PreferencesPage object at 0x7fc9e7965c50>, trait: preferences, old value: <apptools.preferences.scoped_preferences.ScopedPreferences object at 0x7fc9f66f11a8>, new value: <apptools.preferences.scoped_preferences.ScopedPreferences object at 0x7fc9e6013258>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/traits/trait_notifiers.py", line 394, in __call__
    self.handler(*args)
  File "/usr/lib/python3/dist-packages/apptools/preferences/preferences_helper.py", line 81, in _preferences_changed
    self._preferences_changed_listener, self._get_path()
  File "/usr/lib/python3/dist-packages/apptools/preferences/preferences_helper.py", line 112, in _get_path
    raise SystemError('no preferences path, %s' % self)
SystemError: no preferences path, <apptools.preferences.ui.preferences_page.PreferencesPage object at 0x7fc9e7965c50>
ERROR|2019-07-07 02:41:21,925|Exception occurred in traits notification handler for object: <apptools.preferences.ui.preferences_page.PreferencesPage object at 0x7fc9e7965c50>, trait: preferences, old value: <apptools.preferences.scoped_preferences.ScopedPreferences object at 0x7fc9f66f11a8>, new value: <apptools.preferences.scoped_preferences.ScopedPreferences object at 0x7fc9e6013258>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/traits/trait_notifiers.py", line 394, in __call__
    self.handler(*args)
  File "/usr/lib/python3/dist-packages/apptools/preferences/preferences_helper.py", line 81, in _preferences_changed
    self._preferences_changed_listener, self._get_path()
  File "/usr/lib/python3/dist-packages/apptools/preferences/preferences_helper.py", line 112, in _get_path
    raise SystemError('no preferences path, %s' % self)
SystemError: no preferences path, <apptools.preferences.ui.preferences_page.PreferencesPage object at 0x7fc9e7965c50>
```

**Comment by mprogram** [comment]
UPDATE: interactive running:
`$ rm -rf ~/.enthought && env QT_API=pyside2 ETS_TOOLKIT=qt4 mayavi2`
``` python
Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from numpy import pi, sin, cos, mgrid
>>> dphi, dtheta = pi/250.0, pi/250.0
>>> [phi,theta] = mgrid[0:pi+dphi*1.5:dphi,0:2*pi+dtheta*1.5:dtheta]
>>> m0 = 4; m1 = 3; m2 = 2; m3 = 3; m4 = 6; m5 = 2; m6 = 6; m7 = 4;
>>> r = sin(m0*phi)**m1 + cos(m2*phi)**m3 + sin(m4*theta)**m5 + cos(m6*theta)**m7
>>> x = r*sin(phi)*cos(theta)
>>> y = r*cos(phi)
>>> z = r*sin(phi)*sin(theta)
>>> from mayavi import mlab
>>> s = mlab.mesh(x, y, z)
Exception occurred in traits notification handler.
Please check the log file for details.
Exception occurred in traits notification handler for object: <mayavi.filters.poly_data_normals.PolyDataNormals object at 0x7f57583c1888>, trait: name, old value: PolyDataNormals, new value: 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/traits/trait_notifiers.py", line 591, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/usr/lib/python3/dist-packages/traits/trait_notifiers.py", line 695, in dispatch
    handler(*args)
  File "/usr/lib/python3/dist-packages/traitsui/tree_node.py", line 1899, in wrapped_listener
    return listener(node, name, new)
  File "/usr/lib/python3/dist-packages/traitsui/qt4/tree_editor.py", line 1618, in _label_updated
    for name2, nid in self._map[id(object)]:
KeyError: 140013175497480
Exception occurred in traits notification handler for object: <mayavi.modules.surface.Surface object at 0x7f5758216200>, trait: name, old value: Surface, new value: 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/traits/trait_notifiers.py", line 591, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/usr/lib/python3/dist-packages/traits/trait_notifiers.py", line 695, in dispatch
    handler(*args)
  File "/usr/lib/python3/dist-packages/traitsui/tree_node.py", line 1899, in wrapped_listener
    return listener(node, name, new)
  File "/usr/lib/python3/dist-packages/traitsui/qt4/tree_editor.py", line 1618, in _label_updated
    for name2, nid in self._map[id(object)]:
KeyError: 140013175497480

(now navigate to Tools/Preferences, try setting Stereo, ipython, etc… BTW, what those options mean? I see no difference on the output)

>>> Exception occurred in traits notification handler for object: <apptools.preferences.ui.preferences_page.PreferencesPage object at 0x7f5753ea3ca8>, trait: preferences, old value: <apptools.preferences.scoped_preferences.ScopedPreferences object at 0x7f575f9d24c0>, new value: <apptools.preferences.scoped_preferences.ScopedPreferences object at 0x7f5753dcd620>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/traits/trait_notifiers.py", line 394, in __call__
    self.handler(*args)
  File "/usr/lib/python3/dist-packages/apptools/preferences/preferences_helper.py", line 81, in _preferences_changed
    self._preferences_changed_listener, self._get_path()
  File "/usr/lib/python3/dist-packages/apptools/preferences/preferences_helper.py", line 112, in _get_path
    raise SystemError('no preferences path, %s' % self)
SystemError: no preferences path, <apptools.preferences.ui.preferences_page.PreferencesPage object at 0x7f5753ea3ca8>
```

**Comment by opoplawski** [comment]
This has been reported against Fedora 31 as well: https://bugzilla.redhat.com/show_bug.cgi?id=1852478

**Comment by opoplawski** [comment]
On fedora rawhide:
```
(base) [orion@vmrawhide-rufous ~]$ mayavi2
ERROR|2020-07-02 20:57:22,355|Exception occurred in traits notification handler for object: <apptools.preferences.ui.preferences_page.PreferencesPage object at 0x7fd839c183b0>, trait: preferences, old value: <apptools.preferences.scoped_preferences.ScopedPreferences object at 0x7fd858deac70>, new value: <apptools.preferences.scoped_preferences.ScopedPreferences object at 0x7fd8216b24a0>
Traceback (most recent call last):
  File "/usr/lib64/python3.9/site-packages/traits/trait_notifiers.py", line 340, in __call__
    self.handler(*args)
  File "/usr/lib/python3.9/site-packages/apptools/preferences/preferences_helper.py", line 81, in _preferences_changed
    self._preferences_changed_listener, self._get_path()
  File "/usr/lib/python3.9/site-packages/apptools/preferences/preferences_helper.py", line 112, in _get_path
    raise SystemError('no preferences path, %s' % self)
SystemError: no preferences path, <apptools.preferences.ui.preferences_page.PreferencesPage object at 0x7fd839c183b0>
```
Packages:
```
Mayavi-4.7.1-3.fc33.x86_64
python3-apptools-4.5.0-3.fc33.noarch
python3-Traits-6.1.0-1.fc33.x86_64
python3-traitsui-7.0.0-2.fc33.noarch
```

**Comment by Harshapriya123** [comment]
> ```
> python3-traitsui-7.0.0-2.fc33.noarch
> ```

Is that you got solution? i too get the same errors.
` C:\WINDOWS\system32>python C:\Users\harsha\Anaconda3\etc\keras\load_config.py  1>temp.txt
The process cannot access the file because it is being used by another process.

C:\WINDOWS\system32>set /p KERAS_BACKEND= 0<temp.txt

C:\WINDOWS\system32>del temp.txt
C:\WINDOWS\system32\temp.txt
The process cannot access the file because it is being used by another process.

C:\WINDOWS\system32>python -c "import keras"  1>nul 2>&1

C:\WINDOWS\system32>if errorlevel 1 (
ver  1>nul
 set "KERAS_BACKEND=theano"
 python -c "import keras"  1>nul 2>&1
)

(base) C:\WINDOWS\system32>pip install numpy --upgrade --ignore-installed
Collecting numpy
  Downloading numpy-1.19.5-cp37-cp37m-win_amd64.whl (13.2 MB)
     |████████████████████████████████| 13.2 MB 244 kB/s
Installing collected packages: numpy
ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'c:\\users\\harsha\\anaconda3\\Lib\\site-packages\\numpy\\core\\_multiarray_tests.cp37-win_amd64.pyd'
Consider using the `--user` option or check the permissions.


(base) C:\WINDOWS\system32>pip install numpy --user
Requirement already satisfied: numpy in c:\users\harsha\anaconda3\lib\site-packages (1.16.5)

(base) C:\WINDOWS\system32>pip install numpy --upgrade
Requirement already satisfied: numpy in c:\users\harsha\anaconda3\lib\site-packages (1.16.5)
Collecting numpy
  Using cached numpy-1.19.5-cp37-cp37m-win_amd64.whl (13.2 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.16.5
    Uninstalling numpy-1.16.5:
      Successfully uninstalled numpy-1.16.5
Successfully installed numpy-1.19.5

(base) C:\WINDOWS\system32>mayavi2
ERROR|2021-01-29 11:01:44,818|Exception occurred in traits notification handler for object: <apptools.preferences.ui.preferences_page.PreferencesPage object at 0x00000213E0BE9648>, trait: preferences, old value: <apptools.preferences.scoped_preferences.ScopedPreferences object at 0x00000213DB3D3A68>, new value: <apptools.preferences.scoped_preferences.ScopedPreferences object at 0x00000213E0BA8B28>
Traceback (most recent call last):
  File "C:\Users\harsha\Anaconda3\lib\site-packages\traits\trait_notifiers.py", line 340, in __call__
    self.handler(*args)
  File "C:\Users\harsha\Anaconda3\lib\site-packages\apptools\preferences\preferences_helper.py", line 81, in _preferences_changed
    self._preferences_changed_listener, self._get_path()
  File "C:\Users\harsha\Anaconda3\lib\site-packages\apptools\preferences\preferences_helper.py", line 112, in _get_path
    raise SystemError('no preferences path, %s' % self)
SystemError: no preferences path, <apptools.preferences.ui.preferences_page.PreferencesPage object at 0x00000213E0BE9648>
ERROR|2021-01-29 11:03:25,006|Exception occurred in traits notification handler for object: <apptools.preferences.ui.preferences_page.PreferencesPage object at 0x00000213E15F1EE8>, trait: preferences, old value: <apptools.preferences.scoped_preferences.ScopedPreferences object at 0x00000213DB3D3A68>, new value: <apptools.preferences.scoped_preferences.ScopedPreferences object at 0x00000213E15F1E88>
Traceback (most recent call last):
  File "C:\Users\harsha\Anaconda3\lib\site-packages\traits\trait_notifiers.py", line 340, in __call__
    self.handler(*args)
  File "C:\Users\harsha\Anaconda3\lib\site-packages\apptools\preferences\preferences_helper.py", line 81, in _preferences_changed
    self._preferences_changed_listener, self._get_path()
  File "C:\Users\harsha\Anaconda3\lib\site-packages\apptools\preferences\preferences_helper.py", line 112, in _get_path
    raise SystemError('no preferences path, %s' % self)
SystemError: no preferences path, <apptools.preferences.ui.preferences_page.PreferencesPage object at 0x00000213E15F1EE8>
ERROR|2021-01-29 11:03:25,914|Exception occurred in traits notification handler for object: <apptools.preferences.ui.preferences_page.PreferencesPage object at 0x00000213E0BA5048>, trait: preferences, old value: <apptools.preferences.scoped_preferences.ScopedPreferences object at 0x00000213DB3D3A68>, new value: <apptools.preferences.scoped_preferences.ScopedPreferences object at 0x00000213E0BD9EE8>
Traceback (most recent call last):
  File "C:\Users\harsha\Anaconda3\lib\site-packages\traits\trait_notifiers.py", line 340, in __call__
    self.handler(*args)
  File "C:\Users\harsha\Anaconda3\lib\site-packages\apptools\preferences\preferences_helper.py", line 81, in _preferences_changed
    self._preferences_changed_listener, self._get_path()
  File "C:\Users\harsha\Anaconda3\lib\site-packages\apptools\preferences\preferences_helper.py", line 112, in _get_path
    raise SystemError('no preferences path, %s' % self)
SystemError: no preferences path, <apptools.preferences.ui.preferences_page.PreferencesPage object at 0x00000213E0BA5048>
ERROR|2021-01-29 11:03:26,985|Exception occurred in traits notification handler for object: <apptools.preferences.ui.preferences_page.PreferencesPage object at 0x00000213E0BD9DC8>, trait: preferences, old value: <apptools.preferences.scoped_preferences.ScopedPreferences object at 0x00000213DB3D3A68>, new value: <apptools.preferences.scoped_preferences.ScopedPreferences object at 0x00000213DFC58168>
Traceback (most recent call last):
  File "C:\Users\harsha\Anaconda3\lib\site-packages\traits\trait_notifiers.py", line 340, in __call__
    self.handler(*args)
  File "C:\Users\harsha\Anaconda3\lib\site-packages\apptools\preferences\preferences_helper.py", line 81, in _preferences_changed
    self._preferences_changed_listener, self._get_path()
  File "C:\Users\harsha\Anaconda3\lib\site-packages\apptools\preferences\preferences_helper.py", line 112, in _get_path
    raise SystemError('no preferences path, %s' % self)
SystemError: no preferences path, <apptools.preferences.ui.preferences_page.PreferencesPage object at 0x00000213E0BD9DC8>
ERROR|2021-01-29 11:03:27,760|Exception occurred in traits notification handler for object: <apptools.preferences.ui.preferences_page.PreferencesPage object at 0x00000213DFC78168>, trait: preferences, old value: <apptools.preferences.scoped_preferences.ScopedPreferences object at 0x00000213DB3D3A68>, new value: <apptools.preferences.scoped_preferences.ScopedPreferences object at 0x00000213DFC783A8>
Traceback (most recent call last):
  File "C:\Users\harsha\Anaconda3\lib\site-packages\traits\trait_notifiers.py", line 340, in __call__
    self.handler(*args)
  File "C:\Users\harsha\Anaconda3\lib\site-packages\apptools\preferences\preferences_helper.py", line 81, in _preferences_changed
    self._preferences_changed_listener, self._get_path()
  File "C:\Users\harsha\Anaconda3\lib\site-packages\apptools\preferences\preferences_helper.py", line 112, in _get_path
    raise SystemError('no preferences path, %s' % self)
SystemError: no preferences path, <apptools.preferences.ui.preferences_page.PreferencesPage object at 0x00000213DFC78168>
ERROR|2021-01-29 11:03:40,564|Exception occurred in traits notification handler for object: <apptools.preferences.ui.preferences_page.PreferencesPage object at 0x00000213E0830A08>, trait: preferences, old value: <apptools.preferences.scoped_preferences.ScopedPreferences object at 0x00000213DB3D3A68>, new value: <apptools.preferences.scoped_preferences.ScopedPreferences object at 0x00000213E0830C48>
Traceback (most recent call last):
  File "C:\Users\harsha\Anaconda3\lib\site-packages\traits\trait_notifiers.py", line 340, in __call__
    self.handler(*args)
  File "C:\Users\harsha\Anaconda3\lib\site-packages\apptools\preferences\preferences_helper.py", line 81, in _preferences_changed
    self._preferences_changed_listener, self._get_path()
  File "C:\Users\harsha\Anaconda3\lib\site-packages\apptools\preferences\preferences_helper.py", line 112, in _get_path
    raise SystemError('no preferences path, %s' % self)
SystemError: no preferences path, <apptools.preferences.ui.preferences_page.PreferencesPage object at 0x00000213E0830A08>
ERROR|2021-01-29 11:03:41,377|Exception occurred in traits notification handler for object: <apptools.preferences.ui.preferences_page.PreferencesPage object at 0x00000213E08AB048>, trait: preferences, old value: <apptools.preferences.scoped_preferences.ScopedPreferences object at 0x00000213DB3D3A68>, new value: <apptools.preferences.scoped_preferences.ScopedPreferences object at 0x00000213E08AB2E8>
Traceback (most recent call last):
  File "C:\Users\harsha\Anaconda3\lib\site-packages\traits\trait_notifiers.py", line 340, in __call__
    self.handler(*args)
  File "C:\Users\harsha\Anaconda3\lib\site-packages\apptools\preferences\preferences_helper.py", line 81, in _preferences_changed
    self._preferences_changed_listener, self._get_path()
  File "C:\Users\harsha\Anaconda3\lib\site-packages\apptools\preferences\preferences_helper.py", line 112, in _get_path
    raise SystemError('no preferences path, %s' % self)
SystemError: no preferences path, <apptools.preferences.ui.preferences_page.PreferencesPage object at 0x00000213E08AB048>
Qt: Untested Windows version 10.0 detected!
Qt: Untested Windows version 10.0 detected!
ERROR|2021-01-29 11:05:38,161|'NoneType' object has no attribute 'run_line_magic'
Traceback (most recent call last):
  File "C:\Users\harsha\Anaconda3\lib\site-packages\mayavi\action\save_load.py", line 118, in perform
    open(dialog.path).read(), dialog.path, 'exec'), g, g
  File "C:/Users/harsha/Downloads/GUI/NEW.py", line 7, in <module>
    get_ipython().run_line_magic('gui', 'qt')
AttributeError: 'NoneType' object has no attribute 'run_line_magic'
ERROR|2021-01-29 11:21:45,433|'NoneType' object has no attribute 'run_line_magic'
Traceback (most recent call last):
  File "C:\Users\harsha\Anaconda3\lib\site-packages\mayavi\action\save_load.py", line 118, in perform
    open(dialog.path).read(), dialog.path, 'exec'), g, g
  File "C:/Users/harsha/Downloads/GUI/NEW.py", line 11, in <module>
    get_ipython().run_line_magic('gui', 'qt')
AttributeError: 'NoneType' object has no attribute 'run_line_magic' `
