### ISSUE TITLE
FiPy: 'AssignAttribute' object has no attribute 'cell_data'

### ISSUE THREAD

**Issue by mprogram** [enthought/mayavi#802]
I'm trying to run the following example, taken from: https://www.ctcms.nist.gov/fipy/fipy/generated/fipy.viewers.mayaviViewer.html
``` python
import os
os.environ["QT_API"] = "pyqt"

from traits.etsconfig.api import ETSConfig
ETSConfig.toolkit = 'qt4'

from fipy import *
mesh = Grid3D(nx=50, ny=100, nz=10, dx=0.1, dy=0.01, dz=0.1)
x, y, z = mesh.cellCenters
xyzVar = CellVariable(mesh=mesh, name=r"x y z", value=x * y * z)
k = Variable(name="k", value=0.)
viewer = MayaviClient(vars=numerix.sin(k * xyzVar),
                    limits={'ymin': 0.1, 'ymax': 0.9},
                    datamin=-0.9, datamax=2.0,
                    title="MayaviClient test")
from builtins import range
for kval in range(10):
    k.setValue(kval)
    viewer.plot()
viewer._promptForOpinion()
```
However, I'm getting the following traceback: 
```
Jul 08 13:54:38 linux compiz[2909]: Traceback (most recent call last):
Jul 08 13:54:38 linux compiz[2909]:   File "/usr/lib/python2.7/dist-packages/pyface/ui/qt4/gui.py", line 183, in event
Jul 08 13:54:38 linux compiz[2909]:     self._callable(*self._args, **self._kw)
Jul 08 13:54:38 linux compiz[2909]:   File "~/.local/lib/python2.7/site-packages/fipy/viewers/mayaviViewer/mayaviDaemon.py", line 130, in run
Jul 08 13:54:38 linux compiz[2909]:     if out.cell_data.scalars is not None]
Jul 08 13:54:38 linux compiz[2909]: AttributeError: 'AssignAttribute' object has no attribute 'cell_data'
```
How shall I construct the code to be Mayavi properly called?

**Comment by s769** [comment]
I also have the same issue. I think it may be a problem with vtk but I'm not sure.
