### ISSUE TITLE
Mayavi 4.7.0: No pyface.toolkits plugin could be loaded for qt4

### ISSUE THREAD

**Issue by gnurser** [enthought/mayavi#803]
If I invoke mayavi2 from the command line (MacOS 10.13, miniconda3 with python3.7), with pyqt and standard qt(?qt4) backends:
~~~~
(basemap) ~ $ env | grep QT
QT_API=pyqt
(basemap) ~ $ env | grep TOOL  
ETS_TOOLKIT=qt4
 ~~~~

 I am getting:
`(basemap) ~ $ mayavi2`
~~~~
Traceback (most recent call last):
  File "/Users/agn/miniconda3/envs/basemap/bin/mayavi2", line 7, in <module>
    from mayavi.scripts.mayavi2 import main
  File "/Users/agn/miniconda3/envs/basemap/lib/python3.7/site-packages/mayavi/scripts/mayavi2.py", line 464, in <module>
    from mayavi.plugins.app import Mayavi, setup_logger
  File "/Users/agn/miniconda3/envs/basemap/lib/python3.7/site-packages/mayavi/plugins/app.py", line 19, in <module>
    from .mayavi_workbench_application import MayaviWorkbenchApplication
  File "/Users/agn/miniconda3/envs/basemap/lib/python3.7/site-packages/mayavi/plugins/mayavi_workbench_application.py", line 13, in <module>
    from envisage.ui.workbench.api import WorkbenchApplication
  File "/Users/agn/miniconda3/envs/basemap/lib/python3.7/site-packages/envisage/ui/workbench/api.py", line 4, in <module>
    from .workbench import Workbench
  File "/Users/agn/miniconda3/envs/basemap/lib/python3.7/site-packages/envisage/ui/workbench/workbench.py", line 5, in <module>
    import pyface.workbench.api as pyface
  File "/Users/agn/miniconda3/envs/basemap/lib/python3.7/site-packages/pyface/workbench/api.py", line 4, in <module>
    from .editor import Editor
  File "/Users/agn/miniconda3/envs/basemap/lib/python3.7/site-packages/pyface/workbench/editor.py", line 18, in <module>
    from pyface.toolkit import toolkit_object
  File "/Users/agn/miniconda3/envs/basemap/lib/python3.7/site-packages/pyface/toolkit.py", line 27, in <module>
    toolkit = toolkit_object = find_toolkit('pyface.toolkits')
  File "/Users/agn/miniconda3/envs/basemap/lib/python3.7/site-packages/pyface/base_toolkit.py", line 263, in find_toolkit
    return import_toolkit(ETSConfig.toolkit, entry_point)
  File "/Users/agn/miniconda3/envs/basemap/lib/python3.7/site-packages/pyface/base_toolkit.py", line 227, in import_toolkit
    raise RuntimeError(msg)
RuntimeError: No pyface.toolkits plugin could be loaded for qt4
~~~~

I had just installed mayavi 4.7.0 on a Max, OSX using conda.
I did
`conda install mayavi` (using the conda-forge channel)

The following packages were installed
~~~~
The following NEW packages will be INSTALLED:

  apptools           conda-forge/osx-64::apptools-4.4.0-py37_1002
  configobj          conda-forge/noarch::configobj-5.0.6-py_0
  dbus               conda-forge/osx-64::dbus-1.13.6-h2f22bb5_0
  envisage           conda-forge/noarch::envisage-4.7.2-py_0
  expat              conda-forge/osx-64::expat-2.2.5-h6de7cb9_1003
  future             conda-forge/osx-64::future-0.17.1-py37_1000
  gettext            conda-forge/osx-64::gettext-0.19.8.1-h46ab8bc_1002
  glib               conda-forge/osx-64::glib-2.58.3-h9d45998_1001
  jsoncpp            conda-forge/osx-64::jsoncpp-1.8.4-h04f5b5a_1001
  mayavi             conda-forge/osx-64::mayavi-4.7.0-py37h2cdb68b_0
  pcre               conda-forge/osx-64::pcre-8.41-h0a44026_1003
  pyface             conda-forge/noarch::pyface-6.1.1-py_0
  pyqt               conda-forge/osx-64::pyqt-5.9.2-py37h2a560b1_0
  qt                 conda-forge/osx-64::qt-5.9.7-h93ee506_2
  sip                conda-forge/osx-64::sip-4.19.8-py37h0a44026_1000
  tbb                conda-forge/osx-64::tbb-2019.7-h770b8ee_0
  traits             conda-forge/osx-64::traits-5.1.1-py37h01d97ff_0
  traitsui           conda-forge/noarch::traitsui-6.1.1-py_0
  vtk                conda-forge/osx-64::vtk-8.2.0-py37h9382d79_201
~~~~

**Comment by kaushik333** [comment]
were you able to resolve this issue? If yes, can you please point me to how you did it? Thanks.
