### ISSUE TITLE
installation failure on Win 10: vtk downloaded but not found

### ISSUE THREAD

**Issue by RossBoylan** [enthought/mayavi#818]
Windows 10, Python 3.7.3 installed as part of MS Visual Studio (I have 2019 and 2017 installed).
Numpy and PyQt5 were already installed.
Running with elevated privileges, the installer downloads vtk, but when it gets to building the wheel for myavi it fails with "No module named 'vtk'".  Maybe vtk is not fully installed or configured at that point, so some dependency isn't properly expressed?

Transcript:
```
Microsoft Windows [Version 10.0.16299.1268]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\windows\system32>py -3-64 -m pip install mayavi
Collecting mayavi
  Downloading https://files.pythonhosted.org/packages/08/ea/eb808cb4df8f92bc4d9f9a1ef14566b9b5d60370e6ecbaf9061cdae335fa/mayavi-4.7.1.tar.bz2 (7.0MB)
     |████████████████████████████████| 7.0MB 6.8MB/s
Collecting apptools (from mayavi)
  Downloading https://files.pythonhosted.org/packages/78/84/64764e2c87fcb7ad7521bdabc7c44c109b80691f94218cbddd5df2ee682c/apptools-4.4.0.tar.bz2 (241kB)
     |████████████████████████████████| 245kB ...
Collecting envisage (from mayavi)
  Downloading https://files.pythonhosted.org/packages/24/25/63a50574fd9af66345ee6dc0d4bac342e755f9ac868927ca0beae178725a/envisage-4.7.2.tar.gz (256kB)
     |████████████████████████████████| 266kB ...
Requirement already satisfied: numpy in c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages (from mayavi) (1.16.3)
Collecting pyface>=6.1.1 (from mayavi)
  Downloading https://files.pythonhosted.org/packages/71/0b/6410ff300b614d1f25f045a99cde27ff40e5ffa6ec5e95860c0fbce80faf/pyface-6.1.2.tar.gz (5.3MB)
     |████████████████████████████████| 5.3MB ...
Collecting pygments (from mayavi)
  Downloading https://files.pythonhosted.org/packages/5c/73/1dfa428150e3ccb0fa3e68db406e5be48698f2a979ccbcec795f28f44048/Pygments-2.4.2-py2.py3-none-any.whl (883kB)
     |████████████████████████████████| 890kB ...
Collecting traits>=4.6.0 (from mayavi)
  Downloading https://files.pythonhosted.org/packages/95/d5/aa0e6622e9183008cb9a3e91b147685035991a6faf7e03450029786b6526/traits-5.1.2.tar.gz (437kB)
     |████████████████████████████████| 440kB ...
Collecting traitsui>=6.0.0 (from mayavi)
  Downloading https://files.pythonhosted.org/packages/8c/dd/6f7ce27586d3657826fbd315858d19d3a98d609db45380da4abcc3dcd18c/traitsui-6.1.2.tar.gz (5.1MB)
     |████████████████████████████████| 5.1MB ...
Collecting vtk (from mayavi)
  Downloading https://files.pythonhosted.org/packages/6b/55/e4f0cdf6634def017a98374a6930ffdd65d84b8ddf1c885a08728de5b408/vtk-8.1.2-cp37-cp37m-win_amd64.whl (24.4MB)
     |████████████████████████████████| 24.4MB 6.4MB/s
Collecting configobj (from apptools->mayavi)
  Downloading https://files.pythonhosted.org/packages/64/61/079eb60459c44929e684fa7d9e2fdca403f67d64dd9dbac27296be2e0fab/configobj-5.0.6.tar.gz
Requirement already satisfied: six in c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages (from traits>=4.6.0->mayavi) (1.12.0)
Building wheels for collected packages: mayavi, apptools, envisage, pyface, traits, traitsui, configobj
  Building wheel for mayavi (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\rdboylan\\AppData\\Local\\Temp\\pip-install-i4o59wpf\\mayavi\\setup.py'"'"'; __file__='"'"'C:\\Users\\rdboylan\\AppData\\Local\\Temp\\pip-install-i4o59wpf\\mayavi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\rdboylan\AppData\Local\Temp\pip-wheel-wl9gy7q2' --python-tag cp37
       cwd: C:\Users\rdboylan\AppData\Local\Temp\pip-install-i4o59wpf\mayavi\
  Complete output (33 lines):
  running bdist_wheel
  running build
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\rdboylan\AppData\Local\Temp\pip-install-i4o59wpf\mayavi\setup.py", line 474, in <module>
      **config
    File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\numpy\distutils\core.py", line 171, in setup
      return old_setup(**new_attr)
    File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\setuptools\__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\wheel\bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\rdboylan\AppData\Local\Temp\pip-install-i4o59wpf\mayavi\setup.py", line 268, in run
      build_tvtk_classes_zip()
    File "C:\Users\rdboylan\AppData\Local\Temp\pip-install-i4o59wpf\mayavi\setup.py", line 254, in build_tvtk_classes_zip
      gen_tvtk_classes_zip()
    File "tvtk\setup.py", line 83, in gen_tvtk_classes_zip
      from tvtk.code_gen import TVTKGenerator
    File "C:\Users\rdboylan\AppData\Local\Temp\pip-install-i4o59wpf\mayavi\tvtk\code_gen.py", line 10, in <module>
      import vtk_module as vtk
    File "tvtk\vtk_module.py", line 15, in <module>
      from vtk import *
  ModuleNotFoundError: No module named 'vtk'
  ----------------------------------------
  ERROR: Failed building wheel for mayavi
  Running setup.py clean for mayavi
  Building wheel for apptools (setup.py) ... done
  Created wheel for apptools: filename=apptools-4.4.0-cp37-none-any.whl size=393781 sha256=0ab1b8e9ac3c2a7c39a1c8446f9e920efcc92bbfc7714e5f0480162c1883644f
  Stored in directory: C:\Users\rdboylan\AppData\Local\pip\Cache\wheels\f9\9e\2a\981bab2267d8f7fa546568cd79440e6b61b4fc570ee071080e
  Building wheel for envisage (setup.py) ... done
  Created wheel for envisage: filename=envisage-4.7.2-cp37-none-any.whl size=395860 sha256=d23d0550b3b96ab6e05c7a8bf365c9e5a442e1985f7de7d70b28e4d16e58cd58
  Stored in directory: C:\Users\rdboylan\AppData\Local\pip\Cache\wheels\c6\4e\b1\7fdc3b4f5d86e82f74e962ec368bd024d91105aee07b2e5c90
  Building wheel for pyface (setup.py) ... done
  Created wheel for pyface: filename=pyface-6.1.2-cp37-none-any.whl size=1013182 sha256=b4d6603ac3ab40e64347a6acd354d8d9e82323441b6e5ae695413a3c271a362d
  Stored in directory: C:\Users\rdboylan\AppData\Local\pip\Cache\wheels\99\7c\75\0ce4d816cbcf9da1a2887b5d17a8c7e283a11622e008c8455d
  Building wheel for traits (setup.py) ... done
  Created wheel for traits: filename=traits-5.1.2-cp37-cp37m-win_amd64.whl size=297197 sha256=c3574ea0f09836344e33363cfc6134cab22d1be7ba8c51b8bb908ccca1a9e17f
  Stored in directory: C:\Users\rdboylan\AppData\Local\pip\Cache\wheels\07\a9\28\7705539d9cb37ef1ef984e0019910071ce1fb5ed60873ca455
  Building wheel for traitsui (setup.py) ... done
  Created wheel for traitsui: filename=traitsui-6.1.2-cp37-none-any.whl size=783701 sha256=89e3ade06f69d6f451efa31ce5f8ded4dd0734f0955784cdab377043e0144ace
  Stored in directory: C:\Users\rdboylan\AppData\Local\pip\Cache\wheels\d7\0d\49\75945c25a6c317891fc0afd28dada00287784e8255199de0e3
  Building wheel for configobj (setup.py) ... done
  Created wheel for configobj: filename=configobj-5.0.6-cp37-none-any.whl size=34550 sha256=480564bfd523bd2d73a44fe3d5c033cdb42a128ca67ebb6306f14a2a214f3ceb
  Stored in directory: C:\Users\rdboylan\AppData\Local\pip\Cache\wheels\f1\e4\16\4981ca97c2d65106b49861e0b35e2660695be7219a2d351ee0
Successfully built apptools envisage pyface traits traitsui configobj
Failed to build mayavi
Installing collected packages: traits, pyface, traitsui, configobj, apptools, envisage, pygments, vtk, mayavi
  WARNING: The script pygmentize.exe is installed in 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Running setup.py install for mayavi ... done
ERROR: Could not install packages due to an EnvironmentError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '"C:'

WARNING: You are using pip version 19.2.1, however version 19.2.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

**Comment by RossBoylan** [comment]
Despite the apparent errors, things may be OK.

1. Running install for vtk and mayavi a second time says everything is installed already.
2. mayavi2 -t reports nothing.  Not sure if that means no errors, or no tests run.
3. mayavi2 launches the GUI.

`nosetests` doesn't seem to be installed, probably because the installation was not from source.

I also updated pip before the following transcript:
```
C:\windows\system32>py -3-64 -m pip install vtk
Requirement already satisfied: vtk in c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages (8.1.2)

C:\windows\system32>py -3-64 -m pip install mayavi
Requirement already satisfied: mayavi in c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages (4.7.1)
Requirement already satisfied: apptools in c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages (from mayavi) (4.4.0)
Requirement already satisfied: envisage in c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages (from mayavi) (4.7.2)
Requirement already satisfied: numpy in c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages (from mayavi) (1.16.3)
Requirement already satisfied: pyface>=6.1.1 in c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages (from mayavi) (6.1.2)
Requirement already satisfied: pygments in c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages (from mayavi) (2.4.2)
Requirement already satisfied: traits>=4.6.0 in c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages (from mayavi) (5.1.2)
Requirement already satisfied: traitsui>=6.0.0 in c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages (from mayavi) (6.1.2)
Requirement already satisfied: vtk in c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages (from mayavi) (8.1.2)
Requirement already satisfied: configobj in c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages (from apptools->mayavi) (5.0.6)
Requirement already satisfied: six in c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages (from traits>=4.6.0->mayavi) (1.12.0)

C:\windows\system32>cd "\Program files (x86)\Microsoft Visual Studio\Shared\Python37_64\Scripts"

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Scripts>mayavi2 -t

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Scripts>mayavi2
```

**Comment by prabhuramachandran** [comment]
Yes, this is due to the way pip figures out dependencies (for packages with traditional setup.py based requirements), it needs to try an installation first and then install the dependencies.  So what happens is that it tries to install mayavi without vtk, fails and then installs vtk and re-installs mayavi and that works in the end.  Unfortunately, this means you need to see the long log of messages rather carefully.
