### ISSUE TITLE
Exception occurred in traits notification handler. When run command mayavi2

### ISSUE THREAD

**Issue by shivak3** [enthought/mayavi#838]
**PLEASE help me What/ Where to check to fix this error.**

usr/local/lib64/python3.6/site-packages/traits/etsconfig/etsconfig.py:420: UserWarning: Environment variable "HOME" not set, setting home directory to /tmp
  % (environment_variable, parent_directory)
Exception occurred in traits notification handler.
Please check the log file for details.
Exception occurred in traits notification handler for object: <mayavi.plugins.mayavi_ui_plugin.MayaviUIPlugin object at 0x7f92bbecbaf0>, trait: application, old value: None, new value: <mayavi.plugins.mayavi_workbench_application.MayaviWorkbenchApplication object at 0x7f92bbecbd58>
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/traits/trait_notifiers.py", line 654, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/usr/local/lib64/python3.6/site-packages/traits/trait_notifiers.py", line 553, in dispatch
    handler(*args)
  File "/usr/local/lib64/python3.6/site-packages/traits/traits_listener.py", line 498, in handle_simple
    self.next.register(new)
  File "/usr/local/lib64/python3.6/site-packages/traits/traits_listener.py", line 464, in register
    value = getattr(self, type)(new, name, False)
  File "/usr/local/lib64/python3.6/site-packages/traits/traits_listener.py", line 738, in _register_simple
    return next.register(getattr(object, name))
  File "/usr/local/lib/python3.6/site-packages/envisage/ui/workbench/workbench_application.py", line 140, in _gui_default
    return GUI(splash_screen=self.splash_screen)
  File "/usr/local/lib64/python3.6/site-packages/mayavi/plugins/mayavi_workbench_application.py", line 121, in _splash_screen_default
    show_log_messages = True,
  File "/usr/local/lib/python3.6/site-packages/pyface/base_toolkit.py", line 178, in __init__
    raise NotImplementedError(msg % (toolkit, package, name))
NotImplementedError: the null pyface.ui.null backend doesn't implement splash_screen:SplashScreen
Exception occurred in traits notification handler for object: <mayavi.scripts.mayavi2.MayaviApp object at 0x7f92bc0519e8>, trait: application, old value: None, new value: <mayavi.plugins.mayavi_workbench_application.MayaviWorkbenchApplication object at 0x7f92bbecbd58>
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/traits/trait_notifiers.py", line 654, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/usr/local/lib64/python3.6/site-packages/traits/trait_notifiers.py", line 553, in dispatch
    handler(*args)
  File "/usr/local/lib64/python3.6/site-packages/traits/traits_listener.py", line 498, in handle_simple
    self.next.register(new)
  File "/usr/local/lib64/python3.6/site-packages/traits/traits_listener.py", line 464, in register
    value = getattr(self, type)(new, name, False)
  File "/usr/local/lib64/python3.6/site-packages/traits/traits_listener.py", line 738, in _register_simple
    return next.register(getattr(object, name))
  File "/usr/local/lib/python3.6/site-packages/envisage/ui/workbench/workbench_application.py", line 140, in _gui_default
    return GUI(splash_screen=self.splash_screen)
  File "/usr/local/lib64/python3.6/site-packages/mayavi/plugins/mayavi_workbench_application.py", line 121, in _splash_screen_default
    show_log_messages = True,
  File "/usr/local/lib/python3.6/site-packages/pyface/base_toolkit.py", line 178, in __init__
    raise NotImplementedError(msg % (toolkit, package, name))
NotImplementedError: the null pyface.ui.null backend doesn't implement splash_screen:SplashScreen
Traceback (most recent call last):
  File "/usr/local/bin/mayavi2", line 11, in <module>
    load_entry_point('mayavi==4.7.1', 'gui_scripts', 'mayavi2')()
  File "/usr/local/lib64/python3.6/site-packages/mayavi/scripts/mayavi2.py", line 602, in main
    mayavi.main(sys.argv[1:])
  File "/usr/local/lib64/python3.6/site-packages/mayavi/plugins/app.py", line 195, in main
    app.run()
  File "/usr/local/lib64/python3.6/site-packages/mayavi/plugins/mayavi_workbench_application.py", line 73, in run
    gui = self.gui
  File "/usr/local/lib/python3.6/site-packages/envisage/ui/workbench/workbench_application.py", line 140, in _gui_default
    return GUI(splash_screen=self.splash_screen)
  File "/usr/local/lib64/python3.6/site-packages/mayavi/plugins/mayavi_workbench_application.py", line 121, in _splash_screen_default
    show_log_messages = True,
  File "/usr/local/lib/python3.6/site-packages/pyface/base_toolkit.py", line 178, in __init__
    raise NotImplementedError(msg % (toolkit, package, name))
NotImplementedError: the null pyface.ui.null backend doesn't implement splash_screen:SplashScreen

**Comment by savantas** [comment]
I get the same error on CentOS 7 when running this example:
http://docs.enthought.com/mayavi/mayavi/auto/example_mlab_interactive_dialog.html#example-mlab-interactive-dialog
Anyone knows how to solve this?

**Comment by shivak3** [comment]
Hi Savantas,
Just want to check that  did you set Python home environment to Python3.6 or check still it is pointing python 2.7 or 2.x (old version).

**Comment by zhengpuchen** [comment]
Hi,

I met the same problem, I am sure that the environment is Python3.6.

Zhengpu

**Comment by rahulporuri** [comment]
> NotImplementedError: the null pyface.ui.null backend doesn't implement splash_screen:SplashScreen

The error message is a little cryptic but it is pointing to the fact that no GUI toolkit/backend package is installed/available in the environment. Did you install any one of the following packages - PyQt4/PyQt5/PySide2/WxPython4? In the absence of a toolkit backend, the `null` toolkit is implicitly selected and we see the error because the `null` toolkit cannot create GUI windows.

If a backend package has been installed in the environment, can you check what the `ETS_TOOLKIT` and `QT_API` environment variables are set to? If they are already set, can you unset the environment variables and see if the error persists? Or, you can optionally set the `ETS_TOOLKIT` and `QT_API` environment variables e.g. `ETS_TOOLKIT` should be `qt` and QT_API should be `PyQt5` if the PyQt5 toolkit/backend is used.

**Comment by WyomingWill** [comment]
Your suggestion just worked for me on Linux Mint 20:

export ETS_TOOLKIT=qt
export QT_API=pyqt5

Now Mayavi starts up correctly. Thank you.

**Comment by shivak3** [comment]
Hi @rahulporuri & @prabhuramachandran,

I see the same "Exception occurred in traits notification handler" error on my Production Server(RHEL7).

I followed the environment variable set up. But, it didn't work me.

Could you please help me to fix this error? TIA.

**Comment by rahulporuri** [comment]
@shivak3 can you give us some more information on what you're seeing?

**Comment by shivak3** [comment]
Hi @rahulporuri 

Thank you for your reply. 

I am using Mayavi with conda setup on RHEL 7 system.

I had PyQT 5.12.3 version when Mayavi worked fine without any issues.
~~~
(base) [root@RHEL7 ~] conda list | grep pyqt
pyqt                      5.9.2            py37h05f1152_2  
pyqt5                     5.12.3                   pypi_0    pypi
pyqt5-sip                 12.7.1                   pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
~~~

And, I have a requirement to install PyQt5-Qt5 5.15.2 version. Then, I installed it using "pip" without activating the conda environment.
~~~
[root@RHEL7 ~] pip install PyQt5==5.15.2
~~~

I tried to run mayavi after installing 5.15.2, Then I see error very lengthy error message

~~~
(base) [root@RHEL7] mayavi2
/usr/bin/anaconda3/lib/python3.7/site-packages/traits/etsconfig/etsconfig.py:420: UserWarning: Environment variable "HOME" not set, setting home directory to /tmp
  % (environment_variable, parent_directory)
Exception occurred in traits notification handler.
Please check the log file for details.
Exception occurred in traits notification handler for object: <mayavi.plugins.mayavi_ui_plugin.MayaviUIPlugin object at 0x7fecdd61e830>, trait: application, old value: None, new value: <mayavi.plugins.mayavi_workbench_application.MayaviWorkbenchApplication object at 0x7fecdd61ee90>
Traceback (most recent call last):
  File "/usr/bin/anaconda3/lib/python3.7/site-packages/traits/trait_notifiers.py", line 654, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/usr/bin/anaconda3/lib/python3.7/site-packages/traits/trait_notifiers.py", line 553, in dispatch
    handler(*args)
  File "/usr/bin/anaconda3/lib/python3.7/site-packages/traits/traits_listener.py", line 498, in handle_simple
    self.next.register(new)
  File "/usr/bin/anaconda3/lib/python3.7/site-packages/traits/traits_listener.py", line 464, in register
    value = getattr(self, type)(new, name, False)
  File "/usr/bin/anaconda3/lib/python3.7/site-packages/traits/traits_listener.py", line 738, in _register_simple
    return next.register(getattr(object, name))
  File "/usr/bin/anaconda3/lib/python3.7/site-packages/envisage/ui/workbench/workbench_application.py", line 140, in _gui_default
    return GUI(splash_screen=self.splash_screen)
  File "/usr/bin/anaconda3/lib/python3.7/site-packages/mayavi/plugins/mayavi_workbench_application.py", line 121, in _splash_screen_default
    show_log_messages = True,
  File "/usr/bin/anaconda3/lib/python3.7/site-packages/pyface/base_toolkit.py", line 178, in __init__
    raise NotImplementedError(msg % (toolkit, package, name))
NotImplementedError: the null pyface.ui.null backend doesn't implement splash_screen:SplashScreen
Exception occurred in traits notification handler for object: <mayavi.scripts.mayavi2.MayaviApp object at 0x7fed16921230>, trait: application, old value: None, new value: <mayavi.plugins.mayavi_workbench_application.MayaviWorkbenchApplication object at 0x7fecdd61ee90>
Traceback (most recent call last):
  File "/usr/bin/anaconda3/lib/python3.7/site-packages/traits/trait_notifiers.py", line 654, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/usr/bin/anaconda3/lib/python3.7/site-packages/traits/trait_notifiers.py", line 553, in dispatch
    handler(*args)
  File "/usr/bin/anaconda3/lib/python3.7/site-packages/traits/traits_listener.py", line 498, in handle_simple
    self.next.register(new)
  File "/usr/bin/anaconda3/lib/python3.7/site-packages/traits/traits_listener.py", line 464, in register
    value = getattr(self, type)(new, name, False)
  File "/usr/bin/anaconda3/lib/python3.7/site-packages/traits/traits_listener.py", line 738, in _register_simple
    return next.register(getattr(object, name))
  File "/usr/bin/anaconda3/lib/python3.7/site-packages/envisage/ui/workbench/workbench_application.py", line 140, in _gui_default
    return GUI(splash_screen=self.splash_screen)
  File "/usr/bin/anaconda3/lib/python3.7/site-packages/mayavi/plugins/mayavi_workbench_application.py", line 121, in _splash_screen_default
    show_log_messages = True,
  File "/usr/bin/anaconda3/lib/python3.7/site-packages/pyface/base_toolkit.py", line 178, in __init__
    raise NotImplementedError(msg % (toolkit, package, name))
NotImplementedError: the null pyface.ui.null backend doesn't implement splash_screen:SplashScreen
Traceback (most recent call last):
  File "/usr/bin/anaconda3/bin/mayavi2", line 11, in <module>
    load_entry_point('mayavi==4.7.1', 'gui_scripts', 'mayavi2')()
  File "/usr/bin/anaconda3/lib/python3.7/site-packages/mayavi/scripts/mayavi2.py", line 602, in main
    mayavi.main(sys.argv[1:])
  File "/usr/bin/anaconda3/lib/python3.7/site-packages/mayavi/plugins/app.py", line 195, in main
    app.run()
  File "/usr/bin/anaconda3/lib/python3.7/site-packages/mayavi/plugins/mayavi_workbench_application.py", line 73, in run
    gui = self.gui
  File "/usr/bin/anaconda3/lib/python3.7/site-packages/envisage/ui/workbench/workbench_application.py", line 140, in _gui_default
    return GUI(splash_screen=self.splash_screen)
  File "/usr/bin/anaconda3/lib/python3.7/site-packages/mayavi/plugins/mayavi_workbench_application.py", line 121, in _splash_screen_default
    show_log_messages = True,
  File "/usr/bin/anaconda3/lib/python3.7/site-packages/pyface/base_toolkit.py", line 178, in __init__
    raise NotImplementedError(msg % (toolkit, package, name))
NotImplementedError: the null pyface.ui.null backend doesn't implement splash_screen:SplashScreen
~~~

Then, I tried with environment variables ETS_TOOLKIT=qt and QT_API=pyqt5 setup. But, failed to load Mayavi.
 
Present QT related info from environment on the system.

~~~
[root@RHEL7 ~]$ env | grep QT
QTDIR=/usr/lib64/qt4
QTINC=/usr/lib64/qt4/include
QT_GRAPHICSSYSTEM_CHECKED=1
QT_IM_MODULE=ibus
QTLIB=/usr/lib64/qt4/lib
QT_PLUGIN_PATH=/usr/lib64/kde4/plugins:/usr/lib/kde4/plugins
~~~

Posted the above error **"@enthought/traits" forum**, They say that this is not a bug with traits.

Please help me on this. TIA.
