### ISSUE TITLE
Intermittent test failure (TraitError) in test_all_instantiable

### ISSUE THREAD

**Issue by mdickinson** [enthought/mayavi#861]
CI runs fail occasionally with a test failure resembling that below. The bounds for the trait are the same each time, but I've seen different values appear in the `TraitError` (most recently, -1e-77), suggesting that that value may have come from something undefined.

```
======================================================================
FAIL: Test if all the TVTK classes can be instantiated
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/enthought/mayavi/tvtk/tests/test_tvtk.py", line 934, in test_all_instantiable
    raise AssertionError(message.format(''.join(errors)))
AssertionError: Not all classes could be instantiated:
Traceback (most recent call last):
  File "/home/travis/build/enthought/mayavi/tvtk/tests/test_tvtk.py", line 929, in test_all_instantiable
    tvtk_klass()
  File "tvtk_classes/euclidean_cluster_extraction.py", line 74, in __init__
    tvtk_base.TVTKBase.__init__(self, vtk.vtkEuclideanClusterExtraction, obj, update, **traits)
  File "/home/travis/build/enthought/mayavi/tvtk/tvtk_base.py", line 367, in __init__
    self.update_traits()
  File "/home/travis/build/enthought/mayavi/tvtk/tvtk_base.py", line 520, in update_traits
    setattr(self, name, val)
  File "/home/travis/.edm/envs/edm/lib/python2.7/site-packages/traits/trait_handlers.py", line 236, in error
    object, name, self.full_info(object, name, value), value
TraitError: The 'radius' trait of an EuclideanClusterExtraction instance must be 0.0 <= a floating point number <= 9.99999968029e+37, but a value of 1e+299 <type 'float'> was specified.
```

**Comment by mdickinson** [comment]
It would be good to investigate and fix this, else it'll continue to be an impediment to efficient development.
