### ISSUE TITLE
mayavi2 build error in Debian with Python 3.7

### ISSUE THREAD

**Issue by varunhiremath** [enthought/mayavi#873]
Hi @prabhuramachandran,

Sorry for the delay, but I have finally gotten to updating mayavi2 in Debian. I am trying to build the latest version 4.7.1 in Debian using python 3.7, but the build fails with the below error. Build dependencies include python3-vtk7 version 7.1.1. Please let me know if you need any other info.

```
dpkg-buildpackage: info: source package mayavi2
dpkg-buildpackage: info: source version 4.7.1-1
dpkg-buildpackage: info: source distribution UNRELEASED
dpkg-buildpackage: info: source changed by OndÅ™ej NovÃ½ <onovy@debian.org>
 dpkg-source --before-build .
dpkg-buildpackage: info: host architecture amd64
 fakeroot debian/rules clean
dh clean --with python3 --buildsystem=pybuild
   dh_auto_clean -O--buildsystem=pybuild
I: pybuild base:217: python3.7 setup.py clean 
running clean
removing '/build/mayavi2-4.7.1/.pybuild/cpython3_3.7/build' (and everything under it)
'build/bdist.linux-amd64' does not exist -- can't clean it
'build/scripts.linux-amd64-3.7' does not exist -- can't clean it
   dh_autoreconf_clean -O--buildsystem=pybuild
   debian/rules override_dh_clean
make[1]: Entering directory '/build/mayavi2-4.7.1'
dh_clean
rm -rf ./mayavi/images/m2_about.jpg
make[1]: Leaving directory '/build/mayavi2-4.7.1'
 dpkg-source -b .
dpkg-source: info: using source format '3.0 (quilt)'
dpkg-source: info: building mayavi2 using existing ./mayavi2_4.7.1.orig.tar.bz2
dpkg-source: info: using patch list from debian/patches/series
dpkg-source: warning: ignoring deletion of file mayavi/images/m2_about.jpg, use --include-removal to override
dpkg-source: info: building mayavi2 in mayavi2_4.7.1-1.debian.tar.xz
dpkg-source: info: building mayavi2 in mayavi2_4.7.1-1.dsc
 debian/rules build
dh build --with python3 --buildsystem=pybuild
   dh_update_autotools_config -O--buildsystem=pybuild
   dh_autoreconf -O--buildsystem=pybuild
   dh_auto_configure -O--buildsystem=pybuild
I: pybuild base:217: python3.7 setup.py config 
running config
   dh_auto_build -O--buildsystem=pybuild
I: pybuild base:217: /usr/bin/python3 setup.py build 
running build
----------------------------------------------------------------------
Building TVTK classes... Traceback (most recent call last):
  File "setup.py", line 474, in <module>
  File "/usr/lib/python3/dist-packages/numpy/distutils/core.py", line 171, in setup
    return old_setup(**new_attr)
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 268, in run
  File "setup.py", line 254, in build_tvtk_classes_zip
  File "tvtk/setup.py", line 99, in gen_tvtk_classes_zip
    gen.generate_code()
  File "/build/mayavi2-4.7.1/tvtk/code_gen.py", line 131, in generate_code
    self._write_wrapper_class(node, tvtk_name)
  File "/build/mayavi2-4.7.1/tvtk/code_gen.py", line 221, in _write_wrapper_class
    self.wrap_gen.generate_code(node, out)
  File "/build/mayavi2-4.7.1/tvtk/wrapper_gen.py", line 250, in generate_code
    self._gen_methods(node, out)
  File "/build/mayavi2-4.7.1/tvtk/wrapper_gen.py", line 371, in _gen_methods
    self._gen_get_methods(klass, out)
  File "/build/mayavi2-4.7.1/tvtk/wrapper_gen.py", line 919, in _gen_get_methods
    if len(sig) == 1 and sig[0][1] is None:
TypeError: object of type 'NoneType' has no len()
E: pybuild pybuild:341: build: plugin distutils failed with: exit code=1: /usr/bin/python3 setup.py build 
dh_auto_build: pybuild --build -i python{version} -p 3.7 returned exit code 13
```

Thanks,
Varun

**Comment by varunhiremath** [comment]
Sorry, this build error was cased by an old vtk patch included in the debian package. Once I removed that patch mayavi2 builds fine now. Thanks.

**Comment by prabhuramachandran** [comment]
Great, relieved to hear this, thanks for the update!
