### ISSUE TITLE
Test Errors/Failures with Python 3.7 & VTK 7

### ISSUE THREAD

**Issue by swt2c** [enthought/mayavi#878]
I'm seeing a few errors & failures when running the unit tests under Python 3.7 and VTK 7, see below.  I don't see this particular combination in the Travis configuration, so perhaps it has not been tested?

Python: 3.7.6
vtk: 7.1.1
mayavi: 4.7.1

```
======================================================================
ERROR: test_decorated_scene (test_garbage_collection.TestTVTKGarbageCollection)
Tests if Decorated Scene can be garbage collected.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/talbert/debian-packaging/mayavi2/mayavi2/tvtk/tests/test_garbage_collection.py", line 50, in test_decorated_scene
    self.check_object_garbage_collected(create_fn, close_fn)
  File "/usr/lib/python3/dist-packages/tvtk/tests/common.py", line 61, in check_object_garbage_collected
    self.assertTrue(object_collected[0])
IndexError: list index out of range

======================================================================
ERROR: test_tvtk_scene_garbage_collected (test_tvtk_scene.TestTVTKScene)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/talbert/debian-packaging/mayavi2/mayavi2/tvtk/tests/test_tvtk_scene.py", line 36, in test_tvtk_scene_garbage_collected
    scene_weakref = do()
  File "/home/talbert/debian-packaging/mayavi2/mayavi2/tvtk/tests/test_tvtk_scene.py", line 28, in do
    scene = TVTKScene()
  File "/usr/lib/python3/dist-packages/tvtk/pyface/tvtk_scene.py", line 222, in __init__
    self.control = self._create_control(parent)
  File "/usr/lib/python3/dist-packages/tvtk/pyface/tvtk_scene.py", line 815, in _create_control
    renwin = self._renwin = tvtk.RenderWindow()
  File "/usr/lib/python3/dist-packages/tvtk/tvtk_classes.zip/tvtk_classes/render_window.py", line 62, in __init__
    tvtk_base.TVTKBase.__init__(self, vtk.vtkRenderWindow, obj, update, **traits)
  File "/usr/lib/python3/dist-packages/tvtk/tvtk_base.py", line 362, in __init__
    super(TVTKBase, self).__init__(**traits)
TypeError: super(type, obj): obj must be an instance or subtype of type

======================================================================
ERROR: test_arrow (test_visual.TestVisual)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/talbert/debian-packaging/mayavi2/mayavi2/tvtk/tests/test_visual.py", line 178, in test_arrow
    a = visual.arrow()
  File "/usr/lib/python3/dist-packages/tvtk/tools/visual.py", line 1576, in __init__
    self.property = self.actor.property
  File "/usr/lib/python3/dist-packages/traits/trait_types.py", line 3154, in create_default_value
    return klass(*args[1:], **kw)
  File "/usr/lib/python3/dist-packages/tvtk/tvtk_classes.zip/tvtk_classes/actor.py", line 53, in __init__
    tvtk_base.TVTKBase.__init__(self, vtk.vtkActor, obj, update, **traits)
  File "/usr/lib/python3/dist-packages/tvtk/tvtk_base.py", line 362, in __init__
    super(TVTKBase, self).__init__(**traits)
TypeError: super(type, obj): obj must be an instance or subtype of type

======================================================================
ERROR: test_box (test_visual.TestVisual)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/talbert/debian-packaging/mayavi2/mayavi2/tvtk/tests/test_visual.py", line 155, in test_box
    b = visual.box(size=tuple(sz), pos=pos)
  File "/usr/lib/python3/dist-packages/tvtk/tools/visual.py", line 1414, in __init__
    self.property = self.actor.property
  File "/usr/lib/python3/dist-packages/traits/trait_types.py", line 3154, in create_default_value
    return klass(*args[1:], **kw)
  File "/usr/lib/python3/dist-packages/tvtk/tvtk_classes.zip/tvtk_classes/actor.py", line 53, in __init__
    tvtk_base.TVTKBase.__init__(self, vtk.vtkActor, obj, update, **traits)
  File "/usr/lib/python3/dist-packages/tvtk/tvtk_base.py", line 362, in __init__
    super(TVTKBase, self).__init__(**traits)
TypeError: super(type, obj): obj must be an instance or subtype of type

======================================================================
ERROR: test_cone (test_visual.TestVisual)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/talbert/debian-packaging/mayavi2/mayavi2/tvtk/tests/test_visual.py", line 86, in test_cone
    c = visual.cone()
  File "/usr/lib/python3/dist-packages/tvtk/tools/visual.py", line 945, in __init__
    self.property = self.actor.property
  File "/usr/lib/python3/dist-packages/traits/trait_types.py", line 3154, in create_default_value
    return klass(*args[1:], **kw)
  File "/usr/lib/python3/dist-packages/tvtk/tvtk_classes.zip/tvtk_classes/actor.py", line 53, in __init__
    tvtk_base.TVTKBase.__init__(self, vtk.vtkActor, obj, update, **traits)
  File "/usr/lib/python3/dist-packages/tvtk/tvtk_base.py", line 362, in __init__
    super(TVTKBase, self).__init__(**traits)
TypeError: super(type, obj): obj must be an instance or subtype of type

======================================================================
ERROR: test_curve (test_visual.TestVisual)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/talbert/debian-packaging/mayavi2/mayavi2/tvtk/tests/test_visual.py", line 234, in test_curve
    c = visual.curve(points=[[0.,0.,0.],[1.,1.,1.]], pos=(1.,1.,1.))
  File "/usr/lib/python3/dist-packages/tvtk/tools/visual.py", line 574, in __init__
    self.property = self.actor.property
  File "/usr/lib/python3/dist-packages/traits/trait_types.py", line 3154, in create_default_value
    return klass(*args[1:], **kw)
  File "/usr/lib/python3/dist-packages/tvtk/tvtk_classes.zip/tvtk_classes/actor.py", line 53, in __init__
    tvtk_base.TVTKBase.__init__(self, vtk.vtkActor, obj, update, **traits)
  File "/usr/lib/python3/dist-packages/tvtk/tvtk_base.py", line 362, in __init__
    super(TVTKBase, self).__init__(**traits)
TypeError: super(type, obj): obj must be an instance or subtype of type

======================================================================
ERROR: test_cylinder (test_visual.TestVisual)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/talbert/debian-packaging/mayavi2/mayavi2/tvtk/tests/test_visual.py", line 136, in test_cylinder
    c = visual.cylinder(radius=0.5, length=2, pos=(1., 1, 1))
  File "/usr/lib/python3/dist-packages/tvtk/tools/visual.py", line 1248, in __init__
    self.property = self.actor.property
  File "/usr/lib/python3/dist-packages/traits/trait_types.py", line 3154, in create_default_value
    return klass(*args[1:], **kw)
  File "/usr/lib/python3/dist-packages/tvtk/tvtk_classes.zip/tvtk_classes/actor.py", line 53, in __init__
    tvtk_base.TVTKBase.__init__(self, vtk.vtkActor, obj, update, **traits)
  File "/usr/lib/python3/dist-packages/tvtk/tvtk_base.py", line 362, in __init__
    super(TVTKBase, self).__init__(**traits)
TypeError: super(type, obj): obj must be an instance or subtype of type

======================================================================
ERROR: test_ellipsoid (test_visual.TestVisual)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/talbert/debian-packaging/mayavi2/mayavi2/tvtk/tests/test_visual.py", line 201, in test_ellipsoid
    s = visual.ellipsoid(size=(1.0, 1.0, 1.0), pos=(1., 1., 1.))
  File "/usr/lib/python3/dist-packages/tvtk/tools/visual.py", line 1977, in __init__
    self.property = self.actor.property
  File "/usr/lib/python3/dist-packages/traits/trait_types.py", line 3154, in create_default_value
    return klass(*args[1:], **kw)
  File "/usr/lib/python3/dist-packages/tvtk/tvtk_classes.zip/tvtk_classes/actor.py", line 53, in __init__
    tvtk_base.TVTKBase.__init__(self, vtk.vtkActor, obj, update, **traits)
  File "/usr/lib/python3/dist-packages/tvtk/tvtk_base.py", line 362, in __init__
    super(TVTKBase, self).__init__(**traits)
TypeError: super(type, obj): obj must be an instance or subtype of type

======================================================================
ERROR: test_frame (test_visual.TestVisual)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/talbert/debian-packaging/mayavi2/mayavi2/tvtk/tests/test_visual.py", line 268, in test_frame
    s = visual.sphere()
  File "/usr/lib/python3/dist-packages/tvtk/tools/visual.py", line 1093, in __init__
    self.property = self.actor.property
  File "/usr/lib/python3/dist-packages/traits/trait_types.py", line 3154, in create_default_value
    return klass(*args[1:], **kw)
  File "/usr/lib/python3/dist-packages/tvtk/tvtk_classes.zip/tvtk_classes/actor.py", line 53, in __init__
    tvtk_base.TVTKBase.__init__(self, vtk.vtkActor, obj, update, **traits)
  File "/usr/lib/python3/dist-packages/tvtk/tvtk_base.py", line 362, in __init__
    super(TVTKBase, self).__init__(**traits)
TypeError: super(type, obj): obj must be an instance or subtype of type

======================================================================
ERROR: test_helix (test_visual.TestVisual)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/talbert/debian-packaging/mayavi2/mayavi2/tvtk/tests/test_visual.py", line 248, in test_helix
    h = visual.helix(pos=(1., 1.,1.))
  File "/usr/lib/python3/dist-packages/tvtk/tools/visual.py", line 1747, in __init__
    self.property = self.actor.property
  File "/usr/lib/python3/dist-packages/traits/trait_types.py", line 3154, in create_default_value
    return klass(*args[1:], **kw)
  File "/usr/lib/python3/dist-packages/tvtk/tvtk_classes.zip/tvtk_classes/actor.py", line 53, in __init__
    tvtk_base.TVTKBase.__init__(self, vtk.vtkActor, obj, update, **traits)
  File "/usr/lib/python3/dist-packages/tvtk/tvtk_base.py", line 362, in __init__
    super(TVTKBase, self).__init__(**traits)
TypeError: super(type, obj): obj must be an instance or subtype of type

======================================================================
ERROR: test_ring (test_visual.TestVisual)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/talbert/debian-packaging/mayavi2/mayavi2/tvtk/tests/test_visual.py", line 50, in test_ring
    r = visual.ring()
  File "/usr/lib/python3/dist-packages/tvtk/tools/visual.py", line 761, in __init__
    self.property = self.actor.property
  File "/usr/lib/python3/dist-packages/traits/trait_types.py", line 3154, in create_default_value
    return klass(*args[1:], **kw)
  File "/usr/lib/python3/dist-packages/tvtk/tvtk_classes.zip/tvtk_classes/actor.py", line 53, in __init__
    tvtk_base.TVTKBase.__init__(self, vtk.vtkActor, obj, update, **traits)
  File "/usr/lib/python3/dist-packages/tvtk/tvtk_base.py", line 362, in __init__
    super(TVTKBase, self).__init__(**traits)
TypeError: super(type, obj): obj must be an instance or subtype of type

======================================================================
ERROR: test_sphere (test_visual.TestVisual)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/talbert/debian-packaging/mayavi2/mayavi2/tvtk/tests/test_visual.py", line 112, in test_sphere
    s = visual.sphere()
  File "/usr/lib/python3/dist-packages/tvtk/tools/visual.py", line 1093, in __init__
    self.property = self.actor.property
  File "/usr/lib/python3/dist-packages/traits/trait_types.py", line 3154, in create_default_value
    return klass(*args[1:], **kw)
  File "/usr/lib/python3/dist-packages/tvtk/tvtk_classes.zip/tvtk_classes/actor.py", line 53, in __init__
    tvtk_base.TVTKBase.__init__(self, vtk.vtkActor, obj, update, **traits)
  File "/usr/lib/python3/dist-packages/tvtk/tvtk_base.py", line 362, in __init__
    super(TVTKBase, self).__init__(**traits)
TypeError: super(type, obj): obj must be an instance or subtype of type

======================================================================
FAIL: test_basic_vtk (test_class_tree.TestClassTree)
Basic tests for the VTK module.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/talbert/debian-packaging/mayavi2/mayavi2/tvtk/tests/test_class_tree.py", line 86, in test_basic_vtk
    self.assertEqual(names, expect)
AssertionError: Lists differ: ['object'] != ['object', 'vtkColor3', 'vtkColor4', 'vtkDenseArra[146 chars]or3']

Second list contains 12 additional elements.
First extra element 1:
'vtkColor3'

- ['object']
?          ^

+ ['object',
?          ^

+  'vtkColor3',
+  'vtkColor4',
+  'vtkDenseArray',
+  'vtkQuaternion',
+  'vtkRect',
+  'vtkSparseArray',
+  'vtkTuple',
+  'vtkTypedArray',
+  'vtkVariantStrictWeakOrderKey',
+  'vtkVector',
+  'vtkVector2',
+  'vtkVector3']

======================================================================
FAIL: test_custom (test_tvtk.TestTVTK)
Test if custom modules can be imported.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/talbert/debian-packaging/mayavi2/mayavi2/tvtk/tests/test_tvtk.py", line 143, in test_custom
    self.assertEqual(r.__class__.__bases__, expect)
AssertionError: Tuples differ: (<class 'object'>,) != ()

First tuple contains 1 additional elements.
First extra element 0:
<class 'object'>

- (<class 'object'>,)
+ ()

----------------------------------------------------------------------
Ran 138 tests in 29.704s

FAILED (failures=2, errors=12, skipped=4)
```

**Comment by aconceicao** [comment]
I also had problems running the tests.

```
> ----------------------------------------------------------------------
> Running TVTK tests.
> Traceback (most recent call last):
>   File "C:\Users\concea\AppData\Local\Continuum\anaconda3\Scripts\mayavi2-script.py", line 6, in <module>
>     from mayavi.scripts.mayavi2 import main
>   File "C:\Users\concea\AppData\Local\Continuum\anaconda3\lib\site-packages\mayavi\scripts\mayavi2.py", line 427, in <module>
>     runtests.main()
>   File "C:\Users\concea\AppData\Local\Continuum\anaconda3\lib\site-packages\mayavi\tests\runtests.py", line 225, in main
>     status = m2_tests(verbose)
>   File "C:\Users\concea\AppData\Local\Continuum\anaconda3\lib\site-packages\mayavi\tests\runtests.py", line 179, in m2_tests
>     err = run(tests, verbose)
>   File "C:\Users\concea\AppData\Local\Continuum\anaconda3\lib\site-packages\mayavi\tests\runtests.py", line 124, in run
>     res = re.search('Ran\s*(\d*)\s*test', err)
>   File "C:\Users\concea\AppData\Local\Continuum\anaconda3\lib\re.py", line 183, in search
>     return _compile(pattern, flags).search(string)
> TypeError: cannot use a string pattern on a bytes-like object 
```
Has anyone find how to fix it?
I am using python  3.7.3 and VTK 8.2

**Comment by mdickinson** [comment]
@aconceicao Thanks for the report. This is a different type of failure from the one reported in this issue. To keep things clean, I've opened #885 to track the issue you reported.

**Comment by witignite** [comment]
@swt2c , What command did you use during setup to point `setup.py` to specific version of VTK?

**Comment by swt2c** [comment]
> @swt2c , What command did you use during setup to point setup.py to specific version of VTK?

I was building mayavi in a chroot on Debian Unstable which still has VTK 7.
