### ISSUE TITLE
Mayavi2 fails to start with with python 3.8

### ISSUE THREAD

**Issue by pirogronian** [enthought/mayavi#882]
Fresh installation.
OS: Arch Linux
Mayavi version: 4.7.1
Python version: 3.8.1
Console trace:
```
Traceback (most recent call last):
  File "/usr/bin/mayavi2", line 11, in <module>
    load_entry_point('mayavi==4.7.1', 'gui_scripts', 'mayavi2')()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.8/site-packages/mayavi/scripts/mayavi2.py", line 464, in <module>
    from mayavi.plugins.app import Mayavi, setup_logger
  File "/usr/lib/python3.8/site-packages/mayavi/plugins/app.py", line 19, in <module>
    from .mayavi_workbench_application import MayaviWorkbenchApplication
  File "/usr/lib/python3.8/site-packages/mayavi/plugins/mayavi_workbench_application.py", line 17, in <module>
    import mayavi.api
  File "/usr/lib/python3.8/site-packages/mayavi/api.py", line 2, in <module>
    from mayavi.core.engine import Engine
  File "/usr/lib/python3.8/site-packages/mayavi/core/engine.py", line 28, in <module>
    from mayavi.core.base import Base
  File "/usr/lib/python3.8/site-packages/mayavi/core/base.py", line 19, in <module>
    from tvtk.pyface.tvtk_scene import TVTKScene
  File "/usr/lib/python3.8/site-packages/tvtk/pyface/tvtk_scene.py", line 20, in <module>
    from tvtk.api import tvtk
  File "/usr/lib/python3.8/site-packages/tvtk/api.py", line 10, in <module>
    from tvtk.tvtk_access import tvtk
  File "/usr/lib/python3.8/site-packages/tvtk/tvtk_access.py", line 34, in <module>
    from tvtk.tvtk_classes.vtk_version import vtk_build_version
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 914, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1342, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1316, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1297, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 414, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 649, in spec_from_file_location
  File "<frozen zipimport>", line 191, in get_filename
  File "<frozen zipimport>", line 711, in _get_module_code
  File "<frozen zipimport>", line 611, in _unmarshal_code
NameError: name _boost'rap_external' is not defined
```

Not asked on Arch Linux bugtracker yet, but going to do it.

**Comment by pirogronian** [comment]
Solved with python 3.8.4.
