### ISSUE TITLE
unable to launch mayavi on os x x64

### ISSUE THREAD

**Issue by satra** [enthought/mayavi#9]
(devpype)[satra@robinhill ~]$ export ETS_TOOLKIT=qt4
(devpype)[satra@robinhill ~]$ mayavi2
Traceback (most recent call last):
  File "/Library/Frameworks/EPD64.framework/Versions/Current/bin/mayavi2", line 9, in <module>
    load_entry_point('Mayavi==3.4.2', 'console_scripts', 'mayavi2')()
  File "/Library/Frameworks/EPD64.framework/Versions/7.0/lib/python2.7/site-packages/Mayavi-3.4.2-py2.7-macosx-10.5-x86_64.egg/enthought/mayavi/scripts/mayavi2.py", line 649, in main
    mayavi.main(sys.argv[1:])
  File "/Library/Frameworks/EPD64.framework/Versions/7.0/lib/python2.7/site-packages/Mayavi-3.4.2-py2.7-macosx-10.5-x86_64.egg/enthought/mayavi/plugins/app.py", line 195, in main
    app.run()
  File "/Library/Frameworks/EPD64.framework/Versions/7.0/lib/python2.7/site-packages/Mayavi-3.4.2-py2.7-macosx-10.5-x86_64.egg/enthought/mayavi/plugins/mayavi_workbench_application.py", line 76, in run
    if self.start():
  File "/Library/Frameworks/EPD64.framework/Versions/7.0/lib/python2.7/site-packages/EnvisageCore-3.2.1-py2.7.egg/enthought/envisage/application.py", line 277, in start
    self.plugin_manager.start()
  File "/Library/Frameworks/EPD64.framework/Versions/7.0/lib/python2.7/site-packages/EnvisageCore-3.2.1-py2.7.egg/enthought/envisage/plugin_manager.py", line 105, in start
    map(lambda plugin: self.start_plugin(plugin), self._plugins)
  File "/Library/Frameworks/EPD64.framework/Versions/7.0/lib/python2.7/site-packages/EnvisageCore-3.2.1-py2.7.egg/enthought/envisage/plugin_manager.py", line 105, in <lambda>
    map(lambda plugin: self.start_plugin(plugin), self._plugins)
  File "/Library/Frameworks/EPD64.framework/Versions/7.0/lib/python2.7/site-packages/EnvisageCore-3.2.1-py2.7.egg/enthought/envisage/plugin_manager.py", line 115, in start_plugin
    plugin.activator.start_plugin(plugin)
  File "/Library/Frameworks/EPD64.framework/Versions/7.0/lib/python2.7/site-packages/EnvisageCore-3.2.1-py2.7.egg/enthought/envisage/plugin_activator.py", line 31, in start_plugin
    plugin.start()
  File "/Library/Frameworks/EPD64.framework/Versions/7.0/lib/python2.7/site-packages/EnvisageCore-3.2.1-py2.7.egg/enthought/envisage/core_plugin.py", line 145, in start
    self._load_preferences(self.application.preferences)
  File "/Library/Frameworks/EPD64.framework/Versions/7.0/lib/python2.7/site-packages/EnvisageCore-3.2.1-py2.7.egg/enthought/envisage/core_plugin.py", line 226, in _load_preferences
    f = resource_manager.file(resource_name)
  File "/Library/Frameworks/EPD64.framework/Versions/7.0/lib/python2.7/site-packages/EnvisageCore-3.2.1-py2.7.egg/enthought/envisage/resource/resource_manager.py", line 56, in file
    return protocol.file(address)
  File "/Library/Frameworks/EPD64.framework/Versions/7.0/lib/python2.7/site-packages/EnvisageCore-3.2.1-py2.7.egg/enthought/envisage/resource/package_resource_protocol.py", line 50, in file
    raise NoSuchResourceError(address)
enthought.envisage.resource.no_such_resource_error.NoSuchResourceError: traits.logger/plugin/preferences.ini

**Comment by stefanoborini** [comment]
@satra still relevant?

**Comment by satra** [comment]
@stefanoborini - thanks for the ping.
