### ISSUE TITLE
Issue with Python 2 ImportError

### ISSUE THREAD

**Issue by kaalessi** [enthought/mayavi#916]
I am getting `ImportError: cannot import name getfullargspec`. From my little bit of research, `getfullargspec` was an update to `getargspec` in Python3, but I am using Python 2.7, so I don't understand why I am getting this error. I have tried removing mayavi, and several other packets and reinstalling. mayavi works in python3, but I need to use Python 2 for my project.

The entire error printout is as follows: 
` Traceback (most recent call last):
  File "mayavi_test.py", line 3, in <module>
    from mayavi import mlab
  File "/home/user/.local/lib/python2.7/site-packages/mayavi/mlab.py", line 16, in <module>
    from mayavi.tools.camera import view, roll, yaw, pitch, move
  File "/home/user/.local/lib/python2.7/site-packages/mayavi/tools/camera.py", line 24, in <module>
    from .engine_manager import get_engine
  File "/home/user/.local/lib/python2.7/site-packages/mayavi/tools/engine_manager.py", line 12, in <module>
    from mayavi.preferences.api import preference_manager
  File "/home/user/.local/lib/python2.7/site-packages/mayavi/preferences/api.py", line 4, in <module>
    from .preference_manager import preference_manager
  File "/home/user/.local/lib/python2.7/site-packages/mayavi/preferences/preference_manager.py", line 29, in <module>
    from traitsui.api import View, Group, Item
  File "/home/user/.local/lib/python2.7/site-packages/traitsui/api.py", line 37, in <module>
    from .editors.api import (
  File "/home/user/.local/lib/python2.7/site-packages/traitsui/editors/__init__.py", line 26, in <module>
    from .api import (
  File "/home/user/.local/lib/python2.7/site-packages/traitsui/editors/api.py", line 6, in <module>
    from .array_editor import ArrayEditor
  File "/home/user/.local/lib/python2.7/site-packages/traitsui/editors/array_editor.py", line 34, in <module>
    from ..view import View
  File "/home/user/.local/lib/python2.7/site-packages/traitsui/view.py", line 41, in <module>
    from .ui import UI
  File "/home/user/.local/lib/python2.7/site-packages/traitsui/ui.py", line 51, in <module>
    from .handler import Handler, ViewHandler
  File "/home/user/.local/lib/python2.7/site-packages/traitsui/handler.py", line 27, in <module>
    from inspect import getfullargspec
ImportError: cannot import name getfullargspec`

**Comment by prabhuramachandran** [comment]
That looks like an issue with your traitsui package and not Mayavi -- see the error message isn't from mayavi but from traitsui.  Downgrade to an older traitsui and this should work.  Try with traitsui 6.1.3 for example.  I am not sure how you have installed traitsui.

**Comment by kaalessi** [comment]
prabhuramachandran You are correct! I just looked at https://github.com/enthought/traitsui/releases and noticed that 7.0.0 dropped support for Python 2. Thanks
