### ISSUE TITLE
Testsuite failed during weekly CRON job run

### ISSUE THREAD

**Issue by rahulporuri** [enthought/mayavi#935]
ref : https://travis-ci.org/github/enthought/mayavi/builds/702500915

The failures are happening with VTK 8 + Python 3.6 on both MacOS and Linux variants. The test failures are : 

<details>

```
======================================================================

ERROR: Basic tests for the VTK module.

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/enthought/mayavi/tvtk/tests/test_class_tree.py", line 88, in test_basic_vtk

    self.assertEqual(names, expect)

UnboundLocalError: local variable 'expect' referenced before assignment

======================================================================

ERROR: Test ContextDevice2D Get/SetMatrix API

----------------------------------------------------------------------

Traceback (most recent call last):

  File "tvtk_classes/tvtk_helper.py", line 23, in get_module

    globals(), locals(), [fname])

ModuleNotFoundError: No module named 'tvtk.custom.bezier_triangle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/home/travis/build/enthought/mayavi/tvtk/tests/test_tvtk.py", line 823, in test_contextdevice2d_matrix_api

    if has_subclass(klass):

  File "/home/travis/build/enthought/mayavi/tvtk/tests/test_tvtk.py", line 68, in has_subclass

    return bool(inspect.getmembers(tvtk, is_sub_class))

  File "/home/travis/.edm/envs/edm/lib/python3.6/inspect.py", line 342, in getmembers

    value = getattr(object, key)

  File "tvtk_classes/tvtk_helper.py", line 1767, in <lambda>

    BezierTriangle = property(lambda self: get_class('BezierTriangle'))

  File "tvtk_classes/tvtk_helper.py", line 47, in get_class

    mod = get_module(fname)

  File "tvtk_classes/tvtk_helper.py", line 28, in get_module

    mod = __import__('tvtk.tvtk_classes.%s'%fname, globals(), locals(), [fname])

  File "<frozen importlib._bootstrap>", line 971, in _find_and_load

  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked

  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible

  File "tvtk_classes/bezier_triangle.py", line 29, in <module>

    from tvtk.tvtk_classes.higher_order_triangle import HigherOrderTriangle

  File "<frozen importlib._bootstrap>", line 971, in _find_and_load

  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked

  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible

  File "tvtk_classes/higher_order_triangle.py", line 32, in <module>

    class HigherOrderTriangle(NonLinearCell):

  File "tvtk_classes/higher_order_triangle.py", line 56, in HigherOrderTriangle

    parametric_coords = traits.Array(enter_set=True, auto_set=False, shape=(9,), dtype="float", value=(nan, nan, 0.0, 6.91176469033213e-310, 2.37e-322, 2.93e-321, 0.0, 2.20347903e-316, nan), cols=3, desc=\

NameError: name 'nan' is not defined

======================================================================

ERROR: Test if VTK object changes when trait is changed.

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/enthought/mayavi/tvtk/tests/test_tvtk.py", line 181, in test_do_change

    self.assertEqual(val, getattr(p, t))

  File "/home/travis/.edm/envs/edm/lib/python3.6/unittest/case.py", line 829, in assertEqual

    assertion_func(first, second, msg=msg)

  File "/home/travis/.edm/envs/edm/lib/python3.6/unittest/case.py", line 819, in _baseAssertEqual

    if not first == second:

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

======================================================================

ERROR: Test ObjectFactory Get/SetEnableFlag API

----------------------------------------------------------------------

Traceback (most recent call last):

  File "tvtk_classes/tvtk_helper.py", line 23, in get_module

    globals(), locals(), [fname])

ModuleNotFoundError: No module named 'tvtk.custom.bezier_triangle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/home/travis/build/enthought/mayavi/tvtk/tests/test_tvtk.py", line 803, in test_object_factory_enableflag_api

    if has_subclass(klass):

  File "/home/travis/build/enthought/mayavi/tvtk/tests/test_tvtk.py", line 68, in has_subclass

    return bool(inspect.getmembers(tvtk, is_sub_class))

  File "/home/travis/.edm/envs/edm/lib/python3.6/inspect.py", line 342, in getmembers

    value = getattr(object, key)

  File "tvtk_classes/tvtk_helper.py", line 1767, in <lambda>

    BezierTriangle = property(lambda self: get_class('BezierTriangle'))

  File "tvtk_classes/tvtk_helper.py", line 47, in get_class

    mod = get_module(fname)

  File "tvtk_classes/tvtk_helper.py", line 28, in get_module

    mod = __import__('tvtk.tvtk_classes.%s'%fname, globals(), locals(), [fname])

  File "<frozen importlib._bootstrap>", line 971, in _find_and_load

  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked

  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible

  File "tvtk_classes/bezier_triangle.py", line 29, in <module>

    from tvtk.tvtk_classes.higher_order_triangle import HigherOrderTriangle

  File "<frozen importlib._bootstrap>", line 971, in _find_and_load

  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked

  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible

  File "tvtk_classes/higher_order_triangle.py", line 32, in <module>

    class HigherOrderTriangle(NonLinearCell):

  File "tvtk_classes/higher_order_triangle.py", line 56, in HigherOrderTriangle

    parametric_coords = traits.Array(enter_set=True, auto_set=False, shape=(9,), dtype="float", value=(nan, nan, 0.0, 6.91176469033213e-310, 2.37e-322, 2.93e-321, 0.0, 2.20347903e-316, nan), cols=3, desc=\

NameError: name 'nan' is not defined

======================================================================

ERROR: Test if all the TVTK classes can be instantiated

----------------------------------------------------------------------

Traceback (most recent call last):

  File "tvtk_classes/tvtk_helper.py", line 23, in get_module

    globals(), locals(), [fname])

ModuleNotFoundError: No module named 'tvtk.custom.bezier_triangle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/home/travis/build/enthought/mayavi/tvtk/tests/test_tvtk.py", line 913, in setUp

    tvtk_klass = getattr(tvtk, tvtk_klass_name, None)

  File "tvtk_classes/tvtk_helper.py", line 1767, in <lambda>

    BezierTriangle = property(lambda self: get_class('BezierTriangle'))

  File "tvtk_classes/tvtk_helper.py", line 47, in get_class

    mod = get_module(fname)

  File "tvtk_classes/tvtk_helper.py", line 28, in get_module

    mod = __import__('tvtk.tvtk_classes.%s'%fname, globals(), locals(), [fname])

  File "<frozen importlib._bootstrap>", line 971, in _find_and_load

  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked

  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible

  File "tvtk_classes/bezier_triangle.py", line 29, in <module>

    from tvtk.tvtk_classes.higher_order_triangle import HigherOrderTriangle

  File "<frozen importlib._bootstrap>", line 971, in _find_and_load

  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked

  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible

  File "tvtk_classes/higher_order_triangle.py", line 32, in <module>

    class HigherOrderTriangle(NonLinearCell):

  File "tvtk_classes/higher_order_triangle.py", line 56, in HigherOrderTriangle

    parametric_coords = traits.Array(enter_set=True, auto_set=False, shape=(9,), dtype="float", value=(nan, nan, 0.0, 6.91176469033213e-310, 2.37e-322, 2.93e-321, 0.0, 2.20347903e-316, nan), cols=3, desc=\

NameError: name 'nan' is not defined

======================================================================

ERROR: Test if all of the traits can be obtained

----------------------------------------------------------------------

Traceback (most recent call last):

  File "tvtk_classes/tvtk_helper.py", line 23, in get_module

    globals(), locals(), [fname])

ModuleNotFoundError: No module named 'tvtk.custom.bezier_triangle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/home/travis/build/enthought/mayavi/tvtk/tests/test_tvtk.py", line 913, in setUp

    tvtk_klass = getattr(tvtk, tvtk_klass_name, None)

  File "tvtk_classes/tvtk_helper.py", line 1767, in <lambda>

    BezierTriangle = property(lambda self: get_class('BezierTriangle'))

  File "tvtk_classes/tvtk_helper.py", line 47, in get_class

    mod = get_module(fname)

  File "tvtk_classes/tvtk_helper.py", line 28, in get_module

    mod = __import__('tvtk.tvtk_classes.%s'%fname, globals(), locals(), [fname])

  File "<frozen importlib._bootstrap>", line 971, in _find_and_load

  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked

  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible

  File "tvtk_classes/bezier_triangle.py", line 29, in <module>

    from tvtk.tvtk_classes.higher_order_triangle import HigherOrderTriangle

  File "<frozen importlib._bootstrap>", line 971, in _find_and_load

  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked

  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible

  File "tvtk_classes/higher_order_triangle.py", line 32, in <module>

    class HigherOrderTriangle(NonLinearCell):

  File "tvtk_classes/higher_order_triangle.py", line 56, in HigherOrderTriangle

    parametric_coords = traits.Array(enter_set=True, auto_set=False, shape=(9,), dtype="float", value=(nan, nan, 0.0, 6.91176469033213e-310, 2.37e-322, 2.93e-321, 0.0, 2.20347903e-316, nan), cols=3, desc=\

NameError: name 'nan' is not defined

======================================================================

ERROR: test_import_tvtk_does_not_import_gui (tvtk.tests.test_tvtk.TestTVTKModule)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "tvtk_classes/tvtk_helper.py", line 23, in get_module

    globals(), locals(), [fname])

ModuleNotFoundError: No module named 'tvtk.custom.bezier_triangle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/home/travis/build/enthought/mayavi/tvtk/tests/test_tvtk.py", line 913, in setUp

    tvtk_klass = getattr(tvtk, tvtk_klass_name, None)

  File "tvtk_classes/tvtk_helper.py", line 1767, in <lambda>

    BezierTriangle = property(lambda self: get_class('BezierTriangle'))

  File "tvtk_classes/tvtk_helper.py", line 47, in get_class

    mod = get_module(fname)

  File "tvtk_classes/tvtk_helper.py", line 28, in get_module

    mod = __import__('tvtk.tvtk_classes.%s'%fname, globals(), locals(), [fname])

  File "<frozen importlib._bootstrap>", line 971, in _find_and_load

  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked

  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible

  File "tvtk_classes/bezier_triangle.py", line 29, in <module>

    from tvtk.tvtk_classes.higher_order_triangle import HigherOrderTriangle

  File "<frozen importlib._bootstrap>", line 971, in _find_and_load

  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked

  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible

  File "tvtk_classes/higher_order_triangle.py", line 32, in <module>

    class HigherOrderTriangle(NonLinearCell):

  File "tvtk_classes/higher_order_triangle.py", line 56, in HigherOrderTriangle

    parametric_coords = traits.Array(enter_set=True, auto_set=False, shape=(9,), dtype="float", value=(nan, nan, 0.0, 6.91176469033213e-310, 2.37e-322, 2.93e-321, 0.0, 2.20347903e-316, nan), cols=3, desc=\

NameError: name 'nan' is not defined

======================================================================

ERROR: Test if none of the TVTK classes' traits has a value of "*_p_void"

----------------------------------------------------------------------

Traceback (most recent call last):

  File "tvtk_classes/tvtk_helper.py", line 23, in get_module

    globals(), locals(), [fname])

ModuleNotFoundError: No module named 'tvtk.custom.bezier_triangle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/home/travis/build/enthought/mayavi/tvtk/tests/test_tvtk.py", line 913, in setUp

    tvtk_klass = getattr(tvtk, tvtk_klass_name, None)

  File "tvtk_classes/tvtk_helper.py", line 1767, in <lambda>

    BezierTriangle = property(lambda self: get_class('BezierTriangle'))

  File "tvtk_classes/tvtk_helper.py", line 47, in get_class

    mod = get_module(fname)

  File "tvtk_classes/tvtk_helper.py", line 28, in get_module

    mod = __import__('tvtk.tvtk_classes.%s'%fname, globals(), locals(), [fname])

  File "<frozen importlib._bootstrap>", line 971, in _find_and_load

  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked

  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible

  File "tvtk_classes/bezier_triangle.py", line 29, in <module>

    from tvtk.tvtk_classes.higher_order_triangle import HigherOrderTriangle

  File "<frozen importlib._bootstrap>", line 971, in _find_and_load

  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked

  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible

  File "tvtk_classes/higher_order_triangle.py", line 32, in <module>

    class HigherOrderTriangle(NonLinearCell):

  File "tvtk_classes/higher_order_triangle.py", line 56, in HigherOrderTriangle

    parametric_coords = traits.Array(enter_set=True, auto_set=False, shape=(9,), dtype="float", value=(nan, nan, 0.0, 6.91176469033213e-310, 2.37e-322, 2.93e-321, 0.0, 2.20347903e-316, nan), cols=3, desc=\

NameError: name 'nan' is not defined

======================================================================

ERROR: Test if all the attributes with MinValue/MaxValue are traits

----------------------------------------------------------------------

Traceback (most recent call last):

  File "tvtk_classes/tvtk_helper.py", line 23, in get_module

    globals(), locals(), [fname])

ModuleNotFoundError: No module named 'tvtk.custom.bezier_triangle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/home/travis/build/enthought/mayavi/tvtk/tests/test_tvtk.py", line 913, in setUp

    tvtk_klass = getattr(tvtk, tvtk_klass_name, None)

  File "tvtk_classes/tvtk_helper.py", line 1767, in <lambda>

    BezierTriangle = property(lambda self: get_class('BezierTriangle'))

  File "tvtk_classes/tvtk_helper.py", line 47, in get_class

    mod = get_module(fname)

  File "tvtk_classes/tvtk_helper.py", line 28, in get_module

    mod = __import__('tvtk.tvtk_classes.%s'%fname, globals(), locals(), [fname])

  File "<frozen importlib._bootstrap>", line 971, in _find_and_load

  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked

  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible

  File "tvtk_classes/bezier_triangle.py", line 29, in <module>

    from tvtk.tvtk_classes.higher_order_triangle import HigherOrderTriangle

  File "<frozen importlib._bootstrap>", line 971, in _find_and_load

  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked

  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible

  File "tvtk_classes/higher_order_triangle.py", line 32, in <module>

    class HigherOrderTriangle(NonLinearCell):

  File "tvtk_classes/higher_order_triangle.py", line 56, in HigherOrderTriangle

    parametric_coords = traits.Array(enter_set=True, auto_set=False, shape=(9,), dtype="float", value=(nan, nan, 0.0, 6.91176469033213e-310, 2.37e-322, 2.93e-321, 0.0, 2.20347903e-316, nan), cols=3, desc=\

NameError: name 'nan' is not defined

======================================================================

FAIL: test_get_children (tvtk.tests.test_browser.TestFullTreeGenrator)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/enthought/mayavi/tvtk/tests/test_browser.py", line 112, in test_get_children

    self.assertTrue(len(kids) in [6, 7])

AssertionError: False is not true

======================================================================

FAIL: test_box (tvtk.tests.test_visual.TestVisual)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/enthought/mayavi/tvtk/tests/test_visual.py", line 170, in test_box

    assert_allclose(b.polydata.bounds, bounds)

  File "/home/travis/.edm/envs/edm/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 1515, in assert_allclose

    verbose=verbose, header=header, equal_nan=equal_nan)

  File "/home/travis/.edm/envs/edm/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 841, in assert_array_compare

    raise AssertionError(msg)

AssertionError: 

Not equal to tolerance rtol=1e-07, atol=0

Mismatch: 66.7%

Max absolute difference: 0.20710678

Max relative difference: 0.29289322

 x: array([-0.5,  0.5, -0.5,  0.5, -0.5,  0.5])

 y: array([-0.707107,  0.707107, -0.707107,  0.707107, -0.5     ,  0.5     ])

======================================================================

FAIL: test_helix (tvtk.tests.test_visual.TestVisual)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/enthought/mayavi/tvtk/tests/test_visual.py", line 258, in test_helix

    assert_allclose(h.polydata.bounds, bounds, atol=3e-2, rtol=0)

  File "/home/travis/.edm/envs/edm/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 1515, in assert_allclose

    verbose=verbose, header=header, equal_nan=equal_nan)

  File "/home/travis/.edm/envs/edm/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 841, in assert_array_compare

    raise AssertionError(msg)

AssertionError: 

Not equal to tolerance rtol=0, atol=0.03

Mismatch: 66.7%

Max absolute difference: 0.8097887

Max relative difference: 0.66666667

 x: array([1.02    , 2.      , 0.809789, 1.190211, 0.8     , 1.2     ])

 y: array([0.8, 1.2, 1. , 2. , 0.8, 1.2])

======================================================================

FAIL: Check if parser is usable without the tree.

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/enthought/mayavi/tvtk/tests/test_vtk_parser.py", line 272, in test_no_tree

    self.test_parse()

  File "/home/travis/build/enthought/mayavi/tvtk/tests/test_vtk_parser.py", line 49, in test_parse

    {'Debug': 0, 'GlobalWarningDisplay': 1})

AssertionError: {'Debug': False, 'GlobalWarningDisplay': 0} != {'Debug': 0, 'GlobalWarningDisplay': 1}

- {'Debug': False, 'GlobalWarningDisplay': 0}

?           ^^^^^                          ^

+ {'Debug': 0, 'GlobalWarningDisplay': 1}

?           ^                          ^

======================================================================

FAIL: Check if the methods are organized correctly.

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/enthought/mayavi/tvtk/tests/test_vtk_parser.py", line 49, in test_parse

    {'Debug': 0, 'GlobalWarningDisplay': 1})

AssertionError: {'Debug': False, 'GlobalWarningDisplay': 0} != {'Debug': 0, 'GlobalWarningDisplay': 1}

- {'Debug': False, 'GlobalWarningDisplay': 0}

?           ^^^^^                          ^

+ {'Debug': 0, 'GlobalWarningDisplay': 1}

?           ^                          ^
```

</details>

**Comment by prabhuramachandran** [comment]
Yes, it has been broken for a while with VTK 9 not sure this has to do with VTK 8, the script tells you VTK 8 but thats bogus, it is really pulling the 9 wheels.  There is just too much happening so I haven't had the chance to fix this. :(
