### ISSUE TITLE
Error when running "mayavi2"

### ISSUE THREAD

**Issue by zhengpuchen** [enthought/mayavi#950]
I met a similar problem as issue #944 

When I tried running "mayavi2" in terminal, I got following error:

Exception occurred in traits notification handler for object: <mayavi.plugins.mayavi_ui_plugin.MayaviUIPlugin object at 0x2ab031a0a150>, trait: application, old value: None, new value: <mayavi.plugins.mayavi_workbench_application.MayaviWorkbenchApplication object at 0x2ab031a0a3b8>
Traceback (most recent call last):
  File "/home/.conda/envs/cent7/5.1.0-py27/Test/lib/python3.6/site-packages/traits/trait_notifiers.py", line 580, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/home/.conda/envs/cent7/5.1.0-py27/Test/lib/python3.6/site-packages/traits/trait_notifiers.py", line 484, in dispatch
    handler(*args)
  File "/home/.conda/envs/cent7/5.1.0-py27/Test/lib/python3.6/site-packages/traits/traits_listener.py", line 412, in handle_simple
    self.next.register(new)
  File "/home/.conda/envs/cent7/5.1.0-py27/Test/lib/python3.6/site-packages/traits/traits_listener.py", line 386, in register
    value = getattr(self, type)(new, name, False)
  File "/home/.conda/envs/cent7/5.1.0-py27/Test/lib/python3.6/site-packages/traits/traits_listener.py", line 607, in _register_simple
    return next.register(getattr(object, name))
  File "/home/.conda/envs/cent7/5.1.0-py27/Test/lib/python3.6/site-packages/envisage/ui/workbench/workbench_application.py", line 132, in _gui_default
    return GUI(splash_screen=self.splash_screen)
  File "/home/.conda/envs/cent7/5.1.0-py27/Test/lib/python3.6/site-packages/mayavi/plugins/mayavi_workbench_application.py", line 121, in _splash_screen_default
    show_log_messages = True,
  File "/home/.conda/envs/cent7/5.1.0-py27/Test/lib/python3.6/site-packages/pyface/base_toolkit.py", line 184, in __init__
    raise NotImplementedError(msg % (toolkit, package, name))
NotImplementedError: the null pyface.ui.null backend doesn't implement splash_screen:SplashScreen
Exception occurred in traits notification handler for object: <mayavi.scripts.mayavi2.MayaviApp object at 0x2ab0316ea888>, trait: application, old value: None, new value: <mayavi.plugins.mayavi_workbench_application.MayaviWorkbenchApplication object at 0x2ab031a0a3b8>
Traceback (most recent call last):
  File "/home/.conda/envs/cent7/5.1.0-py27/Test/lib/python3.6/site-packages/traits/trait_notifiers.py", line 580, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/home/.conda/envs/cent7/5.1.0-py27/Test/lib/python3.6/site-packages/traits/trait_notifiers.py", line 484, in dispatch
    handler(*args)
  File "/home/.conda/envs/cent7/5.1.0-py27/Test/lib/python3.6/site-packages/traits/traits_listener.py", line 412, in handle_simple
    self.next.register(new)
  File "/home/.conda/envs/cent7/5.1.0-py27/Test/lib/python3.6/site-packages/traits/traits_listener.py", line 386, in register
    value = getattr(self, type)(new, name, False)
  File "/home/.conda/envs/cent7/5.1.0-py27/Test/lib/python3.6/site-packages/traits/traits_listener.py", line 607, in _register_simple
    return next.register(getattr(object, name))
  File "/home/.conda/envs/cent7/5.1.0-py27/Test/lib/python3.6/site-packages/envisage/ui/workbench/workbench_application.py", line 132, in _gui_default
    return GUI(splash_screen=self.splash_screen)
  File "/home/.conda/envs/cent7/5.1.0-py27/Test/lib/python3.6/site-packages/mayavi/plugins/mayavi_workbench_application.py", line 121, in _splash_screen_default
    show_log_messages = True,
  File "/home/.conda/envs/cent7/5.1.0-py27/Test/lib/python3.6/site-packages/pyface/base_toolkit.py", line 184, in __init__
    raise NotImplementedError(msg % (toolkit, package, name))
NotImplementedError: the null pyface.ui.null backend doesn't implement splash_screen:SplashScreen
Traceback (most recent call last):
  File "/home/.conda/envs/cent7/5.1.0-py27/Test/bin/mayavi2", line 8, in <module>
    sys.exit(main())
  File "/home/.conda/envs/cent7/5.1.0-py27/Test/lib/python3.6/site-packages/mayavi/scripts/mayavi2.py", line 602, in main
    mayavi.main(sys.argv[1:])
  File "/home/.conda/envs/cent7/5.1.0-py27/Test/lib/python3.6/site-packages/mayavi/plugins/app.py", line 195, in main
    app.run()
  File "/home/.conda/envs/cent7/5.1.0-py27/Test/lib/python3.6/site-packages/mayavi/plugins/mayavi_workbench_application.py", line 73, in run
    gui = self.gui
  File "/home/.conda/envs/cent7/5.1.0-py27/Test/lib/python3.6/site-packages/envisage/ui/workbench/workbench_application.py", line 132, in _gui_default
    return GUI(splash_screen=self.splash_screen)
  File "/home/.conda/envs/cent7/5.1.0-py27/Test/lib/python3.6/site-packages/mayavi/plugins/mayavi_workbench_application.py", line 121, in _splash_screen_default
    show_log_messages = True,
  File "/home/.conda/envs/cent7/5.1.0-py27/Test/lib/python3.6/site-packages/pyface/base_toolkit.py", line 184, in __init__
    raise NotImplementedError(msg % (toolkit, package, name))
NotImplementedError: the null pyface.ui.null backend doesn't implement splash_screen:SplashScreen

When I tried running an example using mayavi library, I got following error:

Traceback (most recent call last):
  File "protein.py", line 121, in <module>
    mlab.figure(1, bgcolor=(0, 0, 0))
  File "/home/.conda/envs/cent7/5.1.0-py27/Test/lib/python3.6/site-packages/mayavi/tools/figure.py", line 64, in figure
    engine = get_engine()
  File "/home/.conda/envs/cent7/5.1.0-py27/Test/lib/python3.6/site-packages/mayavi/tools/engine_manager.py", line 92, in get_engine
    return self.new_engine()
  File "/home/.conda/envs/cent7/5.1.0-py27/Test/lib/python3.6/site-packages/mayavi/tools/engine_manager.py", line 137, in new_engine
    check_backend()
  File "/home/.conda/envs/cent7/5.1.0-py27/Test/lib/python3.6/site-packages/mayavi/tools/engine_manager.py", line 40, in check_backend
    raise ImportError(msg)
ImportError: Could not import backend for traitsui.  Make sure you
        have a suitable UI toolkit like PyQt/PySide or wxPython
        installed.

I think the problem may caused by the upgrading of some dependent packages. The version of the packages are listed below:
apptools        4.5.0
certifi         2020.6.20
click           7.1.2
configobj       5.0.6
cycler          0.10.0
edempy          0.1.4
envisage        4.7.0
gitdb           4.0.5
GitPython       3.1.1
h5py            2.10.0
kiwisolver      1.2.0
matplotlib      3.3.0
mayavi          4.7.1
numpy           1.19.0
packaging       20.4
pandas          1.0.5
physt           0.4.10.1
Pillow          7.2.0
pip             20.1.1
pyface          7.0.1
Pygments        2.6.1
pyparsing       2.4.7
python-dateutil 2.8.1
pytz            2020.1
scipy           1.5.2
setuptools      49.2.0
six             1.15.0
smmap           3.0.4
traits          6.1.1
traitsui        7.0.1
vtk             8.1.2
wheel           0.34.2

**Comment by rahulporuri** [comment]
@zhengpuchen the error message is a little cryptic but it mentions what the underlying problem is - ` NotImplementedError: the null pyface.ui.null backend doesn't implement **splash_screen:SplashScreen`. In order to run the `mayavi2` application or to run one of the examples, you will need to install a GUI backend package for example PyQt5 or PySide2 on Python 3. Without them, mayavi cannot create GUI windows.

Can you please install them and try again?

**Comment by zhengpuchen** [comment]
I installed both PyQt5 and Pyside2, however, the same error persists.

**Comment by WxComeon** [comment]
@zhengpuchen Were you able to resolve the problem? I have the same issue - installed both PyQt5 and Pyside2, doesn't work :(

**Comment by CalebDmArcher** [comment]
> @zhengpuchen Were you able to resolve the problem? I have the same issue - installed both PyQt5 and Pyside2, doesn't work :(

Not sure if you still need help. But after checking whether I have successfully installed PyQt5 and VTK and installed them if I haven't, it works fine for me.
