### ISSUE TITLE
No module named 'traits._py2to3'

### ISSUE THREAD

**Issue by steel3d** [enthought/mayavi#953]
I tried upgrading mayavi today (after using it all day). Can't use it anymore.

I upgraded to mayavi 4.7.1 and traits 6.1.1:

`
c:\Steve\p4>pip install --upgrade --user mayavi
Requirement already up-to-date: mayavi in c:\users\steve\appdata\local\programs\python\python36\lib\site-packages (4.7.1)
Requirement already satisfied, skipping upgrade: pyface>=6.1.1 in c:\users\steve\appdata\local\programs\python\python36\lib\site-packages (from mayavi) (7.0.1)
Requirement already satisfied, skipping upgrade: pygments in c:\users\steve\appdata\local\programs\python\python36\lib\site-packages (from mayavi) (2.2.0)
Processing c:\users\steve\appdata\local\pip\cache\wheels\25\73\54\c034c1b79c3bcac3102f82236ee7fe05e341cd9839ae94c07c\traits-6.1.1-cp36-cp36m-win_amd64.whl
Requirement already satisfied, skipping upgrade: traitsui>=6.0.0 in c:\users\steve\appdata\local\programs\python\python36\lib\site-packages (from mayavi) (6.0.0)
Requirement already satisfied, skipping upgrade: envisage in c:\users\steve\appdata\local\programs\python\python36\lib\site-packages (from mayavi) (4.7.1)
Requirement already satisfied, skipping upgrade: vtk in c:\users\steve\appdata\local\programs\python\python36\lib\site-packages (from mayavi) (8.1.2)
Requirement already satisfied, skipping upgrade: numpy in c:\users\steve\appdata\local\programs\python\python36\lib\site-packages (from mayavi) (1.18.4)
Requirement already satisfied, skipping upgrade: apptools in c:\users\steve\appdata\local\programs\python\python36\lib\site-packages (from mayavi) (4.4.0)
Requirement already satisfied, skipping upgrade: configobj in c:\users\steve\appdata\local\programs\python\python36\lib\site-packages (from apptools->mayavi) (5.0.6)
Requirement already satisfied, skipping upgrade: six in c:\users\steve\appdata\local\programs\python\python36\lib\site-packages (from configobj->apptools->mayavi) (1.11.0)
Installing collected packages: traits
Successfully installed traits-6.1.1
`

I get an error on import:

`
c:\Steve\p4\py\pnet\pnet>python pnet.py
Traceback (most recent call last):
  File "pnet.py", line 25, in <module>
    from mayavi import mlab
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python36\lib\site-packages\mayavi\mlab.py", line 16, in <module>
    from mayavi.tools.camera import view, roll, yaw, pitch, move
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python36\lib\site-packages\mayavi\tools\camera.py", line 24, in <module>
    from .engine_manager import get_engine
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python36\lib\site-packages\mayavi\tools\engine_manager.py", line 12, in <module>
    from mayavi.preferences.api import preference_manager
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python36\lib\site-packages\mayavi\preferences\api.py", line 4, in <module>
    from .preference_manager import preference_manager
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python36\lib\site-packages\mayavi\preferences\preference_manager.py", line 29, in <module>
    from traitsui.api import View, Group, Item
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python36\lib\site-packages\traitsui\api.py", line 31, in <module>
    from .editor import Editor
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python36\lib\site-packages\traitsui\editor.py", line 51, in <module>
    from .item import Item
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python36\lib\site-packages\traitsui\item.py", line 34, in <module>
    import traits._py2to3 as _py2to3
ModuleNotFoundError: No module named 'traits._py2to3'
`

**Comment by mdickinson** [comment]
It looks as though you're using an old version of TraitsUI. Can you try upgrading the `traitsui` package?

**Comment by steel3d** [comment]
Wow! Thanks for the quick response! That fixed it!

So I guess this requirement needs to be updated to a higher version? 

"Requirement already satisfied, skipping upgrade: traitsui>=6.0.0"

**Comment by mdickinson** [comment]
Yes, I think it may make sense to update the dependencies to require TraitsUI 7.0 or later. @prabhuramachandran Opinions?

**Comment by prabhuramachandran** [comment]
Sure, I don't have a problem with that.  Perhaps this should be done before the next Mayavi release.

**Comment by prabhuramachandran** [comment]
@mdickinson  -- I am also going to bump the requirement for traits to be traits>=6.0.0, I guess that should be fine too right?

**Comment by prabhuramachandran** [comment]
This is now in the 4.7.2 release.

**Comment by mdickinson** [comment]
> I am also going to bump the requirement for traits to be traits>=6.0.0

Sounds good to me!

**Comment by Roly83** [comment]
Hola tengo un problema al crear mi ejecutable para Windows estoy utilizando la biblioteca de Mayavi que me gusta mucho y me parece genial, pero me esta generando este error y no tengo idea de como solucionarlo                                                                                                                          Traceback (most recent call last):
  File "pyface\base_toolkit.py", line 219, in import_toolkit
  File "importlib\metadata\__init__.py", line 162, in load
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'traitsui.null'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Caver_Mapping3.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "mayavi\mlab.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "mayavi\tools\camera.py", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "mayavi\tools\engine_manager.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "mayavi\preferences\api.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "mayavi\preferences\preference_manager.py", line 29, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "traitsui\api.py", line 257, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "traitsui\editors\__init__.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "traitsui\editors\api.py", line 96, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "traitsui\editors\code_editor.py", line 21, in <module>
  File "traitsui\editors\code_editor.py", line 32, in CodeEditor
  File "traits\trait_factory.py", line 40, in __call__
  File "traitsui\toolkit_traits.py", line 43, in ColorTrait
  File "traitsui\toolkit.py", line 110, in toolkit
  File "pyface\base_toolkit.py", line 294, in find_toolkit
  File "pyface\base_toolkit.py", line 231, in import_toolkit
RuntimeError: No traitsui.toolkits plugin could be loaded for null
