### ISSUE TITLE
lastest mayavi not working with wxpython

### ISSUE THREAD

**Issue by shlomok613** [enthought/mayavi#972]
Please can help me. I am having trouble running mayavi with wxpython

ran mayavi2 with pyqt5 and comes up with properly

removed pyqt5 and installed wxpython

ran mayavi2 with wxpython and I just see the splash screen but no ide.

when I run https://docs.enthought.com/mayavi/mayavi/auto/example_wx_embedding.html I get this crash:

Traceback (most recent call last):
  File "C:/Users/Owner/AppData/Roaming/JetBrains/PyCharmCE2020.2/scratches/scratch_37.py", line 47, in <module>
    frame = MainWindow(None, wx.ID_ANY)
  File "C:/Users/Owner/AppData/Roaming/JetBrains/PyCharmCE2020.2/scratches/scratch_37.py", line 43, in __init__
    kind='subpanel').control
  File "C:\sixdof\mayavi\venv\lib\site-packages\traits\has_traits.py", line 1678, in edit_traits
    args,
  File "C:\sixdof\mayavi\venv\lib\site-packages\traitsui\view.py", line 462, in ui
    ui.ui(parent, kind)
  File "C:\sixdof\mayavi\venv\lib\site-packages\traitsui\ui.py", line 244, in ui
    self.rebuild(self, parent)
  File "C:\sixdof\mayavi\venv\lib\site-packages\traitsui\wx\toolkit.py", line 108, in ui_subpanel
    ui_panel.ui_subpanel(ui, parent)
  File "C:\sixdof\mayavi\venv\lib\site-packages\traitsui\wx\ui_panel.py", line 85, in ui_subpanel
    ui_panel_for(ui, parent, False)
  File "C:\sixdof\mayavi\venv\lib\site-packages\traitsui\wx\ui_panel.py", line 95, in ui_panel_for
    ui.control = control = Panel(ui, parent, buttons).control
  File "C:\sixdof\mayavi\venv\lib\site-packages\traitsui\wx\ui_panel.py", line 174, in __init__
    sw = panel(ui, cpanel)
  File "C:\sixdof\mayavi\venv\lib\site-packages\traitsui\wx\ui_panel.py", line 274, in panel
    panel, content[0], ui
  File "C:\sixdof\mayavi\venv\lib\site-packages\traitsui\wx\ui_panel.py", line 433, in fill_panel_for_group
    panel, group, ui, suppress_label, is_dock_window, create_panel
  File "C:\sixdof\mayavi\venv\lib\site-packages\traitsui\wx\ui_panel.py", line 589, in __init__
    self.add_items(content, panel, self.sizer)
  File "C:\sixdof\mayavi\venv\lib\site-packages\traitsui\wx\ui_panel.py", line 909, in add_items
    editor.prepare(item_panel)
  File "C:\sixdof\mayavi\venv\lib\site-packages\traitsui\editor.py", line 236, in prepare
    self.init(parent)
  File "C:\sixdof\mayavi\venv\lib\site-packages\tvtk\pyface\ui\wx\scene_editor.py", line 59, in init
    self._create_scene()
  File "C:\sixdof\mayavi\venv\lib\site-packages\tvtk\pyface\ui\wx\scene_editor.py", line 100, in _create_scene
    self._scene = factory.scene_class(self.control)
  File "C:\sixdof\mayavi\venv\lib\site-packages\tvtk\pyface\ui\wx\decorated_scene.py", line 70, in __init__
    self._setup_axes_marker()
  File "C:\sixdof\mayavi\venv\lib\site-packages\tvtk\pyface\ui\wx\decorated_scene.py", line 127, in _setup_axes_marker
    self._background_changed(self.background)
  File "C:\sixdof\mayavi\venv\lib\site-packages\tvtk\pyface\ui\wx\decorated_scene.py", line 204, in _background_changed
    m.set_outline_color(0,0,0)
AttributeError: 'OrientationMarkerWidget' object has no attribute 'set_outline_color'

I have tried running with wxpython 4.0.5 and get the same result.

Here is my environment

(venv) C:\sixdof\mayavi>python
Python 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

(venv) C:\sixdof\mayavi>pip list
Package        Version
-------------- -------
apptools       4.5.0
configobj      5.0.6
envisage       4.9.2
mayavi         4.7.2
numpy          1.19.3
Pillow         8.0.1
pip            20.2.4
pip-autoremove 0.9.1
pyface         7.1.0
Pygments       2.7.2
setuptools     50.3.2
six            1.15.0
traits         6.1.1
traitsui       7.1.0
vtk            9.0.1
wxPython       4.1.0

**Comment by rahulporuri** [comment]
@shlomok613 thanks for reporting this issue. I edited the title and description of the issue, I hope that is okay with you.
I am also able to reproduce this issue on my windows 10 machine with the latest mayavi (4.7.2) and wxPython 4.1.0 on windows.

Additionally, when I run `python -m mayavi.scripts.mayavi2` which is what gets run by the `mayavi2` console script, I see the error

```
(test)C:\Users\rporuri\work\github\ets\mayavi\examples\mayavi\interactive>python -m mayavi.scripts.mayavi2
Traceback (most recent call last):
  File "C:\Users\rporuri\.edm\envs\test\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\rporuri\.edm\envs\test\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\rporuri\.edm\envs\test\lib\site-packages\mayavi\scripts\mayavi2.py", line 613, in <module>
    main()
  File "C:\Users\rporuri\.edm\envs\test\lib\site-packages\mayavi\scripts\mayavi2.py", line 602, in main
    mayavi.main(sys.argv[1:])
  File "C:\Users\rporuri\.edm\envs\test\lib\site-packages\mayavi\plugins\app.py", line 197, in main
    app.run()
  File "C:\Users\rporuri\.edm\envs\test\lib\site-packages\mayavi\plugins\mayavi_workbench_application.py", line 81, in run
    window.open()
  File "C:\Users\rporuri\.edm\envs\test\lib\site-packages\pyface\workbench\workbench_window.py", line 152, in open
    self._create()
  File "C:\Users\rporuri\.edm\envs\test\lib\site-packages\pyface\ui\wx\application_window.py", line 128, in _create
    self._create_trim_widgets(self.control)
  File "C:\Users\rporuri\.edm\envs\test\lib\site-packages\pyface\i_application_window.py", line 151, in _create_trim_widgets
    self._create_menu_bar(parent)
  File "C:\Users\rporuri\.edm\envs\test\lib\site-packages\pyface\ui\wx\application_window.py", line 77, in _create_menu_bar
    menu_bar = self.menu_bar_manager.create_menu_bar(parent)
  File "C:\Users\rporuri\.edm\envs\test\lib\site-packages\pyface\workbench\action\menu_bar_manager.py", line 39, in create_menu_bar
    parent, controller=controller
  File "C:\Users\rporuri\.edm\envs\test\lib\site-packages\pyface\ui\wx\action\menu_bar_manager.py", line 44, in create_menu_bar
    menu = item.create_menu(parent, controller)
  File "C:\Users\rporuri\.edm\envs\test\lib\site-packages\pyface\ui\wx\action\menu_manager.py", line 56, in create_menu
    return _Menu(self, parent, controller)
  File "C:\Users\rporuri\.edm\envs\test\lib\site-packages\pyface\ui\wx\action\menu_manager.py", line 106, in __init__
    self.refresh()
  File "C:\Users\rporuri\.edm\envs\test\lib\site-packages\pyface\ui\wx\action\menu_manager.py", line 147, in refresh
    parent, group, previous_non_empty_group
  File "C:\Users\rporuri\.edm\envs\test\lib\site-packages\pyface\ui\wx\action\menu_manager.py", line 204, in _add_group
    item.add_to_menu(parent, self, self._controller)
  File "C:\Users\rporuri\.edm\envs\test\lib\site-packages\pyface\ui\wx\action\menu_manager.py", line 66, in add_to_menu
    id = sub.GetId()
AttributeError: '_Menu' object has no attribute 'GetId'
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(475) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed

The above exception was the direct cause of the following exception:

SystemError: <class 'property'> returned a result with an error set
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(475) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed

The above exception was the direct cause of the following exception:

SystemError: <class 'wx._core.WindowDestroyEvent'> returned a result with an error set
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(475) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed

The above exception was the direct cause of the following exception:

SystemError: <class 'property'> returned a result with an error set
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(475) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed

The above exception was the direct cause of the following exception:

SystemError: <class 'wx._core.ActivateEvent'> returned a result with an error set
Error in atexit._run_exitfuncs:
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(475) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed
```
