### ISSUE TITLE
VectorCutPlane error

### ISSUE THREAD

**Issue by erthalion** [enthought/mayavi#98]
I have a strange problem with an applying of the VectorCutPlane to [this file](https://www.dropbox.com/s/nj2fi78riio9us9/boundary2.vtk). This problem is well reproduced, but I don't know is it related to the Mayavi or not?

```
Program received signal SIGSEGV, Segmentation fault.
0x00007fffe79a6259 in vtkCutter::UnstructuredGridCutter(vtkDataSet*, vtkPolyData*) () from /usr/lib64/libvtkGraphics.so.5.10
(gdb) bt
#0  0x00007fffe79a6259 in vtkCutter::UnstructuredGridCutter(vtkDataSet*, vtkPolyData*) () from /usr/lib64/libvtkGraphics.so.5.10
#1  0x00007fffe79a7f26 in vtkCutter::RequestData(vtkInformation*, vtkInformationVector**, vtkInformationVector*) () from /usr/lib64/libvtkGraphics.so.5.10
#2  0x00007fffe79a3761 in vtkCutter::ProcessRequest(vtkInformation*, vtkInformationVector**, vtkInformationVector*) () from /usr/lib64/libvtkGraphics.so.5.10
#3  0x00007fffec769a05 in vtkExecutive::CallAlgorithm(vtkInformation*, int, vtkInformationVector**, vtkInformationVector*) () from /usr/lib64/libvtkFiltering.so.5.10
#4  0x00007fffec75c23e in vtkDemandDrivenPipeline::ExecuteData(vtkInformation*, vtkInformationVector**, vtkInformationVector*) () from /usr/lib64/libvtkFiltering.so.5.10
#5  0x00007fffec75f392 in vtkDemandDrivenPipeline::ProcessRequest(vtkInformation*, vtkInformationVector**, vtkInformationVector*) ()
   from /usr/lib64/libvtkFiltering.so.5.10
#6  0x00007fffec96f784 in vtkStreamingDemandDrivenPipeline::ProcessRequest(vtkInformation*, vtkInformationVector**, vtkInformationVector*) ()
   from /usr/lib64/libvtkFiltering.so.5.10
#7  0x00007fffec76c0d6 in vtkExecutive::ForwardUpstream(vtkInformation*) () from /usr/lib64/libvtkFiltering.so.5.10
#8  0x00007fffec75f33c in vtkDemandDrivenPipeline::ProcessRequest(vtkInformation*, vtkInformationVector**, vtkInformationVector*) ()
   from /usr/lib64/libvtkFiltering.so.5.10
#9  0x00007fffec96f784 in vtkStreamingDemandDrivenPipeline::ProcessRequest(vtkInformation*, vtkInformationVector**, vtkInformationVector*) ()
   from /usr/lib64/libvtkFiltering.so.5.10
#10 0x00007fffec76c0d6 in vtkExecutive::ForwardUpstream(vtkInformation*) () from /usr/lib64/libvtkFiltering.so.5.10
#11 0x00007fffec75f33c in vtkDemandDrivenPipeline::ProcessRequest(vtkInformation*, vtkInformationVector**, vtkInformationVector*) ()
   from /usr/lib64/libvtkFiltering.so.5.10
#12 0x00007fffec96f784 in vtkStreamingDemandDrivenPipeline::ProcessRequest(vtkInformation*, vtkInformationVector**, vtkInformationVector*) ()
   from /usr/lib64/libvtkFiltering.so.5.10
```

Mayavi version 4.1.0 - VTK version 5.10.0
Python 2.7.5 
wxPython 2.8.12.1

**Comment by stefanoborini** [comment]
Cannot reproduce on Mayavi 4.4.4, VTK 6.3 on OSX. Can you please check if this is still broken with a most recent release?
